Terrain Moves Cause Permament BG Change
rh-hideout/pokeemerald-expansion pull request #1240
Opened 2020-11-18 02:47 UTC by ghoulslash

## Description
Terrain Moves cause a permanent BG change until they fade, as in the regular games. See example:
![permanent_terrain](https://user-images.githubusercontent.com/41651341/99476361-a71de500-290d-11eb-920b-fca309b1688b.gif)

2020-11-18 03:17 UTC, MandL27 commented
Gen 8 mainline changed it to subtler effects more in line with weather (e.g. don't hide actual battle terrain). I'd be more a fan of implementing terrain visuals that way.

2020-11-18 03:23 UTC, ghoulslash commented
> Gen 8 mainline changed it to subtler effects more in line with weather (e.g. don't hide actual battle terrain). I'd be more a fan of implementing terrain visuals that way.

I'll make it a config option, then

2020-11-20 23:40 UTC, AsparagusEduardo submitted a review, later dismissed

2020-11-25 02:03 UTC, AsparagusEduardo requested changes

2020-11-25 02:03 UTC, AsparagusEduardo commented on include/constants/battle_config.h
> +#define B_TERRAIN_BG_CHANGE             TRUE    //if TRUE, terrain moves permanently change the default battle bg until the effect fades
```suggestion
#define B_TERRAIN_BG_CHANGE             TRUE    // If TRUE, terrain moves permanently change the default battle background until the effect fades.
```

2020-11-25 02:34 UTC, AsparagusEduardo approved these changes

2020-12-04 04:04 UTC, ultima-soul approved these changes

2020-12-04 04:04 UTC, merged