Totem Boosts
rh-hideout/pokeemerald-expansion pull request #1242
Opened 2020-11-19 17:43 UTC by ghoulslash

## Description
- Adds totem boosts (from gen 7) to the battle engine.
- No config option is added because the user can just not set the totem boosts and it will never activate.
- Each stat can be raised/lowered by a unique value per battler.

Here is a GIF of a variety of stat changes occurring:
![totem](https://user-images.githubusercontent.com/41651341/99702838-8cee1f00-2a53-11eb-94aa-daa50016d7d5.gif)

### Mechanics
A `gTotemBoosts` EWRAM_DATA struct is added for each battler. It looks like:
```
struct TotemBoost {
    u8 stats;   //bitfield for each battle stat
    u8 statChanges[NUM_BATTLE_STATS - 1];    //highest bit is decrease
}; /* size = 8 */
```
- the `stats` element is a bitfield for each stat stage (7), with the last bit being used as a flag for the "totem flared to life" message.
- the `statChanges` element is 7 bytes (1 per stat stage), and is set to the number of stages to change by. The last bit, `0x80` is set to decrease the stat instead of raise
- A plethora of macros are added to the bottom of `asm/macros/event.inc` for +1 and +2 each independent stat. But the primary script macro, `settotemboost`, allows the user to customize their totem experience.

2020-12-04 08:28 UTC, ultima-soul requested changes
Functions mostly fine aside from the negative numbers not working as expected.

One more thing to change is that the totem boost happens before abilities activate (like Drought etc.) from what I tested in USUM.

2020-12-04 08:28 UTC, ultima-soul commented on src/battle_script_commands.c
> +                    u8 change = gTotemBoosts[gActiveBattler].statChanges[i] & 0x7F;
```suggestion
                    u8 change = gTotemBoosts[gActiveBattler].statChanges[i] & 0xF;
```
Is one solution to fixing an issue where numbers like -1 aren't properly being converted due to a cast from u8 to s8 in `ChangeStatBuff`.

2020-12-06 04:02 UTC, ghoulslash commented
Updates:
- allow negative script cmd values (instead of needing 0x80 bit set)
- Totem boosts occur before switch-in abilities:
![totem](https://user-images.githubusercontent.com/41651341/101271085-0452cc80-373d-11eb-8fe8-7ceba758836a.gif)

Ready for re-review

2020-12-07 23:59 UTC, ultima-soul submitted a review, later dismissed

2020-12-19 02:25 UTC, ultima-soul approved these changes

2020-12-31 23:55 UTC, ExpoSeed requested changes
if `settotemboost` precedes `trainerbattle`, the game jumps to invalid address 101C101C

quick example to reproduce:
```arm
Route102_EventScript_Rick:: @ 81EC1B3
	settotemboost 0, -2, -2, -2, -2, -2, -2, -2
	trainerbattle_single TRAINER_RICK, Route102_Text_RickIntro, Route102_Text_RickDefeated
	msgbox Route102_Text_RickPostBattle, MSGBOX_AUTOCLOSE
	end
```

note that doing this:
```arm
Route102_EventScript_RouteSignOldale:: @ 81EC0EA
    settotemboost 0, -2, -2, -2, -2, -2, -2, -2
    msgbox Route102_Text_RouteSignOldale, MSGBOX_SIGN
    end
```
and then initiating a trainer battle did not lead to crash

2021-01-01 16:00 UTC, ghoulslash commented
> if `settotemboost` precedes `trainerbattle`, the game jumps to invalid address 101C101C

@ExpoSeed 

This does not happen for me. You may need a `make clean` since I added EWRAM parameters

Proof:
![totem-traienr](https://user-images.githubusercontent.com/41651341/103442035-b8962480-4c0f-11eb-86ca-b351f35d12fd.gif)

```
InsideOfTruck_EventScript_MovingBox::
	givemon SPECIES_AGGRON, 54, 0
	givemon SPECIES_BAGON, 15, 0
	settotemboost 0, -2, -2, -2, -2, -2, -2, -2
	trainerbattle_single TRAINER_RICK, intro, defeat
	end
intro:
	.string "hi$"
defeat:
	.string "bye$"
```

2021-01-10 20:19 UTC, ExpoSeed commented
> This does not happen for me. You may need a `make clean` since I added EWRAM parameters

`make clean` did not affect anything

for what it's worth, i get crashes on this too. the trainer walking up completes, and then it crashes when the script starts
```arm
Route102_EventScript_Rick:: @ 81EC1B3
	settotemboost 0, -2, -2, -2, -2, -2, -2, -2
	end
```

In this situation, the msgbox never executes
```arm
Route102_EventScript_Rick:: @ 81EC1B3
	msgbox Route102_Text_RickPostBattle, MSGBOX_AUTOCLOSE
	settotemboost 0, -2, -2, -2, -2, -2, -2, -2
	end
```

This functions as expected
```arm
Route102_EventScript_RouteSignOldale:: @ 81EC0EA
	settotemboost 0, -2, -2, -2, -2, -2, -2, -2
	trainerbattle_single TRAINER_RICK, Route102_Text_RickIntro, Route102_Text_RickDefeated
	msgbox Route102_Text_RouteSignOldale, MSGBOX_SIGN
	end
```	
So now I think the bug has something to do with object events that use trainer sight, but i'm perplexed as to why you're not experiencing this issue

2021-01-10 20:28 UTC, ExpoSeed approved these changes
so apparently i'm just dumb

trainer_see requires `trainerbattle` to be the first script command, anything else crashes. it's a limitation of both gamefreak's scripting engine and their mental capacity

2021-01-11 02:43 UTC, ultima-soul approved these changes

2021-01-11 02:43 UTC, merged