toggleable manual ability popup destruction
rh-hideout/pokeemerald-expansion pull request #1244
Opened 2020-11-19 22:23 UTC by ghoulslash

## Description
Option to keep ability popup around and manually remove

To keep around, add this in a battle script before `call BattleScript_AbilityPopUp`:
- `setbyte sFIXED_ABILITY_POPUP, TRUE`

Then, when you want to remove it, call `destroyabilitypopup`

![fixed-popup](https://user-images.githubusercontent.com/41651341/99731133-b1112680-2a7a-11eb-9b38-b0f3fb7efe59.gif)

2020-11-20 12:08 UTC, LOuroboros commented on src/battle_interface.c
> +	gSprites[gBattleStruct->abilityPopUpSpriteIds[battlerId][1]].tFrames = 0;
Should use empty spaces in these lines instead of tabs :eyes:

2020-11-20 12:09 UTC, LOuroboros commented on src/battle_interface.c
> +	gBattleStruct->abilityPopUpSpriteIds[gBattleAnimAttacker][1] = spriteId2;
Should use empty spaces in these lines instead of tabs :eyes:

2020-11-20 15:28 UTC, ghoulslash commented
fixed formatting. ready for re review

2020-12-04 17:43 UTC, ultima-soul requested changes
Functions well.

2020-12-07 23:44 UTC, ultima-soul approved these changes

2020-12-12 23:36 UTC, AsparagusEduardo approved these changes

2020-12-12 23:36 UTC, merged