A few evolution updates
rh-hideout/pokeemerald-expansion pull request #1249
Opened 2020-11-23 13:47 UTC by LOuroboros

## Description
- Changed the Eevee->Leafeon evo method from EVO_MAP to EVO_ITEM, which is more accurate in comparison as of Gen. 8 since we still don't have the actual evo method implemented.
- Changed the Eevee->Glaceon evo method for the same reason.
- Added Charjabug's Thunder Stone based evolution as a second option.

I didn't remove the EVO_MAP based evo from Charjabug because it's an accurate way of representing magnetic field reliant evolutions.

## **Discord contact info**
Lunos#4026

2020-11-23 14:04 UTC, LOuroboros commented
Like Charjabug, Magneton can also evolve with a Thunder Stone now, so I threw that one in too.

2020-11-25 02:39 UTC, AsparagusEduardo commented
I don't get this change. Mossy Rock and Icy Rock evolutions are also map-based (you can evolve anywhere in the map the rock is in.
You could add the stone evolutions for Leafeon and Glaceon, but I don't see why replace them.

2020-11-25 02:43 UTC, ExpoSeed commented on src/data/pokemon/evolution.h
> -                                       {EVO_MAP, MAPSEC_SHOAL_CAVE, SPECIES_GLACEON},
no need to remove, they can coexist like they do for charjabug and magneton

2020-11-25 02:43 UTC, LOuroboros commented
> You could add the stone evolutions for Leafeon and Glaceon, but I don't see why replace them.

Mostly because the current max. amount of evos is set to 8. If that can be safely changed though, I can throw that in here.

2020-11-25 02:44 UTC, ExpoSeed commented on src/data/pokemon/evolution.h
> -                                       {EVO_MAP, MAPSEC_SHOAL_CAVE, SPECIES_GLACEON},
oops didn't consider max evos

2020-11-25 02:52 UTC, LOuroboros commented
Ready for re-review :eyes:

2020-11-25 04:16 UTC, LOuroboros commented
Ready for re-re-review 👀

2020-11-25 04:25 UTC, ExpoSeed approved these changes

2020-11-25 12:18 UTC, AsparagusEduardo requested changes

2020-11-25 12:18 UTC, AsparagusEduardo commented on src/data/pokemon/evolution.h
> +    [SPECIES_CRABRAWLER]            = {{EVO_MAPSEC, 67, SPECIES_CRABOMINABLE}},
Crabrawler's evo needs to be updated to Shoal Cave.

2020-11-28 18:00 UTC, AsparagusEduardo approved these changes

2020-11-29 02:26 UTC, ExpoSeed approved these changes

2020-11-29 02:26 UTC, merged