add z crystal and z ring
rh-hideout/pokeemerald-expansion pull request #1256
Opened 2020-11-29 15:01 UTC by ghoulslash

## Description
Add z-ring and z-crystals to prep fro future z-move PR to battle_engine

2020-11-29 15:10 UTC, LOuroboros commented on src/data/text/item_descriptions.h
> +    "Upgrade the Tapu's\n"
I think this should be written as `Tapus'`.

2020-11-29 15:10 UTC, LOuroboros commented on src/data/graphics/items.h
> +//// Z Crystals
`//`

2020-11-29 19:12 UTC, AsparagusEduardo requested changes

2020-11-29 19:12 UTC, AsparagusEduardo commented on src/data/text/item_descriptions.h
> +    "into a Z-Move.");
This will go outside the bag window. Suggested:
```
    "Upgrade Alolan\n"
    "Raichu's Thunder-\n"
    "bolt into a Z-Move.");
```

2020-11-29 19:12 UTC, AsparagusEduardo commented on src/data/text/item_descriptions.h
> +    "into a Z-Move.");
Out of border. Suggestion:
```
    "Upgrade Decidu-\n"
    "eye's Spirit Sha-\n"
    "ckle into a Z-Move.");
```

2020-11-29 19:12 UTC, AsparagusEduardo commented on src/data/text/item_descriptions.h
> +    "into a Z-Move.");
Out of border. Suggestion:
```
"Upgrade Incine-\n"
"roar's Darkest La-\n"
"riat into a Z-Move.");
```

2020-11-29 19:12 UTC, AsparagusEduardo commented on src/data/text/item_descriptions.h
> +    "into a Z-Move.");
Out of border. Suggestion:
```
    "Upgrade Marsha\n"
    "dow's Spectral Thi-\n"
    "ef into a Z-Move.");
```

2020-12-04 22:37 UTC, ultima-soul requested changes
You also have seem to have forgotten to add data for Ultranecrozium beyond its icon and palette.

2020-12-04 22:37 UTC, ultima-soul commented on src/data/items.h
> +        .holdEffectParam = 0,
```suggestion
```

2020-12-04 22:37 UTC, ultima-soul commented on src/data/items.h
> +        .battleUseFunc = NULL,
```suggestion
```

2020-12-04 22:37 UTC, ultima-soul commented on src/data/items.h
> +        .holdEffectParam = 0,
```suggestion
```
Do this for other Z-Crystals too.

2020-12-04 22:37 UTC, ultima-soul commented on src/data/items.h
> +        .importance = 0,
```suggestion
```
Do this for other Z-Crystals too.

2020-12-04 22:37 UTC, ultima-soul commented on src/data/items.h
> +        .battleUseFunc = NULL,
```suggestion
```
Do this for other Z-Crystals too.

2020-12-19 06:58 UTC, ultima-soul requested changes
I wonder if we should change the description of Ultranecrozmium Z to match the bag description where it instead says
> It's a crystal that turns Necrozma fused with Solgaleo or Lunala into a new form.

2020-12-19 06:58 UTC, ultima-soul commented on src/data/text/item_descriptions.h
> +    "that enables"
```suggestion
    "that enables\n"
```

2020-12-20 22:53 UTC, ultima-soul requested changes

2020-12-20 22:53 UTC, ultima-soul commented on src/data/text/item_descriptions.h
> +    "turn fused Necrozma\n"
```suggestion
    "A crystal to turn\n"
    "fused Necrozma\n"
```
To make it fit.

2020-12-20 23:36 UTC, ghoulslash commented on src/data/text/item_descriptions.h
> +    "turn fused Necrozma\n"
done. ready for re review

2020-12-20 23:45 UTC, ultima-soul approved these changes

2021-01-15 17:59 UTC, ExpoSeed approved these changes

2021-01-15 18:50 UTC, merged