Z Moves
rh-hideout/pokeemerald-expansion pull request #1258
Opened 2020-12-01 21:41 UTC by ghoulslash

## Description
Adds z move engine including names, animations, effects, etc.

Also Handles:
- Trainer AI
![zmove](https://user-images.githubusercontent.com/41651341/100800022-35509b80-33e3-11eb-9c14-7911d5c915ce.gif)

- Multi Battles
![zmove_multi](https://user-images.githubusercontent.com/41651341/100800027-371a5f00-33e3-11eb-82d3-be85de49dfd4.gif)

2020-12-01 22:16 UTC, ExpoSeed commented on src/data/text/move_names.h
> +static const u8 sText_Lets_Snuggle_Forever[] = _("Lets Snuggle Forever");
`'`

2020-12-01 22:17 UTC, ExpoSeed commented on src/data/text/move_names.h
> +static const u8 sText_Lets_Snuggle_Forever[] = _("Lets Snuggle Forever");
```suggestion
static const u8 sText_Lets_Snuggle_Forever[] = _("Let's Snuggle Forever");
```

2020-12-01 22:23 UTC, AsparagusEduardo commented
We need a new icon for the trigger, the current one I made as a joke/placeholder xD

2020-12-19 19:12 UTC, LOuroboros commented on src/data/battle_moves.h
> +        .flags = 0,
This Z-Mve move is affected by Soundproof, so it should have the `FLAG_SOUND` set.

2020-12-22 03:32 UTC, Deidara9216 commented
Hello, could you modify the z-moves so that they are binary entered, it is for an old rom in which I have spent a lot of time.

2020-12-22 03:35 UTC, ExpoSeed commented
Could you clarify "binary entered"?

This particular PR is mostly additive and does not remove much, so it should not cause major conflicts if you're pulling into an old repo. If you are, you'll have problems elsewhere, not with z moves.

2020-12-23 22:58 UTC, Deidara9216 commented
I mean the ASM method could you please adapt it, it is that I don't want to start over from scratch.

2020-12-23 23:05 UTC, LOuroboros commented
> 
> 
> I mean the ASM method could you please adapt it, it is that I don't want to start over from scratch.

This was not written in ASM, this was quite clearly written in C, the same programming language in which the GBA Games and the decomps are written in.

You seem to be asking for someone in here to write an implementation of Z-Moves in ASM and inject it into your ROM, is that correct?

That is more than likely not going to happen, but in any case, this is simply not the right place to ask for something like that.

2021-01-01 00:59 UTC, ExpoSeed commented
would you mind syncing this again? there are conflicts

2021-01-01 15:34 UTC, ghoulslash commented
> 
> 
> would you mind syncing this again? there are conflicts

done

2021-02-02 17:57 UTC, ExpoSeed requested changes
logic of the code seems to make sense, just some minor style nitpicks that can be taken care of alongside solving the conflicts

2021-02-02 17:57 UTC, ExpoSeed commented on src/battle_anim_new.c
> +	DestroyAnimVisualTask(taskId);
this entire file mixes tabs and spaces, please change them all to spaces

2021-02-02 17:57 UTC, ExpoSeed commented on src/battle_anim_new.c
> +		gBattleAnimArgs[0] = 0;*/
is there a reason why this is todo? i'm pretty sure PE has midnight lycanroc so there shouldn't be an issue with this check

2021-02-02 17:57 UTC, ExpoSeed commented on src/battle_anim_new.c
> +////sprite callbacks
lol
```suggestion
//sprite callbacks
```

2021-02-02 17:57 UTC, ExpoSeed commented on src/battle_anim_new.c
> +    //.hword 0x100,0x100,0x0,0x0, 0x0,0x0,0x88f6,0x0, 0x7fff,0x0,0x0,0x0
are these comments necessary? if not, remove all instances of `//.hword` comments

2021-02-02 17:57 UTC, ExpoSeed commented on src/battle_z_move.c
> +        //if (zmove == MOVE_Z_STATUS)
```suggestion
```

2021-02-02 17:58 UTC, ExpoSeed commented
a good chunk of them are probably leftover comments from cfru which don't apply to emerald

2021-03-01 22:13 UTC, ExpoSeed requested changes
fix conflicts as well (even though i only got one conflict so ¯\_(ツ)_/¯)

apologies for delaying on reviewing this, i had winter storm and general demotivation

i'm reviewing the thing in game as well at the moment

2021-03-01 22:13 UTC, ExpoSeed commented on src/battle_z_move.c
> +        #endif
```suggestion
        #ifdef POKEMON_EXPANSION
        if (gBattleMons[battlerAtk].ability == ABILITY_DISGUISE && gBattleMons[battlerDef].species == SPECIES_MIMIKYU)
            return 0; // Don't waste a Z-Move busting Mimikyu's disguise
        if (gBattleMons[battlerAtk].ability == ABILITY_ICE_FACE && gBattleMons[battlerDef].species == SPECIES_EISCUE && IS_MOVE_PHYSICAL(chosenMove))
            return 0; // Don't waste a Z-Move busting Eiscue's Ice Face
        #endif
```

2021-03-12 23:43 UTC, AsparagusEduardo commented
Doing some testing, Z-move animations are currently shifted +1 (Breakneck Blitz plays All-Out Pummeling's animation and so forth).

2021-03-13 00:28 UTC, ExpoSeed requested changes

2021-03-13 00:28 UTC, ExpoSeed commented on src/battle_z_move.c
> +    {SPECIES_PIKACHU_PARTNER_CAP,   ITEM_PIKASHUNIUM_Z,        MOVE_THUNDERBOLT,         MOVE_10000000_VOLT_THUNDERBOLT},
world cap pikachu should be able to use 10m volt tbolt

2021-03-13 00:28 UTC, ExpoSeed commented on src/battle_z_move.c
> +    {SPECIES_PIKACHU,               ITEM_PIKANIUM_Z,           MOVE_VOLT_TACKLE,         MOVE_CATASTROPIKA},
i think cosplay pikachus should be able to use catastropika

2021-03-13 14:43 UTC, amiosi requested changes

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .flags = FLAG_MAKES_CONTACT | FLAG_PROTECT_AFFECTED | FLAG_MIRROR_MOVE_AFFECTED,
should also be boosted by iron fist

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .power = 20,
power = 0, pp = 20

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .type = TYPE_MYSTERY,
dark type

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> -        .split = SPLIT_SPECIAL,
mistaken removal

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .priority = 0,
priority = -6

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .accuracy = 100,
accuracy = 0

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> -        .split = SPLIT_STATUS,
mistaken removals

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .priority = 3,
priority = 4

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .priority = 3,
priority = 4

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .priority = 3,
priority = 4

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .split = SPLIT_SPECIAL,
SPLIT_PHYSICAL

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .accuracy = 100,
accuracy = 0

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .flags = FLAG_DANCE,
.flags = 0,

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .priority = 3,
priority = 2

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> -        .split = SPLIT_STATUS,
mistaken removal

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .accuracy = 100,
accuracy = 0

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> -        .split = SPLIT_STATUS,
mistaken removal

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .accuracy = 100,
accuracy = 0

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .accuracy = 100,
accuracy = 0

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .flags = FLAG_SNATCH_AFFECTED,
should also have sound flag

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .effect = EFFECT_HIT,
regression?

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> -        .argument = HOLD_EFFECT_PLATE,
regression here too

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .effect = EFFECT_HIT,
effect_autotomize

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .flags = FLAG_PROTECT_AFFECTED,
should also have ballistic flag

2021-03-13 14:43 UTC, amiosi commented on src/data/battle_moves.h
> +        .target = MOVE_TARGET_FOES_AND_ALLY,
target selected

2021-05-03 00:30 UTC, ProjectRevoTPP commented
https://github.com/rh-hideout/pokeemerald-expansion/blob/71b85031e0dee8c91d039fd7075c169070b594ba/src/battle_util.c#L8303

This is a NULL deference issue. Make sure you check if the PTR is there, otherwise it will cause the wrong status icons to be displayed on the summary screen.

2021-06-08 21:18 UTC, ExpoSeed requested changes
in addition, pls merge with be and see the previous review comments i made about pikachu's z moves

2021-06-08 21:18 UTC, ExpoSeed commented on src/battle_anim_new.c
> +    .paletteTag ANIM_TAG_ROCKS,
```suggestion
    .paletteTag = ANIM_TAG_ROCKS,
```

2021-06-08 21:18 UTC, ExpoSeed commented on src/battle_anim_new.c
> +    .paletteTag ANIM_TAG_ASSURANCE_HAND,
```suggestion
    .paletteTag = ANIM_TAG_ASSURANCE_HAND,
```

2021-06-08 21:18 UTC, ExpoSeed commented on src/battle_anim_new.c
> +    .paletteTag ANIM_TAG_RAZOR_LEAF,
```suggestion
    .paletteTag = ANIM_TAG_RAZOR_LEAF,
```

2021-06-10 16:57 UTC, ExpoSeed commented
superseded by #1543

2021-06-10 16:57 UTC, closed without merging