LGPE & Isle of Armor move data.
rh-hideout/pokeemerald-expansion pull request #13
Opened 2020-10-15 00:51 UTC by AsparagusEduardo

## Description
Added missing Gen 7 & 8 move data.

## **Discord contact info**
AsparagusEduardo#6051

2020-10-15 15:18 UTC, ExpoSeed commented
Holding off on merging this until we figure out our project boards

2020-10-19 10:01 UTC, LOuroboros commented on data/battle_anim_scripts.s
> +    .4byte Move_VEEVEE_VOLLEY
Small nitpick, but you're using the wrong indentation style for these new moves. Should be tabs, not spaces.

2020-10-19 10:02 UTC, LOuroboros commented on data/battle_anim_scripts.s
> +    .4byte Move_SURGING_STRIKES
Just like above, the wrong indentation style is being used here. Should be tabs, not spaces.

2020-10-19 14:29 UTC, Toby313 commented on src/data/battle_moves.h
> +        .type = TYPE_FLYING,
Pika Papow should be Electric type and is spelled incorrectly.

2020-10-19 15:00 UTC, AsparagusEduardo commented
Fixes applied.

2020-10-20 18:00 UTC, ExpoSeed submitted a review, later dismissed
Issues will need to be made for the effects marked `TODO`

2020-10-23 15:55 UTC, MandL27 reviewed
Overall looks good. Part of me wants to PR my battle menu rework so we could fit longer move names, but having such a UI-breaking change in a rombase sounds...not wise.

2020-10-23 15:55 UTC, MandL27 commented on src/data/text/move_descriptions.h
> +	"which one will damage more.");
Inconsistent indentation (also on a few other moves)

2020-10-23 15:55 UTC, MandL27 commented on src/data/text/move_descriptions.h
> +	"The user's highest offensive\n"
Feel like either this or the next line is missing "stat"; maybe "The user's highest stat determines its category" if space is a concern

2020-10-24 05:12 UTC, ExpoSeed commented on src/data/text/move_descriptions.h
> +    "The Water style allows to\n"
"allows to do 3 critical hits" is awkward phrasing imo. I'd probably do "strikes with 3 critical hits" or "lands with 3 critical hits"

2020-10-24 05:13 UTC, ExpoSeed requested changes
i forgot to hit request changes

2020-10-26 01:29 UTC, LOuroboros submitted a review, later dismissed
Lgtm.

2020-11-01 03:47 UTC, ExpoSeed approved these changes

2020-11-12 00:58 UTC, ultima-soul requested changes
There are some duplicates of issues mentioned above for newline and empty line stuff so make sure to cover those. 

Feel free to give opinions on the move descriptions I suggested. They were done to be a bit more closer to official descriptions alongside fixing some errors.

2020-11-12 00:58 UTC, ultima-soul commented on src/data/text/move_names.h
> +    [MOVE_RISING_VOLTAGE] = _("Rise Voltage"),
Maybe `Rising Volts`?

2020-11-12 00:58 UTC, ultima-soul commented on src/data/battle_moves.h
> +    [MOVE_FLOATY_FALL] =
A check should be added in `IsGravityPreventingMove` since it is affected by Gravity.

2020-11-12 01:08 UTC, ExpoSeed commented on src/data/battle_moves.h
> +        .effect = EFFECT_PLACEHOLDER,   //TODO
bulba says triple axel increases by 20 each time as opposed to triple kick's 10

2020-11-13 17:53 UTC, AsparagusEduardo commented
Review changes ready

2020-11-13 23:08 UTC, ghoulslash submitted a review, later dismissed

2020-11-13 23:31 UTC, ultima-soul requested changes
Unnecessary newlines and non-empty ones seemed to still be present in battle_anim_scripts.s

2020-11-13 23:31 UTC, ultima-soul commented on src/data/battle_moves.h
> +            .flags = FLAG_MAKES_CONTACT | FLAG_PROTECT_AFFECTED,
```suggestion
            .flags = FLAG_MAKES_CONTACT | FLAG_PROTECT_AFFECTED | FLAG_MIRROR_MOVE_AFFECTED | FLAG_KINGSROCK_AFFECTED,
        #else
            .power = 50,
            .pp = 15,
            .flags = FLAG_MAKES_CONTACT | FLAG_PROTECT_AFFECTED | FLAG_KINGSROCK_AFFECTED,
```

2020-11-13 23:31 UTC, ultima-soul commented on src/data/battle_moves.h
> +            .flags = FLAG_PROTECT_AFFECTED,
```suggestion
            .flags = FLAG_PROTECT_AFFECTED | FLAG_MIRROR_MOVE_AFFECTED | FLAG_KINGSROCK_AFFECTED,
        #else
            .flags = FLAG_PROTECT_AFFECTED | FLAG_KINGSROCK_AFFECTED,
```

2020-11-13 23:31 UTC, ultima-soul commented on src/data/battle_moves.h
> +            .flags = FLAG_PROTECT_AFFECTED | FLAG_MAGICCOAT_AFFECTED,
```suggestion
            .flags = FLAG_PROTECT_AFFECTED | FLAG_MAGICCOAT_AFFECTED | FLAG_MIRROR_MOVE_AFFECTED | FLAG_KINGSROCK_AFFECTED,
        #else
            .power = 90,
            .accuracy = 100,
            .pp = 15,
            .flags = FLAG_PROTECT_AFFECTED | FLAG_MAGICCOAT_AFFECTED | FLAG_KINGSROCK_AFFECTED,
```

2020-11-14 12:03 UTC, AsparagusEduardo commented
Re-re-ready for re-re-review

2020-11-15 06:47 UTC, ultima-soul approved these changes

2020-11-15 15:29 UTC, ghoulslash approved these changes

2020-11-15 15:29 UTC, merged