Add Form Species ID Tables
rh-hideout/pokeemerald-expansion pull request #1315
Opened 2020-12-26 00:51 UTC by ultima-soul

## Description

Adds tables of Species IDs for forms of a mon. Helpful for checking the relationship between forms. This also adds entries for all new species and forms added in the Pokémon Expansion.

A companion PR to #1316 and #1317.

## **Discord contact info**

UltimaSoul#4017

2020-12-28 02:59 UTC, ghoulslash approved these changes

2021-01-10 20:35 UTC, ExpoSeed requested changes

2021-01-10 20:35 UTC, ExpoSeed commented on src/pokemon.c
> +}
declare these functions in `pokemon.h` i think so it can be used outside of `pokemon.c` 

this applies to all the form table prs

2021-01-20 20:16 UTC, ultima-soul commented
Done as requested and also added a macro for getting base species ID.

2021-01-20 20:16 UTC, ExpoSeed approved these changes

2021-01-20 20:54 UTC, ghoulslash approved these changes

2021-01-20 20:54 UTC, merged