Dex colors, mawile footprint, hoopa friendship, config fix
rh-hideout/pokeemerald-expansion pull request #1322
Opened 2020-12-31 18:25 UTC by amiosi

In Pokemon HOME, some forms got unique colors assigned to them (for the pokedex search function), when before they shared a color across all forms. Affected mons are Burmy, Deerling, and Vivillon

Mawile recieved a new footprint in Generation 4. As we have updated all of Gen 3's sprites to DS-style sprites, I thought it was only fitting to update the footprint as well.

In Gen 8, all Pokemon with 70 Friendship were lowered to 50. In addition, Hoopa Unbound was lowered from 100 to 50 (but not base Hoopa). As we have not lowered the friendship across the board, and the Gen 8 Pokemon we have added are set to 70, I have set Hoopa Unbound to 70 to keep with that trend.

As a final note, the P_UPDATED_ABILITIES config is used in this file for Pokemon whose ability changed after gen 5. However, the Chandelure family used P_UPDATED_ABILITY, which does not correspond to any config. I have rectified this.

## **Discord contact info**
amiosi#1959

2021-01-15 18:33 UTC, ExpoSeed approved these changes

2021-01-16 23:58 UTC, Pyredrid approved these changes

2021-01-20 00:05 UTC, ExpoSeed commented
ultima wants to nitpick this one more

2021-01-22 00:26 UTC, ultima-soul requested changes
I think Hoopa Unbound is the only one that changed from 100 to 50 and every other friendship value we've kept is basically from Gen 7 and that includes applying the standard 70 to Gen 8 mons that had the standard 50, so maybe it'd be better to keep it as 100.

2021-01-22 01:14 UTC, ultima-soul approved these changes

2021-01-22 01:16 UTC, ExpoSeed approved these changes

2021-01-22 01:16 UTC, merged