Sync battle engine
rh-hideout/pokeemerald-expansion pull request #1325
Opened 2021-01-01 01:37 UTC by ExpoSeed

Conflicts: 
- `data/battle_ai_scripts.s`
- `include/constants/pokemon.h`
- `src/battle_ai_script_commands.c`
- `src/battle_gfx_sfx_util.c`
- `src/battle_script_commands.c`
- `src/battle_util.c`
- `src/data/battle_moves.h`
- `src/pokemon.c`

Of note: `FLAG_MAGICCOAT_AFFECTED` and `FLAG_KINGSROCK_AFFECTED` have been renamed to `FLAG_MAGIC_COAT_AFFECTED` and ``FLAG_KINGS_ROCK_AFFECTED`.

2021-01-02 04:36 UTC, ultima-soul requested changes

2021-01-03 23:14 UTC, ExpoSeed commented
Ready for rereview.

2021-01-03 23:26 UTC, ultima-soul approved these changes

2021-01-07 19:13 UTC, ghoulslash approved these changes

2021-01-07 19:13 UTC, merged