Made Alolan Marowak be affected by Thick Club
rh-hideout/pokeemerald-expansion pull request #1330
Opened 2021-01-03 13:01 UTC by LOuroboros

## Description
The Thick Club is supposed to affect Alolan Marowak, but it wasn't in the BE so I quickly address that with this PR.

## **Discord contact info**
Lunos#4026

2021-01-03 19:11 UTC, ultima-soul commented
I wonder if we should wait to incorporate #1316 so you'd utilize something like it for checking Marowak species. 

Might be more flexible in general to do all species checks like this so that if people say add a regional form or any kind of form for these mons, it would automatically check for them instead of having to manually add them or change it to using this kind of check for Cubone on their own.

2021-01-04 01:03 UTC, LOuroboros commented
> 
> 
> I wonder if we should wait to incorporate #1316 so you'd utilize something like it for checking Marowak species.
> 
> Might be more flexible in general to do all species checks like this so that if people say add a regional form or any kind of form for these mons, it would automatically check for them instead of having to manually add them or change it to using this kind of check for Cubone on their own.

Uh, sure, that sounds good to me. I actually forgot that PR was a thing honestly.

One thing though, it seems to be missing the alolan forms including Marowak's. Unless maybe you plan to incorporate that into the PE too? :eyes:

2021-01-15 18:38 UTC, ExpoSeed commented
Yes the alolan form should be listed in #1315, so then this check changes to "if the base species is marowak"

2021-01-20 21:30 UTC, LOuroboros commented
Ready for review :eyes:

2021-01-20 22:30 UTC, ultima-soul requested changes

2021-01-20 22:30 UTC, ultima-soul commented on src/battle_util.c
> +         || GET_BASE_SPECIES_ID(battlerAtk) == SPECIES_MAROWAK)
```suggestion
        if ((GET_BASE_SPECIES_ID(gBattleMons[battlerAtk].species) == SPECIES_CUBONE
         || GET_BASE_SPECIES_ID(gBattleMons[battlerAtk].species) == SPECIES_MAROWAK)
```

2021-01-20 22:31 UTC, LOuroboros commented
Ready for re-review 👀

2021-01-20 22:31 UTC, ultima-soul approved these changes

2021-01-21 00:31 UTC, ghoulslash approved these changes

2021-01-21 00:32 UTC, merged