Add Ripen
rh-hideout/pokeemerald-expansion pull request #1338
Opened 2021-01-06 05:26 UTC by ghoulslash

## Description
Add Ripen ability. Handled:
- Health restoring berries (including flavor-preference ones such as Mago Berry)
- Stat boosting berries (including Starf - shown in Gif)
- Damage resist berries
- Added immediate consumption for stat boosting and flavor-hp-restoring berries to ITEMEFFECTS_MOVE_END

Not handled:
- Micle, Jaboca, Rowap, and Custap(?) berries, as they are not yet in the BE
- Flinging a berry (fling not yet added)

![ripen_starf](https://user-images.githubusercontent.com/41651341/103732476-a405b380-4fa4-11eb-98f9-7fbb0a8d8410.gif)

2021-03-03 02:29 UTC, ultima-soul requested changes
- Magic Guard should prevent activation of Jaboca and Rowap Berry
- Change to item data for Sitrus Berry should happen in Item Expansion

Additionally something to be done by somebody:
- Hold effects for berries should be added to item data in Item Expansion

2021-03-03 02:29 UTC, ultima-soul commented on src/battle_util.c
> +
```suggestion

```

2021-03-03 02:29 UTC, ultima-soul commented on src/battle_util.c
> +      && GetBattleMoveSplit(gCurrentMove) == split)
```suggestion
     && TARGET_TURN_DAMAGED
     && gBattleMons[battlerId].statStages[statId] < MAX_STAT_STAGE
     && !DoesSubstituteBlockMove(gBattlerAttacker, battlerId, gCurrentMove)
     && GetBattleMoveSplit(gCurrentMove) == split)
```

2021-03-03 02:29 UTC, ultima-soul commented on src/battle_util.c
> +                  && IS_MOVE_PHYSICAL(gCurrentMove))
```suggestion
                 && TARGET_TURN_DAMAGED
                 && !DoesSubstituteBlockMove(gBattlerAttacker, battlerId, gCurrentMove)
                 && IS_MOVE_PHYSICAL(gCurrentMove))
```

2021-03-03 02:29 UTC, ultima-soul commented on src/battle_util.c
> +                  && IS_MOVE_SPECIAL(gCurrentMove))
```suggestion
                 && TARGET_TURN_DAMAGED
                 && !DoesSubstituteBlockMove(gBattlerAttacker, battlerId, gCurrentMove)
                 && IS_MOVE_SPECIAL(gCurrentMove))
```

2021-03-03 16:26 UTC, ghoulslash commented
>     * Magic Guard should prevent activation of Jaboca and Rowap Berry
Done
>     * Change to item data for Sitrus Berry should happen in Item Expansion
Removed that part. #1344 handles sitrus berry in IE too
> 
> Additionally something to be done by somebody:
> 
>     * Hold effects for berries should be added to item data in Item Expansion
Handled in #1415

2021-03-03 17:41 UTC, ultima-soul requested changes

2021-03-03 17:41 UTC, ultima-soul commented on src/battle_util.c
>      bool32 isBerry = (ItemId_GetPocket(itemId) == POCKET_BERRIES);
```suggestion
    bool32 isBerry = (ItemId_GetPocket(itemId) == POCKET_BERRIES);

```

2021-03-03 17:41 UTC, ultima-soul commented on src/battle_util.c
> +                  && GetBattlerAbility(gBattlerAttacker) != ABILITY_MAGIC_GUARD)
```suggestion
                 && GetBattlerAbility(gBattlerAttacker) != ABILITY_MAGIC_GUARD)
```

2021-03-03 17:41 UTC, ultima-soul commented on src/battle_util.c
> +                  && GetBattlerAbility(gBattlerAttacker) != ABILITY_MAGIC_GUARD)
```suggestion
                 && GetBattlerAbility(gBattlerAttacker) != ABILITY_MAGIC_GUARD)
```

2021-03-03 17:41 UTC, ultima-soul commented on src/battle_message.c
> +
```suggestion
```

2021-03-03 17:41 UTC, ultima-soul commented on include/battle_scripts.h
> +
Unresolved still.

2021-03-03 17:49 UTC, ghoulslash commented
fixed formatting

2021-03-03 17:59 UTC, ultima-soul approved these changes

2021-03-13 14:16 UTC, AsparagusEduardo approved these changes

2021-03-13 14:16 UTC, merged