Add Several Hold Effects
rh-hideout/pokeemerald-expansion pull request #1339
Opened 2021-01-08 04:28 UTC by ghoulslash

## Description
Adds:
- Throat Spray
![throat_spray](https://user-images.githubusercontent.com/41651341/103974359-e5c26580-512e-11eb-930e-0e1dd6d0ac47.gif)
- Blunder Policy
![blunder_policy](https://user-images.githubusercontent.com/41651341/103974382-ece97380-512e-11eb-9b06-88870bc2709a.gif)
- Room Service
![room_service](https://user-images.githubusercontent.com/41651341/103974393-f377eb00-512e-11eb-84fc-00add43bfde7.gif)
- Terrain Seeds
![seed](https://user-images.githubusercontent.com/41651341/103974403-f70b7200-512e-11eb-9c1a-b1a7572cccc0.gif)
- Heavy Duty Boots (no gif)
- Red Card
![red_card](https://user-images.githubusercontent.com/41651341/103974437-012d7080-512f-11eb-9318-4182269554ab.gif)
- Eject Button (no gif)
- Eject Pack
![eject-pack](https://user-images.githubusercontent.com/41651341/103974456-04c0f780-512f-11eb-8533-4d30bbfdca2d.gif)

2021-03-25 02:11 UTC, ultima-soul requested changes
Notes from testing:
```
Throat Spray:
    - Should raise Sp. Atk of holder, not opponent
    - If target is asleep and Sing fails due to already being asleep, shouldn't activate
    - If target has Soundproof and fails, shouldn't activate
    - If target fainting ends the battle (last mon of the opponent), shouldn't activate
    - Should activate after both stat drops in double battle when something like Growl used

Room Service:
    - When switched in and holding Room Service and Trick Room is in effect, item use animation should play and stat lowering sound should be used (unless has Contrary)

Terrain Seeds:
    - Switching in Contrary mon with Seed that can activate should have stat decrease sound to match stat decrease
    - Contrary mon with +6 Defense/Sp. Def (depending on the Seed) should have Seed activate
    - Contrary mon with -6 Defense/Sp. Def (depending on the Seed) shouldn't have Seed activate

Heavy-Duty Boots:
    - Grounded Poison-types when switched in should still absorb Toxic Spikes

Red Card:
    - If Wild mon holds Red Card, it should activate and make player flee if hit
    - If Wild mon holds Red Card in double wild battle with two enemies active, it should activate and make player switch (if there is a third mon in the party minimum)
        - If single enemy active, instead makes player flee like single battle
    - In double battle, if hitting with attack that hits multiple mons all holding Red Card, only fastest Red Card holder activates its item
    - In double battle, if hitting with attack that hits multiple mons all holding Red Card, if at least one mon isn't hit due to Protect or evading the attack, no Red Card activation takes place when it should activate
    - If attacker that has used Ingrain and is rooted, attacks holder of Red Card, Red Card should get used up, but fails to make attacker switch out (just like how it works with attacker having Suction Cups)
    - If attacker holds Shell Bell, it should not activate if holder of Red Card is attacked and activates its Red Card (Like holding Life Orb)

Eject Button:
    - Being trapped by trapping moves like Fire Spin should not prevent Eject Button from activating
    - In double battle, if hitting with attack that hits multiple mons all holding Red Card, if at least one mon isn't hit due to Protect or evading the attack, no Eject Button activation takes place when it should activate

Eject Pack:
    - If Parting Shot is used against holder of Eject Pack and user is able to switch out, Eject Pack doesn't activate
    - If U-turn or similar is used against holder of Eject Pack that has Weak Armor ability and user is able to switch out, Eject Pack doesn't activate
    - Stockpile stat changes that get lowered by Swallow/Spit Up should activate Eject Pack
```

2021-03-25 02:11 UTC, ultima-soul commented on src/battle_util.c
> +        gLastUsedItem = itemId; // for surge abilities
```suggestion
        gLastUsedItem = itemId; // For surge abilities
```

2021-03-25 02:11 UTC, ultima-soul commented on src/battle_util.c
> +
```suggestion
```

2021-03-25 02:11 UTC, ultima-soul commented on src/battle_util.c
> +                    }
```suggestion
                    {
                        BattleScriptPushCursor();
                        gBattlescriptCurrInstr = BattleScript_EjectPackActivate_Ret;
                    }
                    else
                    {
                        BattleScriptExecute(BattleScript_EjectPackActivate_End2);
                    }
```

2021-03-25 02:11 UTC, ultima-soul commented on src/battle_util.c
> +            if (gBattleMoveDamage != 0  // need to have done damage
```suggestion
            if (gBattleMoveDamage != 0  // Need to have done damage
```

2021-03-25 02:11 UTC, ultima-soul commented on src/battle_util.c
> +            if (gBattleMoveDamage != 0  // need to have done damage
```suggestion
            if (gBattleMoveDamage != 0  // Need to have done damage
```

2021-03-25 02:11 UTC, ultima-soul commented on src/battle_util.c
> +        case HOLD_EFFECT_THROAT_SPRAY:  // doesn't need to be a damaging move
```suggestion
        case HOLD_EFFECT_THROAT_SPRAY:  // Doesn't need to be a damaging move
```

2021-09-03 18:59 UTC, ghoulslash commented
Ready for re-review.

The recent commits also take care of:
- fixes shell bell, throat spray, etc, activation timing relative to multi-hit moves
- handles contrary checks with the function `CompareStat`

Eject Pack + swallow/spit up interaction is not handled because these are not updated to Gen 5 behavior where the stat drop is handled as an animation. This should be a separate PR (probably after this PR is merged to handle eject pack)

2021-09-12 03:22 UTC, ultima-soul requested changes
Some issues that remain:
```
Throat Spray
    - Should activate after hitting at least one target (and other target it can miss against or be protected against)

Room Service
    - When switched in and holding Room Service and Trick Room is in effect and has Contrary, stat increase and its animation should happen

Terrain Seeds
    - Switching in Contrary mon with Seed that can activate, stat decrease and its animation should happen

Red Card
    - If Wild mon holds Red Card in double wild battle with two enemies active:
        - If player has at least a third Pokemon to switch to and attacking player's Pokemon is alive at the time Red Card is activated, but attacker's partner fainted before it in the same turn:
            - Should switch attacking Pokemon to one of your available party Pokemon
            - Then choose Pokemon to replace fainted partner Pokemon at end of turn
        -If no available party Pokemon to switch to (whether attacker's partner faints in the same turn or is alive):
            - Red Card shouldn't activate
    - If Wild mon holds Red Card in double wild battle with one enemy active:
        - If player has at least a third Pokemon to switch to and both of player's Pokemon are alive at the time Red Card is activated:
            - Should switch attacking Pokemon to one of your available party Pokemon
        - If player has at least a third Pokemon to switch to and attacking player's Pokemon is alive at the time Red Card is activated, but attacker's partner fainted before it in the same turn:
            - Should switch attacking Pokemon to one of your available party Pokemon
            - Then choose Pokemon to replace fainted partner Pokemon at end of turn
        -If no available party Pokemon to switch to (whether attacker's partner faints in the same turn or is alive):
            - Red Card shouldn't activate
    - If holder of Red Card (whether a trainer's mon or a wild mon) is hit and attacker's trainer has no mons to switch to, it shouldn't activate

Eject Pack
    - If Parting Shot is used against holder of Eject Pack and user of move is able to switch out, Eject Pack shouldn't activate
    - If U-turn or similar is used against holder of Eject Pack that has Weak Armor ability and user is able to switch out, Eject Pack doesn't activate
    ```
    
For full notes on how Red Card works from official game testing take a look at: https://gist.github.com/ultima-soul/3fa958515961081889ed9af6c3385671

2021-09-12 03:25 UTC, ultima-soul commented on data/battle_scripts_1.s
> +RoomServiceLoop:
Also unresolved this because `TerrainSeedLoop` and `TerrainSeedLoop_NextBattler` are still outstanding for this issue.

2021-09-14 23:24 UTC, ghoulslash commented
ready for re-review

2021-09-16 20:50 UTC, ultima-soul requested changes
All issues are fixed. Just resolve the suggested changes and also the remaining suggested changes from the previous review.

2021-09-16 21:11 UTC, ghoulslash commented
ready for review

2021-09-16 23:41 UTC, ultima-soul approved these changes

2021-09-16 23:41 UTC, merged