Implement Gen4+ Sitrus Berry Effect
rh-hideout/pokeemerald-expansion pull request #1344
Opened 2021-01-12 14:05 UTC by SBird1337

## Description
Implements `HOLD_EFFECT_RESTORE_PCT_HP` and adapts `ITEM_SITRUS_BERRY` s.t. it restores 25% of the user's HP both when held and when used from the bag iff `I_SITRUS_BERRY_HEAL >= GEN_4`

## **Discord contact info**
Karathan#1337

2021-01-25 00:44 UTC, ultima-soul requested changes
Since `HOLD_EFFECT_RESTORE_PCT_HP` is only something that is used in battle, it would be better to implement that case in Battle Engine Upgrade branch.

Therefore you would probably also add a `BATTLE_ENGINE` define check alongside `I_SITRUS_BERRY_HEAL` check in the item data for Sitrus Berry so that it will fall back to the old effect if you don't have the Battle Engine merged.

2021-01-25 00:44 UTC, ultima-soul commented on include/constants/item_config.h
> +#define I_SITRUS_BERRY_HEAL     GEN_7
```suggestion
#define I_SITRUS_BERRY_HEAL     GEN_7   // In Gen4+, Sitrus Berry was changed from healing 30 HP to healing 25% of Max HP.
```

2021-01-25 00:49 UTC, ultima-soul commented
> Since `HOLD_EFFECT_RESTORE_PCT_HP` is only something that is used in battle, it would be better to implement that case in Battle Engine Upgrade branch.
> 
> Therefore you would probably also add a `BATTLE_ENGINE` define check alongside `I_SITRUS_BERRY_HEAL` check in the item data for Sitrus Berry so that it will fall back to the old effect if you don't have the Battle Engine merged.

Oops, apparently it's already implemented in Battle Engine, so you only need to assign it in the item data with both define checks.

2021-05-13 19:59 UTC, LOuroboros commented
Conflicts aside, the change done to the `ItemBattleEffects` func should probably be undone. The IE is not supposed to modify that stuff since it's BE territory.

2021-09-26 21:49 UTC, AsparagusEduardo commented
Superseded by #1338 and #1691 .

2021-09-26 21:49 UTC, closed without merging