Electric and Misty Terrain Effects
rh-hideout/pokeemerald-expansion pull request #1358
Opened 2021-01-16 18:41 UTC by ghoulslash

## Description
Adds electric terrain preventing sleep and misty terrain preventing non-volatile status conditions
![misty_terrain](https://user-images.githubusercontent.com/41651341/104820075-b75c1e80-57ef-11eb-992d-df71f6a14640.gif)

2021-04-16 17:10 UTC, ultima-soul requested changes
Please merge to resolve conflicts.

Also some issues noted:
```
Electric Terrain:
- When Yawn used before Electric Terrain is set and marks a Pokemon as drowsy:
    - If Electric Terrain set the turn after, instead of falling asleep, "X surrounds itself with electrified terrain." is displayed and drowsiness is unset
- When Yawn, Rest, or sleep-inducing move is used while Electric Terrain is set:
    - "X surrounds itself with electrified terrain." is displayed for targeted Pokemon.
        - For Rest, only if HP isn't full it says this, otherwise HP full message appears
        - For Yawn, only if drowsiness isn't set from prior turn, otherwise "But it failed" prints (Yawn used twice against the same Pokemon. One the prior turn and one turn after while drowsiness is still set on the same turn that Electric Terrain is set.)

Misty Terrain:
- Toxic Spikes shouldn't do anything when mon is sent in while Misty Terrain is active
- See Electric Terrain for Sleep-related issues
```

2021-09-13 19:31 UTC, ultima-soul requested changes
Some issues remaining:
```
Electric Terrain:
- When Yawn is used while Electric Terrain is set and drowsiness is set from Yawn being used against target in the previous turn:
    - "But it failed" should display.
- When Rest is used while Electric Terrain is set:
    - "X surrounds itself with electrified terrain!" should display for targeted Pokemon when HP isn't full.
        - Shouldn't say "But it failed" or set the mon to sleep when less than Max HP.

Misty Terrain:
- When Yawn is used while Misty Terrain is set and drowsiness is set from Yawn being used against target in the previous turn:
    - "But it failed" should display.
- When Rest is used while Misty Terrain is set:
    - "X surrounds itself with a protective mist!" should display for targeted Pokemon when HP isn't full.
        - Shouldn't say "But it failed" or set the mon to sleep when less than Max HP.
```

2021-09-13 19:31 UTC, ultima-soul commented on include/battle_util.h
> +
```suggestion
```

2021-09-13 19:31 UTC, ultima-soul commented on src/battle_script_commands.c
> +            if (!CanBeBurned(gEffectBattler))
```suggestion
            if (!CanBeBurned(gEffectBattler))
```

2021-09-13 19:31 UTC, ultima-soul commented on src/battle_util.c
> +                        gBattleCommunication[MULTISTRING_CHOOSER] = 1;
Should add Multi String Constants like other Multi String Arrays.

2021-09-15 21:15 UTC, ghoulslash commented
ready for re-review

2021-09-17 02:09 UTC, ultima-soul approved these changes

2021-09-17 02:09 UTC, merged