Prankster Gen 7
rh-hideout/pokeemerald-expansion pull request #1360
Opened 2021-01-16 23:16 UTC by ghoulslash

## Description
Dark types block priority-boosted status moves used by prankster-mons in gen7. Added a config option

Here's a GIF: poochyena has prankster
![prankster](https://user-images.githubusercontent.com/41651341/104826415-10d74400-5816-11eb-9784-8fdfeaffef59.gif)

2021-03-09 21:47 UTC, AsparagusEduardo requested changes

2021-03-09 21:47 UTC, AsparagusEduardo commented on include/constants/battle_config.h
> +#define B_PRANKSTER                 GEN_7 // In Gen7, Prankster-elevated status moves do not affect Dark type Pokemon
```suggestion
#define B_PRANKSTER_DARK_TYPES      GEN_7 // In Gen7, Prankster-elevated status moves do not affect Dark type Pokémon.
```

2021-03-09 21:47 UTC, AsparagusEduardo commented on src/battle_util.c
> +            #if B_PRANKSTER >= GEN_7
```suggestion
            #if B_PRANKSTER_DARK_TYPES >= GEN_7
```

2021-05-07 01:32 UTC, ultima-soul requested changes
Some issues found while testing:
```
- Perish Song and Rototiller shouldn't bypass foe Dark-type Prankster immunity unlike other multi-target moves that do
- Assist should do animation, say what move is being used, and then fail due to Dark-type Prankster immunity and it should be able to choose either opponent for single target attacks rather than opponent's first slot always.
    - Also if the move chosen is something that targets ally or self, it should work regardless of type. e.g. Harden should work regardless of foes' typings.
- If Dark-type that normally would be immune to Prankster'd move has Magic Bounce ability, it bounces the move back if the move would normally be bounced back by Magic Bounce; right now it says the move failed 
```

2021-05-07 01:32 UTC, ultima-soul commented on src/battle_util.c
> +			break;
```suggestion
            gBattleStruct->atkCancellerTracker++;
            break;
```

2021-05-07 01:32 UTC, ultima-soul commented on include/constants/battle_config.h
> +#define B_PRANKSTER_DARK_TYPES      GEN_7 // In Gen7, Prankster-elevated status moves do not affect Dark type Pokémon.
```suggestion
#define B_PRANKSTER_DARK_TYPES      GEN_7 // In Gen7+, Prankster-elevated status moves do not affect Dark-type Pokémon.
```

2021-09-16 16:02 UTC, ghoulslash commented
ready for re-review. Rototiller is not handled due to the presence of #1657. Preferably, this should be merged and then that PR can handle rototiller + prankster. Otherwise, we will need to wait for #1657

2021-09-18 19:05 UTC, ultima-soul requested changes
A couple of issues:
```
- Dark-type Prankster immunity of ally is bypassed for any boosted moves (e.g. Thunder Wave used on your Dark-type ally is successful)
    - This includes Perish Song

- Assist always fails with "It doesn't affect Foe X..." if slot 1 foe is Dark-type even if move should be successful like when using Curse when it should work normally

- Under the test case of both foes being Dark-type and Assist user's partner has Curse, Pound, and Razor Leaf it should behave like:
    - Curse can be invoked and be successful
    - Pound can be invoked against either foe and will print "It doesn't affect Foe X..."
    - Razor Leaf can be invoked and will print "It doesn't affect Foe X..." and "It doesn't affect Foe Y..."

- Under the test case of slot 1 foe being Dark-type and slot 3 foe being non-Dark-type and Assist user's partner has Curse, Pound, and Razor Leaf it should behave like:
    - Curse can be invoked and be successful
    - Pound can be invoked against Dark-type foe and will print "It doesn't affect Foe X..."
    - Pound can be invoked against non-Dark-type foe and be successful
    - Razor Leaf can be invoked and will print "It doesn't affect Foe X..." for slot 1 foe, do Razor Leaf animation, and then hit non-Dark-type (slot 3 foe).

- Under the test case of slot 3 foe being Dark-type and slot 1 foe being non-Dark-type and Assist user's partner has Curse, Pound, and Razor Leaf it should behave like:
    - Curse can be invoked and be successful
    - Pound can be invoked against Dark-type foe and will print "It doesn't affect Foe X..."
    - Pound can be invoked against non-Dark-type foe and be successful
    - Razor Leaf can be invoked and will print "It doesn't affect Foe X..." for slot 3 foe, do Razor Leaf animation, and then hit non-Dark-type (slot 1 foe).

- Magic Coat shouldn't automatically fail if slot 1 foe is Dark-type

- Dark-type foe that uses status move against user (type doesn't matter) of Prankster'd Magic Coat shouldn't be affected by reflected status move
    - Works like normal with bounced move back message, but then prints "It doesn't affect Foe X..."
    - If Dark-type ally uses status move against Prankster'd Magic Coat user, it bounces back successfully
```

2021-09-22 20:11 UTC, ghoulslash commented
Ready for re-review.

I created a ProtectStruct field, `pranksterElevated`, which is set upon prankster boosting priority to handle assist and other calling-move effects. I also handle magic coat in Cmd_attackcanceler. A general function, `BlocksPrankster`, is added to help duplicate logic.

2021-09-23 18:14 UTC, ultima-soul requested changes
I'm not sure if this one thing can be fixed and whether it's relevant to the PR, but it is a behavioural difference from what I tested in Gen 7:
```
- Under the test case of slot 3 foe being Dark-type and slot 1 foe being non-Dark-type and Assist user's partner has Curse, Pound, and Razor Leaf it should behave like:
    - Razor Leaf can be invoked and will print "It doesn't affect Foe X..." for slot 3 foe, do Razor Leaf animation, and then hit non-Dark-type (slot 1 foe).
 ```
 Other issues are:
 ```
 - Magic Coat should bounce back all status effects for the turn and not just once

- Dark-type foe that uses status move against user (type doesn't matter) of Prankster'd Magic Coat should be affected by reflected status move if `B_PRANKSTER_DARK_TYPES` is set to Gen 6 or below

- If `B_PRANKSTER_DARK_TYPES` is set to Gen 6 or below, when Perish Song is used, it shouldn't say that Dark-type foes are not affected
    - Currently it prints this, but Perish Song is still afflicted; the affliction is correct
```

For the Magic Coat blocking issue when the config is set to Gen 6 or below, see my potential suggestion in `BlocksPrankster`.

2021-09-23 19:18 UTC, ultima-soul requested changes
Good otherwise.

2021-09-23 19:18 UTC, ultima-soul commented on asm/macros/battle_script.inc
> +
```suggestion

```

2021-09-23 19:25 UTC, ultima-soul approved these changes

2021-09-23 19:26 UTC, ultima-soul requested changes
Not sure why GitHub suggestions deleted the line.

2021-09-23 19:26 UTC, ultima-soul commented on asm/macros/battle_script.inc
> +	.macro jumpifpranksterblocked battler:req, ptr:req
```suggestion
	.endm

	.macro jumpifpranksterblocked battler:req, ptr:req
```

2021-09-23 19:27 UTC, ultima-soul approved these changes

2021-09-23 19:27 UTC, merged