Updated the list of untraceable abilities
rh-hideout/pokeemerald-expansion pull request #1369
Opened 2021-01-25 17:57 UTC by LOuroboros

## Description
I forgot to do this one yesterday. The list of abilities that shouldn't be able to be traced by Trace was missing a few Gen. 8 abilities. This PR intends to solve that.

## **Discord contact info**
Lunos#4026

2021-01-25 18:35 UTC, ultima-soul requested changes
You're missing both of the As One abilities.

2021-01-25 18:37 UTC, LOuroboros commented
> 
> 
> You're missing both of the As One abilities.

Not anymore :eyes:

2021-01-25 18:39 UTC, ultima-soul approved these changes

2021-01-27 04:41 UTC, ghoulslash approved these changes

2021-01-27 04:41 UTC, merged