Battle Engine Upstream Sync
rh-hideout/pokeemerald-expansion pull request #1383
Opened 2021-01-30 01:21 UTC by ultima-soul

## Description

Conflicts in:
```
data/battle_ai_scripts.s
data/battle_anim_scripts.s
include/constants/battle_anim.h
include/constants/battle_move_effects.h
src/battle_ai_switch_items.c
src/battle_controller_link_opponent.c
src/battle_controller_link_partner.c
src/battle_controller_opponent.c
src/battle_controller_player.c
src/battle_controller_player_partner.c
src/battle_controller_recorded_opponent.c
src/battle_controller_recorded_player.c
src/battle_controller_safari.c
src/battle_controller_wally.c
src/battle_interface.c
src/battle_main.c
src/battle_script_commands.c
src/battle_util.c
src/pokemon.c
```
## **Discord contact info**

UltimaSoul#4017

2021-01-30 01:52 UTC, PlatinumMaster submitted a review, later dismissed

2021-02-01 19:45 UTC, ExpoSeed requested changes

2021-02-01 19:45 UTC, ExpoSeed commented on data/battle_anim_scripts.s
> +	.4byte General_HangedOn                @ B_ANIM_HANGED_ON
```suggestion
	.4byte General_HangedOn                 @ B_ANIM_HANGED_ON
```

2021-02-01 23:55 UTC, ultima-soul commented
Resolved review suggestions and also did some formatting and sync changes in `battle_script_commands.c` and `battle_main.c`.

2021-02-02 00:20 UTC, ExpoSeed approved these changes

2021-02-02 17:02 UTC, ghoulslash approved these changes

2021-02-02 17:02 UTC, merged