Corrected the order of actions in BattleScript_FirstChargingTurn
rh-hideout/pokeemerald-expansion pull request #1399
Opened 2021-02-08 21:17 UTC by LOuroboros

## Description
Updates the order of actions for 2 turn move effects.
As it was brought up in #1398, in the newer Pokémon games, `attackstring` and the text string printed during their charging turn are supposed to be called before the charging turn's animation is casted.

## **Discord contact info**
Lunos#4026

2021-05-21 23:00 UTC, ultima-soul approved these changes
Please resolve conflicts, otherwise, everything is good to go.

2021-05-21 23:22 UTC, LOuroboros commented
> 
> 
> Please resolve conflicts, otherwise, everything is good to go.

Done :eyes:

2021-05-22 18:58 UTC, ultima-soul requested changes

2021-05-22 18:58 UTC, ultima-soul commented on data/battle_scripts_1.s
> +	pause 0x40
```suggestion
	pause B_WAIT_TIME_LONG
```

2021-05-22 20:50 UTC, ultima-soul approved these changes

2021-05-22 20:50 UTC, merged