restore and add noFlip values
rh-hideout/pokeemerald-expansion pull request #1412
Opened 2021-02-22 21:13 UTC by amiosi

the .noFlip value for all Pokemon was wiped and incorrectly restored at some point in the creation of the pokemon expansion. I have corrected the values using both vanilla emerald and a few other sources, including: pokediamond, hgss/bw2 overworlds, and oras/usum menu sprites.

this is partially incomplete as i am unable to look through the raw hex data for bw2 and oras.

i also took the liberty of adding the flag to spiky-eared pichu as it shared pichu's data in gen 4, its only appearance, while being clearly asymmetrical.

2021-02-23 00:37 UTC, LOuroboros commented
A few TRUE/FALSE comparison pics for the Pokémon affected by this PR would be nice to have.

2021-02-24 21:06 UTC, amiosi commented
![pokeemerald 2021-02-24 16 04 34](https://user-images.githubusercontent.com/44352097/109065828-27e13f80-76ba-11eb-83f3-582a67c24eb9.png)
Before changes

![pokeemerald 2021-02-24 15 57 29](https://user-images.githubusercontent.com/44352097/109065818-257ee580-76ba-11eb-9d3a-3fc9560a8340.png)
After changes

2021-02-25 00:18 UTC, LOuroboros commented
> 
> 
> ![pokeemerald 2021-02-24 16 04 34](https://user-images.githubusercontent.com/44352097/109065828-27e13f80-76ba-11eb-83f3-582a67c24eb9.png)
> .noFlip = FALSE
> 
> ![pokeemerald 2021-02-24 15 57 29](https://user-images.githubusercontent.com/44352097/109065818-257ee580-76ba-11eb-9d3a-3fc9560a8340.png)
> .noFlip = TRUE
> 
> Zangoose and other asymmetrical Pokemon have their defining features flipped without this PR, as seen in the first screenshot.

Unless GitHub is tricking me, Zangoose isn't affected by this PR though.
The point of my suggestion was to provide a Before/After type of comparison, to show off some of the changes in species sprite in game visualization that this PR makes 😆

2021-03-08 23:55 UTC, AsparagusEduardo requested changes
Found a couple of mon that I don't think require noFlip:

Staryu:
![image](https://user-images.githubusercontent.com/2904965/110395860-b310ec80-804d-11eb-956c-f16f6016a2a7.png)

Mandibuzz
![image](https://user-images.githubusercontent.com/2904965/110396842-7b0aa900-804f-11eb-989f-85cb618b9324.png)

Stakataka
![image](https://user-images.githubusercontent.com/2904965/110397246-3b908c80-8050-11eb-8188-3440a764ccc0.png)

2021-03-09 00:24 UTC, surskitty commented
Staryu's garter belt is why it's noflip. 
![https://img.pokemondb.net/artwork/large/staryu.jpg]

2021-05-21 15:44 UTC, merged