Add Berry Hold Effects
rh-hideout/pokeemerald-expansion pull request #1415
Opened 2021-03-03 16:26 UTC by ghoulslash

## Description
Adds hold effects parameters for gen4 berries. Complements #1338

2021-03-13 14:18 UTC, AsparagusEduardo approved these changes

2021-04-16 15:46 UTC, ExpoSeed requested changes

2021-04-16 15:46 UTC, ExpoSeed commented on src/data/items.h
> +        .holdEffect = HOLD_EFFECT_HOLD_EFFECT_KEE_BERRY,
```suggestion
        .holdEffect = HOLD_EFFECT_KEE_BERRY,
```

2021-04-16 15:46 UTC, ExpoSeed commented on src/data/items.h
> +        .holdEffect = HOLD_EFFECT_HOLD_EFFECT_MARANGA_BERRY,
```suggestion
        .holdEffect = HOLD_EFFECT_MARANGA_BERRY,
```

2021-05-23 22:29 UTC, ultima-soul requested changes

2021-05-23 22:29 UTC, ultima-soul commented on src/data/items.h
>          .description = sKeeBerryDesc,
```suggestion
        .description = sKeeBerryDesc,
```

2021-05-23 22:29 UTC, ultima-soul commented on src/data/items.h
>          .description = sJabocaBerryDesc,
```suggestion
        .description = sJabocaBerryDesc,
```

2021-05-23 22:29 UTC, ultima-soul commented on src/data/items.h
>          .description = sRowapBerryDesc,
```suggestion
        .description = sRowapBerryDesc,
```

2021-05-23 22:29 UTC, ultima-soul commented on src/data/items.h
>          .description = sMarangaBerryDesc,
```suggestion
        .description = sMarangaBerryDesc,
```

2021-05-24 18:03 UTC, ultima-soul approved these changes

2021-05-24 18:07 UTC, merged