Implemented Clanging Scales' effect
rh-hideout/pokeemerald-expansion pull request #1486
Opened 2021-05-09 21:23 UTC by LOuroboros

## Description
Addresses #1485 
![Untitled5111](https://user-images.githubusercontent.com/4485172/117587127-c5151700-b0f2-11eb-9076-c773af931eb4.gif)

## **Discord contact info**
Lunos#4026

2021-06-02 17:25 UTC, ultima-soul requested changes

2021-06-02 17:25 UTC, ultima-soul commented on src/data/battle_moves.h
>          .accuracy = 100,
Also change `secondaryEffectChance` to equal 0 since 100% chance is handled by the battle script.

2021-06-02 19:47 UTC, LOuroboros commented
Ready for re-review :eyes:

2021-06-03 05:54 UTC, ultima-soul commented
Please resolve conflicts by merging the latest commits.

2021-06-03 08:14 UTC, LOuroboros commented
> 
> 
> Please resolve conflicts by merging the latest commits.

Done :eyes:

2021-06-03 15:50 UTC, ultima-soul approved these changes

2021-06-03 15:51 UTC, merged