Tweaked Task_ShowAiPoints to comply with the PE
rh-hideout/pokeemerald-expansion pull request #1492
Opened 2021-05-17 21:44 UTC by LOuroboros

## Description
Due to the removal of the Deoxys hack, this function needed some minor adjustments that could have always been handled by using the #ifdef preproc directive.
This PR addresses that, thus giving the user one less thing to think about when merging the feature branches hosted in this repository.

## **Discord contact info**
Lunos#4026

2021-06-02 17:29 UTC, ultima-soul commented
I'm not a fan of this because this is a really easy merge conflict to resolve.

2021-06-02 19:45 UTC, LOuroboros commented
> 
> 
> I'm not a fan of this because this is a really easy merge conflict to resolve.

Huh. I see it as a pointless annoyance that users shouldn't need to go through.

2021-06-03 06:49 UTC, ultima-soul requested changes

2021-06-03 06:49 UTC, ultima-soul commented on src/battle_debug.c
> +    #endif
```suggestion
        #ifndef POKEMON_EXPANSION
        data->aiMonSpriteId = CreateMonPicSprite_HandleDeoxys(gBattleMons[data->aiBattlerId].species,
                                                 gBattleMons[data->aiBattlerId].otId,
                                                 gBattleMons[data->aiBattlerId].personality,
                                                 TRUE,
                                                 39, 130, 15, 0xFFFF);
        #else
        data->aiMonSpriteId = CreateMonPicSprite(gBattleMons[data->aiBattlerId].species,
                                                 gBattleMons[data->aiBattlerId].otId,
                                                 gBattleMons[data->aiBattlerId].personality,
                                                 TRUE,
                                                 39, 130, 15, 0xFFFF);
        #endif
```

2021-06-03 06:49 UTC, ultima-soul commented on src/battle_debug.c
> +    #endif
```suggestion
        #ifndef POKEMON_EXPANSION
        data->aiMonSpriteId = CreateMonPicSprite_HandleDeoxys(gBattleMons[data->aiBattlerId].species,
                                                 gBattleMons[data->aiBattlerId].otId,
                                                 gBattleMons[data->aiBattlerId].personality,
                                                 TRUE,
                                                 39, 130, 15, 0xFFFF);
        #else
        data->aiMonSpriteId = CreateMonPicSprite(gBattleMons[data->aiBattlerId].species,
                                                 gBattleMons[data->aiBattlerId].otId,
                                                 gBattleMons[data->aiBattlerId].personality,
                                                 TRUE,
                                                 39, 130, 15, 0xFFFF);
        #endif
```

2021-06-03 08:18 UTC, LOuroboros commented
I really don't like those changes tbqh with you, @ultima-soul, but done. Ready for re-review :eyes:

2021-06-03 16:01 UTC, ultima-soul approved these changes

2021-06-03 16:01 UTC, merged