Corrected the Wings/Feathers
rh-hideout/pokeemerald-expansion pull request #1493
Opened 2021-05-18 01:06 UTC by LOuroboros

## Description
The Wings, items that raise a stat's EVs by 1 or can be sold for money in the case of the Pretty Wing, were renamed to Feathers in the Gen. 8 games. On top of that, they weren't working because they didn't have the right data set.
This PR corrects all that.

## **Discord contact info**
Lunos#4026

2021-06-02 18:04 UTC, ultima-soul requested changes

2021-06-02 18:04 UTC, ultima-soul commented on src/data/pokemon/item_effects.h
> +#define FEATHER_FRIENDSHIP_CHANGE(i)                \
```suggestion
#define FEATHER_FRIENDSHIP_CHANGE(i)             \
```

2021-06-02 19:48 UTC, LOuroboros commented
Ready for re-review :eyes:

2021-06-03 05:56 UTC, ultima-soul approved these changes

2021-06-03 05:56 UTC, merged