More Battle Config
rh-hideout/pokeemerald-expansion pull request #150
Opened 2020-10-18 02:12 UTC by AsparagusEduardo

## Description
- Tweaking `battle_config` to accomodate `pokemon_config` and `item_config`
- Configurable double wild battle chance, surfing double battles and flag for forcing them.
- Organized interface settings into their own category.
- Adapting move changes to `battle_config`

## **Discord contact info**
AsparagusEduardo#6051

2020-10-18 02:23 UTC, ExpoSeed requested changes

2020-10-18 02:23 UTC, ExpoSeed commented on src/data/battle_moves.h
>          .accuracy = 90,
you forgot to remove `.accuracy` here

2020-10-18 20:55 UTC, AsparagusEduardo commented
Alright, all changes in this page (except for Contests) in this page have been applied:
https://bulbapedia.bulbagarden.net/wiki/List_of_modified_moves

2020-10-18 22:34 UTC, ExpoSeed approved these changes

2020-10-23 15:55 UTC, ghoulslash approved these changes

2020-10-23 15:59 UTC, merged