add last used ball
rh-hideout/pokeemerald-expansion pull request #1549
Opened 2021-06-25 19:39 UTC by ghoulslash

Add (configurable) last used ball feature

## Description
- Press "R" on the choose-action menu in battle to throw the last-thrown ball.
- Can be turned off by setting `B_LAST_USED_BALL` to `FALSE`
- Can change the button (or button combo) by changing `B_LAST_USED_BALL_BUTTON`. The graphic will need to be updated though

![last_ball](https://user-images.githubusercontent.com/41651341/123477020-b5766280-d5ba-11eb-847b-42bb0c09dc2c.gif)

2021-07-18 15:58 UTC, LOuroboros commented
There's merge conflicts that need to be solved :eyes:

2021-09-01 02:10 UTC, LOuroboros commented
There's more merge conflicts in `src/item_use.c` that need to be solved 👀

2021-09-01 11:51 UTC, ghoulslash commented
ready for re review

2021-09-23 00:51 UTC, AsparagusEduardo requested changes

2021-09-23 00:51 UTC, AsparagusEduardo commented on include/global.h
> +    /*0x90*/ u16 lastUsedBall;
I tested behavior in vanilla SwSh and it doesn't keep the last used ball when saving, instead reverting to the first ball in the pocket. I feel that modifying saveblock is out of scope for BE, so only setting up EWRAM data should be enough.

2021-09-23 00:51 UTC, AsparagusEduardo commented on include/constants/battle_config.h
> +#define B_LAST_USED_BALL_BUTTON     R_BUTTON    // If last used ball is implemented, this button (or button combo) will trigger throwing the last used ball.
It'd be good to add in the config comment that the button graphic isn't updated when changing button combinations.

2021-09-23 16:05 UTC, ghoulslash commented
ready for re-review.

- I've added separate graphics for the last used ball window based on the button config option (L vs. R)
- As per SwSh behavior, I've removed the saveblock field and replaced it with an EWRAM variable.

2021-09-23 19:31 UTC, AsparagusEduardo requested changes
I have a suggestion: : a ball count for the interface could be useful for this feature :D
If you don't want to do it it's ok :)

2021-09-23 19:31 UTC, AsparagusEduardo commented on src/battle_interface.c
> +        gLastThrownBall = ITEM_POKE_BALL;
Regarding SwSh behavior, when loading a save it loads the first ball in the pocket instead of defaulting to Poké Balls. Could you implement this?

2021-10-01 02:31 UTC, AsparagusEduardo commented
Calls to `lastUsedBall` were removed, but it's still in the saveblock.

2021-10-09 20:27 UTC, AsparagusEduardo approved these changes

2021-10-09 20:27 UTC, merged