Moves affected by Terrain: Camouflage, Secret Power & Terrain Pulse
rh-hideout/pokeemerald-expansion pull request #1724
Opened 2021-10-05 02:02 UTC by AsparagusEduardo

## Description
- Camouflage's type affected by terrain.
- Secret Power's effect and animation affected by terrain. Addresses #1662 .
- Implemented Terrain Pulse. Addresses #1094 .

(Originally by Fontbane, resubmitted with permission).

## **Discord contact info**
AsparagusEduardo#6051

2021-10-05 22:06 UTC, AsparagusEduardo commented
I decided to leave the animation for later. Ready for review.

2021-10-06 13:18 UTC, ghoulslash requested changes

2021-10-06 13:18 UTC, ghoulslash commented on data/battle_anim_scripts.s
> +	goto Move_DRAGON_PULSE @Temporary, needs to setup different animations based on terrain
What does the animation look like in game? A simple pulse animation that changes particle color based on terrain would be relatively easy to implement

2021-10-06 13:18 UTC, ghoulslash commented on data/battle_anim_scripts.s
>  Move_SECRET_POWER:
should these animations be updated to [Gen 7](https://bulbapedia.bulbagarden.net/wiki/Secret_Power_%28move%29#Generation_VII)?

2021-11-07 14:46 UTC, AsparagusEduardo commented
Ready for re-review
- Added animations to Terrain Pulse:
  - Without terrain:
  ![normal](https://user-images.githubusercontent.com/2904965/140649235-7d56e5a2-6848-4176-b86a-ef860462c9f2.gif)
  - Grassy and Misty Terrains:
  ![grassy](https://user-images.githubusercontent.com/2904965/140649311-1248e950-ba7b-40c3-bd8e-40bf888dcc80.gif) ![misty](https://user-images.githubusercontent.com/2904965/140649312-65b54efd-ab9e-4dcd-98ea-3c1aa4c8f7cb.gif)
  - Psychic and Terrains:
  ![psychic](https://user-images.githubusercontent.com/2904965/140649313-8655acf3-cea4-47f4-82e0-901f90e4faf3.gif) ![electric](https://user-images.githubusercontent.com/2904965/140649314-6cea0413-ce86-462c-97d2-2151f6edb963.gif)
  - Added config for Secret Power's effects and animations.
  - Added new battle terrains to complete Secret Power's, Nature Power's and Camouflage's data (plus added failsafes in case new terrains are added and are not accounted for these moves.

2021-11-07 22:38 UTC, ghoulslash approved these changes

2021-11-07 22:39 UTC, merged