Implement Gorilla Tactics
rh-hideout/pokeemerald-expansion pull request #1828
Opened 2021-10-30 05:33 UTC by BuffelSaft

## Description
Adds the effect of Gorilla Tactics; it's just Choice Band but as an ability.

## **Discord contact info**
Buffel Saft#2205

2021-10-30 13:21 UTC, ghoulslash requested changes

2021-10-30 13:21 UTC, ghoulslash commented on src/battle_script_commands.c
> +             && (HOLD_EFFECT_CHOICE(holdEffectAtk) || GetBattlerAbility(gBattlerAttacker))
`&& (HOLD_EFFECT_CHOICE(holdEffectAtk) || GetBattlerAbility(gBattlerAttacker) == ABILITY_GORILLA_TACTICS)`?

2021-10-30 23:10 UTC, BuffelSaft commented on src/battle_script_commands.c
> +             && (HOLD_EFFECT_CHOICE(holdEffectAtk) || GetBattlerAbility(gBattlerAttacker))
> `&& (HOLD_EFFECT_CHOICE(holdEffectAtk) || GetBattlerAbility(gBattlerAttacker) == ABILITY_GORILLA_TACTICS)`?

Oops, fixed!

2021-10-31 01:44 UTC, ghoulslash approved these changes

2021-10-31 01:44 UTC, merged