Add Neutralizing Gas
rh-hideout/pokeemerald-expansion pull request #1834
Opened 2021-10-30 15:34 UTC by ghoulslash

- Neutralizing Gas is announced before entry hazards
- Neutralizing Gas suppresses abilities (in this example, Hyper Cutter)
![neutralizing_gas2](https://user-images.githubusercontent.com/41651341/139539503-54bbea4f-c742-4296-9da9-a20d9eeb5ace.gif)

- Switch-in abilities occur as the Pokemon with Neutralizing Gas switches out
![neutralizing_gas](https://user-images.githubusercontent.com/41651341/139539507-1de07895-dc79-492e-a9aa-47d0eeddc2af.gif)

**NOTE:** the `jumpifbytenotequal gBattlerTarget, sByteFour, BattleScript_NeutralizingGasExitsLoop` in `BattleScript_NeutralizingGasExits` seems unecessary, but comparing directly to `gBattlersCount` caused the battle script to mess up.

2021-10-30 15:37 UTC, LOuroboros requested changes

2021-10-30 15:37 UTC, LOuroboros commented on src/battle_script_commands.c
> +    gActiveBattler = gBattlerAttacker;
```suggestion
    gActiveBattler = gBattlerAttacker;
```

2021-10-30 15:37 UTC, LOuroboros commented on src/battle_script_commands.c
> +{
```suggestion
{
```

2021-10-30 15:37 UTC, LOuroboros commented on src/battle_script_commands.c
> +
```suggestion

```

2021-10-30 16:00 UTC, LOuroboros commented
I can't find information on whether Run Away is supposed to be blocked by Neutralizing Gas or not.
Right now, it's not being affected in this PR :eyes:
![%pn_1694](https://user-images.githubusercontent.com/4485172/139540451-cc982acd-c6b8-4460-9648-ec0006d62e60.gif)

2021-11-01 20:14 UTC, LOuroboros commented on src/battle_util.c
> +}
Instead of adding a function for this, wouldn't it be better to just use `IsAbilityOnField`? :eyes:

2021-11-14 03:27 UTC, AsparagusEduardo approved these changes

2021-11-14 03:27 UTC, merged