Fix Knock Off, add config
rh-hideout/pokeemerald-expansion pull request #1887
Opened 2021-11-12 08:08 UTC by BuffelSaft

## Description
Addresses #1886.

Added a config for Knock Off's damage boost. Also fixed the conditions it checks to do bonus damage:
- Shouldn't do bonus damage if the target can't lose its item
- Should do bonus damage if the target has Sticky Hold

## **Discord contact info**
Buffel Saft#2205

2021-11-12 12:39 UTC, ghoulslash requested changes
I think PR should update all of knock off's updates while we're at it.

`gBattleStruct->itemStolen` stores original hold items of all of the player's party at the start of battle. If the field `stolen` is set, the original item will be restored at the end of battle if it isn't a berry. So I think it would be as easy as changing `TryKnockOffBattleScript` to:
```
static bool32 TryKnockOffBattleScript(u32 battlerDef)
{
    if (gBattleMons[battlerDef].item != 0
        && CanBattlerGetOrLoseItem(battlerDef, gBattleMons[battlerDef].item)
        && !NoAliveMonsForEitherParty())
    {
        if (GetBattlerAbility(battlerDef) == ABILITY_STICKY_HOLD && IsBattlerAlive(battlerDef))
        {
            gBattlerAbility = battlerDef;
            BattleScriptPushCursor();
            gBattlescriptCurrInstr = BattleScript_StickyHoldActivates;
        }
        else
        {
            u32 side = GetBattlerSide(battlerDef);

            gLastUsedItem = gBattleMons[battlerDef].item;
            gBattleMons[battlerDef].item = 0;
            gBattleStruct->choicedMove[battlerDef] = 0;

#if B_KNOCK_OFF >= GEN_5
           if (!<is_consumable>)
                gBattleStruct->itemStolen[battlerDef].stolen = TRUE;

           BtlController_EmitSetMonData(0, REQUEST_HELDITEM_BATTLE, 0, 2, &gBattleMons[battlerDef].item);
    MarkBattlerForControllerExec(gActiveBattler);
#else
            gWishFutureKnock.knockedOffMons[side] |= gBitTable[gBattlerPartyIndexes[battlerDef]];
#endif
            CheckSetUnburden(battlerDef);

            BattleScriptPushCursor();
            gBattlescriptCurrInstr = BattleScript_KnockedOff;
        }
        return TRUE;
    }
    return FALSE;
}
```

the tricky part determining which items are consumable (to be returned after battle) vs. just berries

2021-11-14 04:28 UTC, BuffelSaft commented
> I think PR should update all of knock off's updates while we're at it.

I think it'd be best to tackle that separately as `is_consumable` will likely require adding flags to the item data, and that point it becomes multiple PRs that may take some time to get tested etc. I'd rather this one stay a quick bug fix just to get this issue resolved.

2021-11-14 13:23 UTC, ghoulslash commented
> > I think PR should update all of knock off's updates while we're at it.
> 
> I think it'd be best to tackle that separately as `is_consumable` will likely require adding flags to the item data, and that point it becomes multiple PRs that may take some time to get tested etc. I'd rather this one stay a quick bug fix just to get this issue resolved.

That seems fine to me

2021-11-14 13:27 UTC, ghoulslash approved these changes

2021-11-14 13:27 UTC, merged