wish update
rh-hideout/pokeemerald-expansion pull request #1892
Opened 2021-11-12 22:56 UTC by ghoulslash

According to [bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Wish_%28move%29), in Gen5+ wish heals half the user's max hp instead of the target's. This PR addresses that.

2021-11-12 23:35 UTC, AsparagusEduardo requested changes

2021-11-12 23:35 UTC, AsparagusEduardo commented on include/constants/battle_config.h
> +#define B_WISH                      GEN_7 // In Gen5+, it heals half of the user's max HP instead of the target
```suggestion
#define B_WISH_HP_SOURCE            GEN_7 // In Gen5+, Wish heals half of the user's max HP instead of the target's.
```

2021-11-12 23:35 UTC, AsparagusEduardo commented on src/battle_script_commands.c
> +        #if B_WISH >= GEN_5
```suggestion
        #if B_WISH_HP_SOURCE >= GEN_5
```

2021-11-13 13:50 UTC, ghoulslash commented
ready for review again

2021-11-13 14:00 UTC, AsparagusEduardo approved these changes

2021-11-13 14:01 UTC, merged