Turn order is recalculated after some actions
rh-hideout/pokeemerald-expansion pull request #1943
Opened 2021-11-23 13:09 UTC by kleeenexfeu

It's a double battle mechanic introduced in gen8, and triple if someone ever implements them.
Essentially, when you are in double battle, a move or a switch avec consequences for the turn order of the battlers that haven't played yet.
To illustrate this, if there is a swift swimmer in the battle, and the whether is normal, but the first pokémon to move uses rain dance, then swift swim will immediately take effect and the turn order recalculated accordingly.
Same goes if there's a paralysis, a mid turn speed drop, etc.
This also have the nice side effect of making an implementation of quash trivial.
All we have to do it having a QuashMarker in a structure you see fit (1 bit for each pokemon on the field); and then when calling GetWhoStrikesFirst, a marked pokemon will have a decreased priority bracket -or whatever the effect of the move is.
Then, the code we have here will automatically take care of the rest.

For people who want to have the speed mechanic pre-gen8 (which was in my opinion an oversight that just last for years) but still want quash, the double loop must just start with an if(IsAnyPokemonQuashed) statement.

I also moved 2 configs from the battle_config.h file, and rename a section, as Lunos and Aspa suggested when I was doing the Mega alter turn calculationg thing.

2021-11-23 13:20 UTC, LOuroboros requested changes

2021-11-23 13:20 UTC, LOuroboros commented on include/constants/battle_config.h
> +#define B_RECALC_TURN_AFTER_ACTIONS GEN_8 // In gen 8, switching/using a move have consequences for the turn order of the current turn.
```suggestion
#define B_RECALC_TURN_AFTER_ACTIONS GEN_8 // In Gen8, switching/using a move have consequences for the turn order of the current turn.
```

2021-11-23 13:21 UTC, AsparagusEduardo commented on include/constants/battle_config.h
> +#define B_RECALC_TURN_AFTER_ACTIONS GEN_8 // In gen 8, switching/using a move have consequences for the turn order of the current turn.
```suggestion
#define B_RECALC_TURN_AFTER_ACTIONS GEN_8 // In Gen8, switching/using a move have consequences for the turn order of the rest of the current turn.
```

2021-11-23 13:32 UTC, LOuroboros commented on include/constants/battle_config.h
> +#define B_RECALC_TURN_AFTER_ACTIONS GEN_8 // In Gen8, switching/using a move affects the current turn's order of switches/moves used.
```suggestion
#define B_RECALC_TURN_AFTER_ACTIONS GEN_8 // In Gen8, switching/using a move affects the current turn's order of actions.
```

2022-01-22 22:02 UTC, AsparagusEduardo approved these changes

2022-01-22 22:07 UTC, merged