Implementing Teatime effect
rh-hideout/pokeemerald-expansion pull request #1956
Opened 2021-11-29 04:03 UTC by SonikkuA-DatH

Note: requires the Bugbite/Stuffed Cheeks PR [here](https://github.com/rh-hideout/pokeemerald-expansion/pull/1581)

![Teatimeeo](https://user-images.githubusercontent.com/58025603/143806880-92810d05-4c9b-46b1-b15e-04ff58c31677.gif)

Solves [#1059](https://github.com/rh-hideout/pokeemerald-expansion/issues/1059)

This PR implements Teatime's effect. Has an edge case for Electrify -> Lightningrod to enable the move to cycle through all battlers with Lightning Rod/Motor Drive/Volt Absorb, and invulnerable mons

TODO []: Confirm if there's ways to block Teatime outside Max Guard. Embargo and Protect don't
TODO []: Confirm if ground types are affected if Teatime is Electrified

Discord: Dat.H A#697

2022-09-09 23:20 UTC, AsparagusEduardo requested changes
I thought I had submitted this review, but I found it as pending. I'm really sorry :(

2022-12-18 23:56 UTC, SonikkuA-DatH commented on data/battle_scripts_1.s
> +    goto BattleScript_MoveEnd
Should be fixed

2022-12-18 23:56 UTC, SonikkuA-DatH commented on data/battle_scripts_1.s
> +    goto BattleScript_MoveEnd
All set

2022-12-18 23:57 UTC, SonikkuA-DatH commented on data/battle_scripts_1.s
> +    playstatchangeanimation BS_TARGET, BIT_SPEED, STAT_CHANGE_BY_TWO
It's good now

2022-12-18 23:57 UTC, SonikkuA-DatH commented on data/battle_scripts_1.s
> +    goto BattleScript_MoveEnd
Okie dokie, it is done now

2022-12-18 23:57 UTC, SonikkuA-DatH commented on data/battle_scripts_1.s
> +jumpifmotoraffected BS_TARGET, BattleScript_Teatimemotor
Easy

2022-12-18 23:58 UTC, SonikkuA-DatH commented on data/battle_scripts_1.s
> +@ at least one battler is affected
Anything else?

2022-12-18 23:58 UTC, SonikkuA-DatH commented on data/battle_scripts_1.s
> +    goto BattleScript_MoveEnd
Aaand, done!

2022-12-18 23:58 UTC, SonikkuA-DatH commented on src/battle_script_commands.c
> +		return;
No tabs here!

2022-12-18 23:59 UTC, SonikkuA-DatH commented on data/battle_scripts_1.s
> +    goto BattleScript_MoveEnd
This good?

2022-12-19 02:25 UTC, AsparagusEduardo commented
It's not building.

2022-12-19 02:27 UTC, LOuroboros commented on data/battle_scripts_1.s
> +  .4byte BattleScript_EffectTeatime                 @ EFFECT_TEATIME
```suggestion
	.4byte BattleScript_EffectTeatime                     @ EFFECT_TEATIME
```

2022-12-19 02:33 UTC, LOuroboros requested changes

2022-12-19 02:33 UTC, LOuroboros commented on src/battle_script_commands.c
> +	}
```suggestion
	if (moveType == TYPE_ELECTRIC && GetBattlerAbility(gBattlerTarget) == ABILITY_LIGHTNING_ROD)
		return TRUE;
	else
		return FALSE;
```

2022-12-19 02:33 UTC, LOuroboros commented on src/battle_script_commands.c
> +}
```suggestion
static bool32 IsAbilityMotorAffected(void)
{
    u32 moveType;

    if (gBattleStruct->dynamicMoveType == 0)
        moveType = gBattleMoves[gCurrentMove].type;
    else if (!(gBattleStruct->dynamicMoveType & 0x40))
        moveType = gBattleStruct->dynamicMoveType & 0x3F;
    else
        moveType = gBattleMoves[gCurrentMove].type;

    if (moveType == TYPE_ELECTRIC && GetBattlerAbility(gBattlerTarget) == ABILITY_MOTOR_DRIVE)
        return TRUE;
    else
        return FALSE;
}
```

2022-12-19 02:33 UTC, LOuroboros commented on src/battle_script_commands.c
> +        return;
```suggestion
    case VARIOUS_TEATIME_TARGETS:
    {
        u32 count = 0;

        for (i = 0; i < gBattlersCount; i++)
        {
            if (IsTeatimeAffected(i))
                count++;
        }
        if (count == 0)
            gBattlescriptCurrInstr = T1_READ_PTR(gBattlescriptCurrInstr + 3);   // Teatime fails
        else
            gBattlescriptCurrInstr += 7;
    }
    return;
```

2022-12-20 01:13 UTC, LOuroboros requested changes

2022-12-21 02:02 UTC, AsparagusEduardo requested changes

2022-12-21 02:02 UTC, AsparagusEduardo commented on src/battle_util.c
>                  gSpecialStatuses[gActiveBattler].lightningRodRedirected = TRUE;
```suggestion
            if (battlerAbility == ABILITY_LIGHTNING_ROD && gCurrentMove != MOVE_TEATIME)
                gSpecialStatuses[gActiveBattler].lightningRodRedirected = TRUE;
```

2022-12-21 15:42 UTC, AsparagusEduardo commented
Did you end up confirming the TODOs?

2022-12-30 20:49 UTC, AsparagusEduardo approved these changes

2022-12-30 20:49 UTC, merged