Ability Popup Fixes + Longer Ability Names config
rh-hideout/pokeemerald-expansion pull request #1957
Opened 2021-11-29 17:44 UTC by ghoulslash

- Make ability popup larger and fix printing ability names
- add a function to clean the ability name to fix wandering spirit
- Config option, `B_EXPANDED_ABILITY_NAMES` to increase ability name length from 12 to 16 chars (and associated ability name fixes
![pokeemerald-1](https://user-images.githubusercontent.com/41651341/143917175-4866a33b-0c02-4663-9733-b78412e26296.png)
)

2021-11-29 19:45 UTC, LOuroboros requested changes

2021-11-29 19:45 UTC, LOuroboros commented on src/battle_interface.c
> +	}
Spaces instead of tabs.

2021-11-29 19:45 UTC, LOuroboros commented on src/battle_interface.c
> +	u8 *buffer = Alloc(sizeof(sAbilityPopUpGfx) * 2);
Spaces instead of tabs.

2021-11-29 19:45 UTC, LOuroboros commented on src/battle_interface.c
> +	CpuCopy32(tiles, buffer, sizeof(sAbilityPopUpGfx));
Spaces instead of tabs.

2021-11-29 19:45 UTC, LOuroboros commented on src/battle_interface.c
> +	}
Spaces instead of tabs.

2021-11-29 19:45 UTC, LOuroboros commented on src/battle_interface.c
> +	Free(buffer);
Spaces instead of tabs.

2021-11-29 19:45 UTC, LOuroboros commented on include/battle_main.h
> +#endif
```suggestion
#endif
```

2021-11-29 19:45 UTC, LOuroboros commented on src/battle_interface.c
> +	{186, 36}, // opponent right
Spaces instead of tabs.

2021-11-29 19:45 UTC, LOuroboros commented on src/battle_interface.c
> +	{186, 57}, // opponent
Spaces instead of tabs.

2021-11-29 19:45 UTC, LOuroboros commented on src/battle_interface.c
> +	winTemplate.height = 2;
Spaces instead of tabs.

2021-11-29 19:45 UTC, LOuroboros commented on src/battle_interface.c
> +	FillWindowPixelBuffer(*windowId, PIXEL_FILL(color1));
Spaces instead of tabs.

2021-11-29 19:45 UTC, LOuroboros commented on src/battle_interface.c
> +	return (u8*)(GetWindowAttribute(*windowId, WINDOW_TILE_DATA));
Spaces instead of tabs.

2021-11-29 19:45 UTC, LOuroboros commented on src/battle_interface.c
> +	}
Spaces instead of tabs.

2021-11-29 19:45 UTC, LOuroboros commented on src/battle_interface.c
> +	}
Spaces instead of tabs.

2021-11-29 19:45 UTC, LOuroboros commented on src/battle_interface.c
> +/*Add pixels by X*/								\
Spaces instead of tabs.

2021-11-29 19:45 UTC, LOuroboros commented on src/battle_interface.c
> +	{PIXEL_COORDS_TO_OFFSET(16, 48), 8},
Spaces instead of tabs.

2021-12-22 21:29 UTC, Jaizu commented
Shouldn't those edits to the gen 3 ability names have ifdefs?

2021-12-22 21:31 UTC, ghoulslash commented
> Shouldn't those edits to the gen 3 ability names have ifdefs?

Its one big ifdef

2021-12-23 13:45 UTC, ghoulslash commented
formatting fixed. ready for review

2022-01-01 22:39 UTC, AsparagusEduardo approved these changes

2022-01-01 22:39 UTC, merged