Correcting Base Quash effect for current gen
rh-hideout/pokeemerald-expansion pull request #1974
Opened 2021-12-04 02:14 UTC by SonikkuA-DatH

Largely done by @kleeenexfeu

Note: Relies on his Speed tier priority PR [here](https://github.com/rh-hideout/pokeemerald-expansion/pull/1943)
Also does not factor pre Gen 8 priority yet

https://user-images.githubusercontent.com/58025603/144693306-6779191e-7400-4857-8999-6f418030e71e.mp4

2021-12-04 10:02 UTC, kleeenexfeu commented
In src/data/battle_moves.h the magic coat flag should be removed, according to bulbapedia.
The edge case of pursuit being used against a switching mon isn't handled, but it's more of a cosmetic change -plus bulbapedia doesn't mention anything about it.

2022-05-09 15:24 UTC, ghoulslash requested changes

2022-05-09 15:24 UTC, ghoulslash commented on include/battle.h
> +    u8 quash : 1;
`quash:1;` for style consistency

2022-05-09 15:24 UTC, ghoulslash commented on src/battle_main.c
> +	    gProtectStructs[gBattlerTarget].quash = FALSE;
please fix the spacing here

2022-05-09 15:24 UTC, ghoulslash commented on src/battle_main.c
> +    if (gProtectStructs[battlerId].quash == 1)
to match pret styling, can you add a space between lines 4414 and 4415? also, remove the braces. Also remember spaces instead of tabs

2022-05-09 15:24 UTC, ghoulslash commented on src/battle_script_commands.c
> +            gProtectStructs[gBattlerTarget].quash = 1;
`.quash = TRUE`

2022-08-24 23:32 UTC, AsparagusEduardo commented
Superseded by #2239.

2022-08-24 23:32 UTC, closed without merging