fix clanging scales triggering defense drop twice in double
rh-hideout/pokeemerald-expansion pull request #1982
Opened 2021-12-05 21:41 UTC by kleeenexfeu

Addresses https://github.com/rh-hideout/pokeemerald-expansion/issues/1654
Also accounts for parental bond PR, but doesn't need it

2021-12-05 21:43 UTC, LOuroboros requested changes

2021-12-05 21:43 UTC, LOuroboros commented on src/battle_script_commands.c
> +                break;
```suggestion
        case MOVE_TARGET_BOTH:
            if (CountAliveMonsInBattle(BATTLE_ALIVE_DEF_SIDE) >= 2) // Check for single target
                return TRUE;
            break;
        case MOVE_TARGET_FOES_AND_ALLY:
            if (CountAliveMonsInBattle(BATTLE_ALIVE_EXCEPT_ATTACKER) >= 2) // Count mons on both sides; ignore attacker
                return TRUE;
            break;
```

2021-12-05 21:43 UTC, LOuroboros commented on src/pokemon.c
> +	case BATTLE_ALIVE_EXCEPT_ATTACKER:
Spaces instead of tab.

2021-12-05 21:43 UTC, LOuroboros commented on src/pokemon.c
> +		break;
Spaces instead of tab.

2022-10-18 11:36 UTC, AsparagusEduardo commented
Closing this for now, as the required PR is in review purgatory and after such a long time it'll be better to tackle this in a new PR.

2022-10-18 11:36 UTC, closed without merging