AI Optimizations
rh-hideout/pokeemerald-expansion pull request #2036
Opened 2022-01-13 16:37 UTC by ghoulslash

Speeds up the AI and make it more efficient by:
- abilities, hold effects, etc and damage/effectiveness computations are performed before `HandleTurnActionSelectionState` runs so that the data is only collected once per turn as opposed for each AI battler and/or AI function
- Effectiveness is stored during the damage calc function instead of being called separately (in most cases)
- some battle utility functions are changed to take ability, hold effect, etc as an input arg so AI utility funcs can call them directly
- many WEATHER_HAS_EFFECT checks are moved after the weather bitfield check so the ability loop checks are not done if the weather is absent. this speeds up the damage calculation function
- removed unnecessary gBattleStruct->aiSimulatedDmg, as the values are already stored in AI_DATA->siimulatedDmg

2022-07-02 00:47 UTC, BuffelSaft commented
I've done some quick testing, and it seems the start of turn freeze is gone in doubles, so the optimizations are good!
One issue I've found: status moves seem to have small amounts of damage calculated/stored for them instead of having it set to zero. This appears to be an issue with this PR:
Latest version of BE:
![pokeemerald-1](https://user-images.githubusercontent.com/28769716/176980353-0b9db6a5-1b7b-4367-aee8-81e6ac68de98.png)
This PR:
![pokeemerald-0](https://user-images.githubusercontent.com/28769716/176980348-a0529b99-72f6-4165-ad19-ee03d4f04673.png)
Both screenshots are youngster Calvin using Sidney's party and flags in a double battle, with no other changes:
```
    [TRAINER_CALVIN_1] =
    {
        .partyFlags = F_TRAINER_PARTY_HELD_ITEM | F_TRAINER_PARTY_CUSTOM_MOVESET,
        .trainerClass = TRAINER_CLASS_YOUNGSTER,
        .encounterMusic_gender = TRAINER_ENCOUNTER_MUSIC_MALE,
        .trainerPic = TRAINER_PIC_YOUNGSTER,
        .trainerName = _("CALVIN"),
        .items = {},
        .doubleBattle = TRUE,
        .aiFlags = AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_TRY_TO_FAINT | AI_FLAG_CHECK_VIABILITY | AI_FLAG_PREFER_STRONGEST_MOVE,
        .partySize = ARRAY_COUNT(sParty_Sidney),
        .party = {.ItemCustomMoves = sParty_Sidney},
    },
```

2022-07-02 03:01 UTC, BuffelSaft requested changes
Just went through the code changes, I'm happy to approve this once conflicts are resolved and that one line with extra spaces is cleaned up. Looks really good!

2022-07-03 21:24 UTC, ghoulslash commented
`AI_CalcDamage` is updated to return 0 for moves with 0 power, and conflicts taken care of. ready for re review

2022-07-04 11:15 UTC, BuffelSaft approved these changes

2022-07-04 11:16 UTC, merged