added special battle evo changes
rh-hideout/pokeemerald-expansion pull request #2112
Opened 2022-05-05 18:43 UTC by AgustinGDLV

Added framework for non-level related battle evolutions and specific functionality for Galarian Farfetch'd's evolution method (even though I'm realizing G-Farfetch'd isn't included in the battle_engine).

## **Discord contact info**
Agustin#1522

2022-05-05 20:08 UTC, AsparagusEduardo requested changes

2022-05-05 20:08 UTC, AsparagusEduardo commented on src/pokemon.c
> +        break;
This should go in #2113 enclosed with in a `#ifdef BATTLE_EXPANSION`  preproc.

2022-05-05 20:08 UTC, AsparagusEduardo commented on include/constants/pokemon.h
> +#define EVO_CRITICAL_HITS                 35     // Pokémon performs specified number of critical hits in one battle
Evolution constants and modes should be synced with #2113 to avoid conflicts.

2022-05-05 20:08 UTC, AsparagusEduardo commented on include/constants/pokemon.h
> +#define EVO_MODE_BATTLE_SPECIAL 4
Evolution constants and modes should be synced with #2113 to avoid conflicts.

2022-05-05 20:11 UTC, AsparagusEduardo commented on src/battle_main.c
> +        u16 species = GetEvolutionTargetSpecies(&gPlayerParty[i], EVO_MODE_BATTLE_SPECIAL, i, SPECIES_NONE);
compile error:
```
src/battle_main.c: In function `TrySpecialEvolution':
src/battle_main.c:5194: too many arguments to function `GetEvolutionTargetSpecies'
```

2022-05-06 02:28 UTC, AgustinGDLV commented
Updated both PRs with the suggestions

2022-05-07 16:10 UTC, AsparagusEduardo requested changes

2022-05-07 16:10 UTC, AsparagusEduardo commented on include/constants/pokemon.h
> +#define EVO_CRITICAL_HITS                 35     // Pokémon performs specified number of critical hits in one battle
```suggestion
#define EVO_CRITICAL_HITS                 35     // Pokémon performs specified number of critical hits in one battle
#define EVO_SCRIPT_TRIGGER_DMG            36     // Pokémon has specified HP below max, then player interacts trigger
#define EVO_DARK_SCROLL                   37     // interacts with Scroll of Darkness
#define EVO_WATER_SCROLL                  38     // interacts with Scroll of Waters
```

2022-05-07 16:28 UTC, AsparagusEduardo commented on include/constants/pokemon.h
> +#define EVO_MODE_BATTLE_SPECIAL 4
```suggestion
#define EVO_MODE_NORMAL            0
#define EVO_MODE_TRADE             1
#define EVO_MODE_ITEM_USE          2
#define EVO_MODE_ITEM_CHECK        3 // If an Everstone is being held, still want to show that the stone *could* be used on that Pokémon to evolve
#define EVO_MODE_BATTLE_SPECIAL    4
#define EVO_MODE_OVERWORLD_SPECIAL 5
```

2022-05-07 20:26 UTC, AsparagusEduardo commented on src/battle_main.c
> +            u16 species = GetEvolutionTargetSpecies(&gPlayerParty[i], EVO_MODE_BATTLE_SPECIAL, i, SPECIES_NONE);
```suggestion
            u16 species = GetEvolutionTargetSpecies(&gPlayerParty[i], EVO_MODE_BATTLE_SPECIAL, i, NULL);
```

2022-05-07 23:13 UTC, AsparagusEduardo commented on include/constants/pokemon.h
>  #define EVO_MODE_NORMAL     0
I forgot to remove this `EVO_MODE_NORMAL` in my suggestion, you'll need to delete it

2022-05-09 21:40 UTC, AsparagusEduardo approved these changes

2022-05-09 21:40 UTC, merged