functional but not perfect implementation
rh-hideout/pokeemerald-expansion pull request #2117
Opened 2022-05-06 22:06 UTC by AgustinGDLV

Addresses issue #346. Symbiosis has a lot of annoying edge cases, so this may require some more testing. Currently implemented like Cheek Pouch, may require some more code to work around other issues. I've done some testing to confirm proper interactions, which you can see below. Untested doesn't necessarily mean incorrect.

**Current Issues:**
- Gem interactions unknown.
- Bestow gets cut off early when Symbiosis procs.
- If an ally eats a foe's berry with Bug Bite but it has no effect (e.g. Sitrus Berry on max HP), Symbiosis does not proc.

**Tested Interactions:**
- [x] Red Card
- [x] Focus Sash
- [x] Bug Bite (user has no item and berry is successfully consumed)
- [x] Knock Off
- [x] Incinerate
- [x] Air Balloon
- [ ] Trick
- [ ] Eject Button / Pack
- [ ] Gems
- [ ] Unexchangeable Items
- [ ] Fling
- [ ] Natural Gift
- [ ] Damage-reducing Berries
- [ ] Multiple Symbiosis abilities on side
- [ ] Gem behavior differences in Gen 6 and Gen 7+

## **Discord Contact Info**
Agustin#1522

2022-05-07 05:18 UTC, AgustinGDLV commented
New commit. Other than some major issues with Fling, Symbiosis is accurate and functional in an isolated BE branch. More testing required with items from IE.

Resolved Issues:
- Bestow gets cut off early when Symbiosis procs.
- If an ally eats a foe's berry with Bug Bite but it has no effect (e.g. Sitrus Berry on max HP), Symbiosis does not proc.

2022-05-07 20:21 UTC, AgustinGDLV commented
Final commit? Tested most interactions and whatever edge cases I could think of. Gems and damage-reducing berries now function correctly (using a new MOVEEND effect), as do Eject Pack and Eject Button. Added battle config for gem function. I think this is complete!

2022-07-22 18:04 UTC, ghoulslash commented
fix conflicts

2022-09-24 17:17 UTC, AsparagusEduardo requested changes

2022-09-24 17:17 UTC, AsparagusEduardo commented on src/battle_script_commands.c
> +
```suggestion
static bool32 TrySymbiosis(u32 battler, u32 itemId)
{
    if (!gBattleStruct->itemStolen[gBattlerPartyIndexes[battler]].stolen
        && gBattleStruct->changedItems[battler] == ITEM_NONE
        && GetBattlerHoldEffect(battler, TRUE) != HOLD_EFFECT_EJECT_BUTTON
        && GetBattlerHoldEffect(battler, TRUE) != HOLD_EFFECT_EJECT_PACK
    #if B_SYMBIOSIS_GEMS >= GEN_7
        && !(gSpecialStatuses[battler].gemBoost)
    #endif
        && gCurrentMove != MOVE_FLING //Fling and damage-reducing berries are handled separately.
        && !gSpecialStatuses[battler].berryReduced
        && SYMBIOSIS_CHECK(battler, BATTLE_PARTNER(battler)))
    {
        BestowItem(BATTLE_PARTNER(battler), battler);
        gLastUsedAbility = gBattleMons[BATTLE_PARTNER(battler)].ability;
        gBattleScripting.battler = gBattlerAbility = BATTLE_PARTNER(battler);
        gBattlerAttacker = battler;
        BattleScriptPush(gBattlescriptCurrInstr + 2);
        gBattlescriptCurrInstr = BattleScript_SymbiosisActivates;
        return TRUE;
    }
    return FALSE;
}

```

2022-09-24 17:17 UTC, AsparagusEduardo commented on src/battle_script_commands.c
> +        break;
```suggestion
    case VARIOUS_TRY_SYMBIOSIS: //called by Bestow, Fling, and Bug Bite, which don't work with Cmd_removeitem.
        if (SYMBIOSIS_CHECK(gActiveBattler, BATTLE_PARTNER(gActiveBattler)))
        {
            BestowItem(BATTLE_PARTNER(gActiveBattler), gActiveBattler);
            gLastUsedAbility = gBattleMons[BATTLE_PARTNER(gActiveBattler)].ability;
            gBattleScripting.battler = gBattlerAbility = BATTLE_PARTNER(gActiveBattler);
            gBattlerAttacker = gActiveBattler;
            BattleScriptPushCursor();
            gBattlescriptCurrInstr = BattleScript_SymbiosisActivates;
            return;
        }
        break;
```

2022-09-24 17:17 UTC, AsparagusEduardo commented on src/battle_script_commands.c
> +            break;
```suggestion
        case MOVEEND_SYMBIOSIS:
            for (i = 0; i < gBattlersCount; i++)
            {
                if ((gSpecialStatuses[i].berryReduced
                #if B_SYMBIOSIS_GEMS >= GEN_7
                    || gSpecialStatuses[i].gemBoost
                #endif
                    ) && SYMBIOSIS_CHECK(i, BATTLE_PARTNER(i)))
                {
                    BestowItem(BATTLE_PARTNER(i), i);
                    gLastUsedAbility = gBattleMons[BATTLE_PARTNER(i)].ability;
                    gBattleScripting.battler = gBattlerAbility = BATTLE_PARTNER(i);
                    gBattlerAttacker = i;
                    BattleScriptPushCursor();
                    gBattlescriptCurrInstr = BattleScript_SymbiosisActivates;
                    effect = TRUE;
                }
            }
            gBattleScripting.moveendState++;
            break;
```

2022-09-24 17:30 UTC, AsparagusEduardo approved these changes

2022-09-24 17:30 UTC, merged