Update Confuse Berry Hold Effect (Item Expansion)
rh-hideout/pokeemerald-expansion pull request #2122
Opened 2022-05-07 19:17 UTC by Sneed69

Added a config for these behaviors:

**Generations III-VI**
A confuse Berry, when held by a Pokémon, will restore 1/8 of its HP when its HP drops to ½ or below, but causes confusion to Pokémon that dislike the its flavor.
**Generation VII**
A Wiki Berry now restores ½ of the holder's HP when it drops to ¼ or below.
**Generation VIII**
The restored amount decreased to 1/3 of the holder's HP.

2022-05-07 20:20 UTC, AsparagusEduardo requested changes
Not too fan of adding a define in between the item data. It'd be better if the prepoc checks would be in each of the items, similar to how the Soul Dew is handled.

2022-05-07 20:29 UTC, Sneed69 commented
I don't see a reason to repeat the same code 6 times. This is what macros are for, no?

2022-05-07 20:39 UTC, AsparagusEduardo commented
Hmm, you're not wrong, though something like that was already done with Fling and `B_UPDATED_MOVE_DATA`. However, in that case, Fling could be tweaked such that it reads move data for TMs if the case applies. I want to weight in thoughts from other people on the Discord to see what they think about it.

2022-05-07 23:59 UTC, AsparagusEduardo commented on src/data/items.h
> +#elseif defined(BATTLE_ENGINE) && B_CONFUSE_BERRIES_HEAL == GEN_7
I forgot to say, for preprocs it's `#elif`, not `#elseif`.

2022-05-08 13:02 UTC, AsparagusEduardo approved these changes

2022-05-08 13:02 UTC, merged