Be/bugbite
rh-hideout/pokeemerald-expansion pull request #2138
Opened 2022-05-13 20:30 UTC by ghoulslash

- new bug bite implementation that does not temporarily change items
- Addresses #2027 

![bugbite](https://user-images.githubusercontent.com/41651341/168384732-26609b45-58dd-469e-962e-832db0446640.gif)

2022-05-13 21:20 UTC, AsparagusEduardo reviewed
I see that some `TRUE`s and `FALSE`s where changed to 1 and 0. Those should probably need to be reverted.

2022-05-14 00:34 UTC, LOuroboros commented
Is there a reason not to use `TRUE`/`FALSE` for `sBERRY_OVERRIDE`? :eyes:

2022-05-14 00:36 UTC, ghoulslash commented
> Is there a reason not to use `TRUE`/`FALSE` for `sBERRY_OVERRIDE`? 👀

because I changed it to be a "state", see: <https://github.com/rh-hideout/pokeemerald-expansion/pull/2138/files#diff-658ef5bc9368700b8dbd6f4137cf50a00220f0eb79e352bb9858047c45a4e09bR7125>

2022-05-14 00:45 UTC, LOuroboros commented on src/battle_util.c
> +        gBattleScripting.overrideBerryRequirements = 2; // to exit VARIOUS_CONSUME_BERRIES
```suggestion
        gBattleScripting.overrideBerryRequirements = 2; // to exit VARIOUS_CONSUME_BERRY
```

2022-05-14 15:57 UTC, AsparagusEduardo requested changes
Jaboca Berry's effect isn't activating before Bug Bite.
![mGBA_ZPRI5iQ7zg](https://user-images.githubusercontent.com/2904965/168439263-e8b43ec0-0675-48e4-ab26-8d32379a651f.gif)

2022-08-22 01:26 UTC, StephenLynx commented
I tested it out on IE and it seems to work fine.

2022-08-23 12:18 UTC, StephenLynx commented
I found the issue on my port: in battle_util GetBattlerHoldEffectParam was used with the id of the attacker while itemId was ignored in a few functions. So I used ItemId_GetHoldEffectParam directly with itemId in these places. this PR probably carries the same issue. https://gitgud.io/stephenlynx/pokemonie/-/commit/02107204b6f03d1f0d7a11cf69ec5d56ef40ea45

2022-08-23 17:43 UTC, StephenLynx commented
I fixed enigma berries, by the way. I was not sure if my commit broke them, because I couldn't find how the table was populated, but if they were broken, now they are surely fixed. 
https://gitgud.io/stephenlynx/pokemonie/-/commit/c0eb452d0ffbe43e669ea8ff0937bbaec6526b5e

2022-08-29 17:40 UTC, StephenLynx commented
I do believe to have found another bug. When it checks if the case is ITEMEFFECT_MOVE_END, there is a loop through the mons in the battle. Later checks that make use of gLastUsedItem will not be updated for subsequential mons, since it was set the last time right after ItemBattleEffects started on the check caseID != ITEMEFFECT_BATTLER_MOVE_END. I fixed it by setting gLastUsedItem to the item of the current on on the loop. 
https://gitgud.io/stephenlynx/pokemonie/-/commit/a2be0a20aebb1ed7051ef43b24632fb80dfd6d2c

2022-11-04 13:31 UTC, closed without merging