16-letter Move Names
rh-hideout/pokeemerald-expansion pull request #2183
Opened 2022-07-11 00:25 UTC by Greenphx9

## Description
Adds a define (B_EXPANDED_MOVE_NAMES) that changes the move name length to 16 characters, and fixes up "squashed" move names (eg: DublIronBash -> Double Iron Bash). Requires the user to make some changes to the summary screen, bag menu, and in-battle move selector to get fully working.

## **Discord contact info**
Greenphx#5428

2022-07-11 00:31 UTC, LOuroboros requested changes

2022-07-11 00:31 UTC, LOuroboros commented on include/constants/battle_config.h
> +#define B_EXPANDED_MOVE_NAMES           FALSE    // If TRUE, move names are increased from 12 characters to 16 characters.
Should be put in the "Interface settings" section, below `B_HIDE_HEALTHBOX_IN_ANIMS`.

2022-07-11 00:31 UTC, LOuroboros commented on include/constants/global.h
> +#include "battle_config.h"
```suggestion
#include "constants/battle_config.h"
```
There isn't a `include/battle_config.h` file in any of the 3 branches.
Also, this should be put at the top of the file, below `#define GUARD_CONSTANTS_GLOBAL_H` imo in order to remain consistent with the huge majority of the files in the project, kinda like this:
```
#define GUARD_CONSTANTS_GLOBAL_H

#include "constants/battle_config.h"

// Invalid Versions show as "----------" in Gen 4 and Gen 5's summary screen.
```

2022-07-11 00:31 UTC, LOuroboros commented on src/data/text/move_names.h
> +//16 letters
```suggestion
// 16 letters
```

2022-07-11 00:31 UTC, LOuroboros commented on src/data/text/move_names.h
> +//12 letters
```suggestion
// 12 letters
```

2022-07-11 00:31 UTC, LOuroboros commented on src/data/text/move_names.h
> +    //GEN 8
```suggestion
    // GEN 8
```
Though I don't know why is this comment here at all. There's no point to it, unless we added one to separate each generation's set of moves.

2022-07-11 00:56 UTC, LOuroboros requested changes

2022-07-11 00:56 UTC, LOuroboros commented on include/constants/battle_config.h
> +#define B_EXPANDED_MOVE_NAMES       FALSE // If TRUE, move names are increased from 12 characters to 16 characters.
```suggestion
#define B_EXPANDED_MOVE_NAMES       FALSE // If set to TRUE, move names are increased from 12 characters to 16 characters.
```

2022-07-21 20:13 UTC, ghoulslash submitted a review, later dismissed

2022-07-21 20:13 UTC, ghoulslash commented
fix conflicts

2022-07-29 12:17 UTC, ghoulslash approved these changes

2022-07-29 12:17 UTC, merged

2022-07-29 12:19 UTC, sphericalice commented on src/data/text/move_names.h
> +    [MOVE_STEAM_ERUPTION] = _("Steam Erruption"),
```suggestion
    [MOVE_STEAM_ERUPTION] = _("Steam Eruption"),
```