Quash
rh-hideout/pokeemerald-expansion pull request #2239
Opened 2022-08-24 21:46 UTC by DizzyEggg

This fixes #1803

It's based on this old PR #1974, but its owner seems to be inactive so I pulled their repo and did the requested changes.

2022-08-26 14:01 UTC, ghoulslash requested changes

2022-08-26 14:02 UTC, DizzyEggg commented on src/battle_main.c
> +            gProtectStructs[gBattlerTarget].quash = FALSE;
also missing from FaintClearSetData?

2022-08-26 14:10 UTC, ghoulslash commented on src/battle_main.c
> +            gProtectStructs[gBattlerTarget].quash = FALSE;
The protect struct fields are all cleared on fainting [here](https://github.com/rh-hideout/pokeemerald-expansion/blob/ae2ff4c1d88693aa06cdd5bc3796f7b7c83d2099/src/battle_main.c#L3167).

2022-08-29 08:24 UTC, DizzyEggg commented on src/battle_main.c
> +            gProtectStructs[gBattlerTarget].quash = FALSE;
Fixed

2022-08-29 08:26 UTC, AsparagusEduardo requested changes

2022-08-29 08:26 UTC, AsparagusEduardo commented on src/battle_main.c
> +		priority = -8;
Spaces instead of tabs

2022-08-29 08:27 UTC, DizzyEggg commented on src/battle_main.c
> +		priority = -8;
done

2022-08-29 14:43 UTC, ghoulslash approved these changes

2022-08-29 14:43 UTC, merged