Include mGBA Printf to help debugging
rh-hideout/pokeemerald-expansion pull request #2292
Opened 2022-09-04 22:28 UTC by AsparagusEduardo

## Description
- Includes @SBird1337's implementation + Oldplayer's modification that allows encoded strings to be used in `MgbaPrintf`.

## **Discord contact info**
AsparagusEduardo#6051

2022-09-04 22:38 UTC, Jaizu commented on src/main.c
> +    MgbaOpen();
Suggestion: Add this under an ifdef/config option. Not everybody might want it enabled as default and there is no reason to force it on -afail-

2022-09-04 22:44 UTC, AsparagusEduardo commented
Converted to draft until #2277 is merged

2022-09-05 01:24 UTC, SBird1337 requested changes
A few things I noticed. Keep in mind that this is for printing messages on an mgba log. If you try to write to the virtual registers on any other platforms it will not work as expected or crash. There's also quite a lot of either incomplete or duplicate code in this PR.

2022-09-05 01:24 UTC, SBird1337 commented on src/mgba_printf/mini_printf.c
> +static u8 decodeChar(u8 input)
This is incomplete, also referencing each alphanumerical character sounds a bit useless, also there is already an implementation here: <https://github.com/rh-hideout/pokeemerald-expansion/blob/c2d880fce9ba4fbe499da78aff0cb81ded65a257/src/mgba_printf/mgba.c#L46>

2022-09-05 01:24 UTC, SBird1337 commented on src/mgba_printf/mini_printf.c
> +static s32 _puts2(char *s, s32 len, void *buf)
cryptic name, this is essentially `putsEncoded` or whatever

2022-09-05 01:24 UTC, SBird1337 commented on src/mgba_printf/mini_printf.c
> +static s32 mini_strlen2(const char *s)
cryptic name, also essentially a copy of the library function `StringLength` that already exists in the game. It is debatable wether this should work as a standalone, but if not this should just use the string library function of the game.

2022-09-05 01:24 UTC, SBird1337 commented on src/mgba_printf/mini_printf.c
> +s32 mini_vpprintf(s32 (*puts)(char* s, s32 len, void* buf),s32 (*puts2)(char* s, s32 len, void* buf), void* buf, const char *fmt, va_list va)
The function essentially conforms to libc `vpprintf` which does not have a second function pointer argument. I think this should be reflected here, the alternate puts can just be called without a function pointer, essentially it is never called with another argument anyways.

2022-09-05 01:24 UTC, SBird1337 commented on src/mgba_printf/mini_printf.c
> +                    // MODIFIED: Use %S to convert to Ascii
Comment is not really necessary, if the function shouod be documented, it should be done at the top

2022-09-05 01:24 UTC, SBird1337 commented on src/mgba_printf/mgba.c
> +static u32 MgbaConvertPStringToAsciiN(const char *src, char *dst, u32 n)
If a pretty printing argument is provided we do not need an explicit function.

2022-09-05 01:24 UTC, SBird1337 commented on src/mgba_printf/mgba.c
> +static void MgbaPrintfBounded(s32 level, const char* ptr, ...)
this should be optional and stubbed if mgba debugging is disabled, the HW registers do not work on a real gba or anything that is not mgba.

2022-09-05 01:24 UTC, SBird1337 commented on src/mgba_printf/mgba.c
> +void MgbaPrintf(s32 level, const char* ptr, ...)
this should be optional and stubbed if mgba debugging is disabled, the HW registers do not work on a real gba or anything that is not mgba.

2022-09-05 01:24 UTC, SBird1337 commented on src/mgba_printf/mgba.c
> +bool8 MgbaOpen(void)
this should be optional and stubbed if mgba debugging is disabled, the HW registers do not work on a real gba or anything that is not mgba.

2022-09-05 01:24 UTC, SBird1337 commented on src/mgba_printf/mgba.c
> +void MgbaClose(void)
this should be optional and stubbed if mgba debugging is disabled, the HW registers do not work on a real gba or anything that is not mgba.

2022-09-05 01:24 UTC, SBird1337 commented on src/mgba_printf/mgba.c
> +void MgbaAssert(const char *pFile, s32 nLine, const char *pExpression, bool32 nStopProgram)
this should be optional and stubbed if mgba debugging is disabled, the HW registers do not work on a real gba or anything that is not mgba.

2022-09-05 01:24 UTC, SBird1337 commented on src/mgba_printf/mgba.c
> +void MgbaPrintEncoded(s32 level, const char *encodedString)
If a pretty printing argument is provided we do not need this function

2022-09-05 01:47 UTC, closed without merging