Improve psycho cut anim
rh-hideout/pokeemerald-expansion pull request #2390
Opened 2022-10-16 23:21 UTC by ghoulslash

Before it was very rigid. I added some movement and the cross impact at the end:

![psychoccut](https://user-images.githubusercontent.com/41651341/196063599-bddc7832-ac1d-4267-b5fe-c42b6a5f3446.gif)

2022-10-16 23:25 UTC, AsparagusEduardo commented
Yes it was :P
![psycho_old](https://user-images.githubusercontent.com/2904965/196063763-bf194a08-9ce6-4bf2-a3d9-079705cee628.gif)

2022-10-16 23:29 UTC, AsparagusEduardo requested changes
Looks good, just needs to remove the trailing whitespaces

2022-10-17 03:39 UTC, ghoulslash commented
> Looks good, just needs to remove the trailing whitespaces

done

2022-10-17 03:40 UTC, AsparagusEduardo approved these changes

2022-10-17 03:41 UTC, merged