convert a few various to callnatives
rh-hideout/pokeemerald-expansion pull request #2465
Opened 2022-11-28 19:38 UTC by ghoulslash

Convert the following various to callnatives

- VARIOUS_SET_Z_EFFECT
- VARIOUS_TRY_SYMBIOSIS
- VARIOUS_CAN_TELEPORT
- VARIOUS_GET_BATTLER_SIDE
- VARIOUS_CHECK_PARENTAL_BOND_COUNTER

2023-02-16 09:14 UTC, Jaizu commented
Please fix conflicts.

2023-05-15 03:02 UTC, AsparagusEduardo commented
Please solve conflicts.

2023-05-15 18:10 UTC, ghoulslash commented
> Please solve conflicts.

Done

2023-05-15 18:24 UTC, equezada-jej commented
I know this was introduced later, but we should use `NATIVE_ARGS` ^^;

2023-05-15 18:29 UTC, LOuroboros commented
Also, instead of increasing `gBattlescriptCurrInstr` by arbitrary amounts, wouldn't it be better to do `gBattlescriptCurrInstr = cmd->nextInstr;`? :eyes:

2023-05-15 18:41 UTC, equezada-jej commented
> Also, instead of increasing `gBattlescriptCurrInstr` by arbitrary amounts, wouldn't it be better to do `gBattlescriptCurrInstr = cmd->nextInstr;`? 👀
> 
> **EDIT**: I know they're not arbitrary per se, but still. Is it not possible to do that in these cases?

This is part of what I mean by using `NATIVE_ARGS` ^^;

2023-05-15 18:45 UTC, AsparagusEduardo commented
> Also, instead of increasing `gBattlescriptCurrInstr` by arbitrary amounts, wouldn't it be better to do `gBattlescriptCurrInstr = cmd->nextInstr;`? 👀
> 
> **EDIT**: I know they're not arbitrary per se, but still. Is it not possible to do that in these cases?

This is part of what I mean by using `NATIVE_ARGS` ^^;

2023-05-15 19:07 UTC, ghoulslash commented
> I know this was introduced later, but we should use `NATIVE_ARGS` ^^;

good call. just updated with them. The SetZEffect one still uses the old method but is a special case. would probably need a separate PR to clean it up if we wanted to down the line.

2023-05-15 19:14 UTC, AsparagusEduardo requested changes

2023-05-15 19:14 UTC, AsparagusEduardo commented on src/battle_script_commands.c
> +
please remove trailing whitespace.

2023-05-15 19:14 UTC, AsparagusEduardo commented on src/battle_script_commands.c
>  // 10 bytes long (callnative(5) + counter(1) + ptr(4))
Comment no longer needed.

2023-05-15 19:14 UTC, AsparagusEduardo commented on src/battle_script_commands.c
>  // 6 bytes long (callnative(5) + battler(1))
Comment no longer needed.

2023-05-15 19:20 UTC, ghoulslash commented
ready for review

2023-05-15 19:27 UTC, AsparagusEduardo approved these changes

2023-05-15 19:34 UTC, merged