Generation IX Moves
rh-hideout/pokeemerald-expansion pull request #2467
Opened 2022-12-01 21:00 UTC by Bassoonian

Updates the PLA moves to SV standards and adds data for the new generation IX moves.

## Description
Some moves are marked as requiring a new flag that Lunos implemented as part of his gen 9 ability branch. They need to be uncommented to work. A bunch of moves are still missing custom effects because I'm not familiar enough with the battle codebase to do all of them myself and none of them have animations. Double Shock needs the correct string (it has a placeholder one because I couldn't find the one the game used and I didn't have time to test yet).

## **Discord contact info**
Jasper#5206

2022-12-03 16:17 UTC, AsparagusEduardo requested changes
I can't test in-battle effects as I haven't progressed much in the game yet, so I'll leave that part for @ghoulslash to review :eyes:

2022-12-03 16:17 UTC, AsparagusEduardo commented on src/data/text/move_descriptions.h
> +    "strikes every turn.");
```suggestion
    "Summons a snowstorm that\n"
    "lasts for five turns.");
```

2022-12-03 16:17 UTC, AsparagusEduardo commented on src/data/text/move_descriptions.h
> +    "through a foe's Protect.");
```suggestion
    "A spinning pointed part\n"
    "bypasses a foe's Protect.");
```

2022-12-03 16:17 UTC, AsparagusEduardo commented on src/data/text/move_descriptions.h
> +    "eyes hit twice in a row.");
```suggestion
    "Mystical eye-beams that hit\n"
    "the target twice in a row.");
```

2022-12-03 16:17 UTC, AsparagusEduardo commented on src/data/text/move_descriptions.h
> +    "the stronger the move.");
```suggestion
    "The more the user has been\n"
    "hit, the stronger the move.");
```

2022-12-03 16:22 UTC, AsparagusEduardo commented on src/data/text/move_descriptions.h
> +    "and always lands a critical hit.");
Updated suggestion, as I thought it was a bit confusing.

2022-12-03 19:49 UTC, AsparagusEduardo commented on include/config.h
> +#define GEN_LATEST GEN_9
Or at least until we have implemented enough significant changes to justify start having Gen 9 as the new standard.

2022-12-03 19:55 UTC, AsparagusEduardo commented
One more thing, remember to update `B_METRONOME_MOVES`.

2022-12-04 17:13 UTC, Bassoonian commented on src/battle_tv.c
> +    [EFFECT_SPECIAL_ATTACK_UP_HIT] = 1,
We don't, but considering that the two new added things are equivalents of mechanics already present in Gen3, I included them out of analogy. I can remove them if you prefer

2022-12-04 20:59 UTC, Bassoonian commented
Updated flags and addressed Eduardo's concerns/comments. It's still a bit unclear which moves are forbidden by Metronome, Sleep Talk, Instruct etc. so that data still needs to be added in later once there's more clarity

2022-12-11 19:47 UTC, ghoulslash approved these changes

2022-12-11 19:47 UTC, merged