Ability popup updates
rh-hideout/pokeemerald-expansion pull request #2586
Opened 2023-01-21 17:27 UTC by Jaizu

## Description
Fixes #2374
Allows larger Pokémon/Nickname names
Small cleanup and documentation

## **Discord contact info**
Jaizu#0001

2023-01-21 18:18 UTC, LOuroboros requested changes

2023-01-21 18:18 UTC, LOuroboros commented on src/battle_interface.c
> +	.priority = 0,
Tabs to spaces.

2023-01-21 18:18 UTC, LOuroboros commented on src/battle_interface.c
> +#define ABILITY_POP_UP_POS_X_DIFF (64 - 7) //Hide second sprite underneath to gain proper letter spacing
```suggestion
#define ABILITY_POP_UP_POS_X_DIFF (64 - 7) // Hide second sprite underneath to gain proper letter spacing
```

2023-01-21 18:18 UTC, LOuroboros commented on src/battle_interface.c
> +    //Make the string say "[NAME]'s" instead of "[NAME]"
```suggestion
    // Make the string say "[NAME]'s" instead of "[NAME]"
```

2023-01-21 18:18 UTC, LOuroboros commented on src/battle_interface.c
> +    //{PIXEL_COORDS_TO_OFFSET(8, 48), 8},
```suggestion
```

2023-01-21 18:18 UTC, LOuroboros commented on src/battle_interface.c
> +    //{PIXEL_COORDS_TO_OFFSET(16, 48), 8},
```suggestion
```

2023-01-21 18:18 UTC, LOuroboros commented on src/battle_interface.c
> +								coords[battlerPosition][1], 1); //Appears below
Tabs to spaces.

2023-01-21 18:18 UTC, LOuroboros commented on src/battle_interface.c
> +								coords[battlerPosition][1], 1); //Appears below
Tabs to spaces.

2023-01-21 18:18 UTC, LOuroboros commented on src/battle_interface.c
> +
Tabs to spaces.

2023-01-21 18:25 UTC, Jaizu commented
Applied all the feedback.

2023-01-23 20:34 UTC, AsparagusEduardo approved these changes

2023-01-23 20:34 UTC, merged