Implement Destiny Knot
rh-hideout/pokeemerald-expansion pull request #2616
Opened 2023-01-29 18:36 UTC by Jaizu

## Description
Implements Destiny Knot daycare effect

## **Discord contact info**
Jaizu#0001

2023-01-30 23:29 UTC, AsparagusEduardo requested changes

2023-01-30 23:29 UTC, AsparagusEduardo commented on src/daycare.c
> -    u8 selectedIvs[INHERITED_IV_COUNT];
Since you're no longer using `INHERITED_IV_COUNT`, it should be deleted.

2023-01-30 23:29 UTC, AsparagusEduardo commented on src/daycare.c
> +    InheritIVs(&egg, daycare, &daycare->mons[parentSlots[1]].mon, &daycare->mons[parentSlots[0]].mon);
`daycare` is being passed already, so there's no need to pass the individual parents, like in `AlterEggSpeciesWithIncenseItem`.

2023-01-31 08:47 UTC, Jaizu commented
Thanks for the review, applied all the feedback.
Ready for re-review.

2023-01-31 10:42 UTC, AsparagusEduardo approved these changes

2023-01-31 10:43 UTC, merged