Illusion [WIP]
rh-hideout/pokeemerald-expansion pull request #2639
Opened 2023-02-06 20:49 UTC by DizzyEggg

2023-02-07 19:44 UTC, Jaizu commented
If this is not a draft anymore restore Lotad abilities :D

2023-02-13 09:29 UTC, Jaizu requested changes

2023-02-13 09:29 UTC, Jaizu commented on src/data/pokemon/species_info.h
> +        .abilities = {ABILITY_ILLUSION, ABILITY_ILLUSION},
You should avoid submiting changes that you made for testing.
Also, revert since it's not a draft anymore o/

2023-02-13 09:32 UTC, sphericalice commented on src/battle_util.c
> +    return 0;
```suggestion
    return SPECIES_NONE;
```

2023-02-16 21:37 UTC, DizzyEggg commented
Ready for review

2023-02-17 13:12 UTC, Jaizu approved these changes

2023-02-19 11:05 UTC, merged