Replace launchtemplate and launchtask in battle anims
rh-hideout/pokeemerald-expansion pull request #2640
Opened 2023-02-06 23:13 UTC by ghoulslash

Adding python script to replace `launchtemplate` with `createsprite`. Same with launchtask and createvisualtask

ANIM_PAL uses have also been removed in favor the pret's F_PAL_xx macros

2023-02-08 08:00 UTC, SBird1337 submitted a review, later dismissed
if the script is a one time thing we should probably not have it in the upstream tree.

2023-02-08 13:46 UTC, ghoulslash commented
> if the script is a one time thing we should probably not have it in the upstream tree.

removed script. also replaced launchtask with createvisualtask and fixed conflicts. ready for review

2023-02-17 14:57 UTC, DizzyEggg requested changes

2023-02-18 14:18 UTC, ghoulslash commented on asm/macros/battle_anim_script.inc
>  .macro setblends setblends_value
> Why not get rid of the setblends and launchsoundtask macros as well?

done

2023-02-19 10:38 UTC, DizzyEggg submitted a review, later dismissed

2023-05-27 21:28 UTC, AsparagusEduardo approved these changes

2023-05-27 21:32 UTC, merged