Fixed Grassy Terrain not healing + Added To-Do test results
rh-hideout/pokeemerald-expansion pull request #2857
Opened 2023-03-24 01:36 UTC by AsparagusEduardo

## Description
I didn't feel like adding more than the needed test to fix Grassy Terrain, so I added a way to have test placeholders instead.

## **Discord contact info**
AsparagusEduardo#6051

2023-03-24 13:08 UTC, ghoulslash requested changes

2023-03-24 13:08 UTC, ghoulslash commented on src/battle_util.c
> +        if (terrainFlag == STATUS_FIELD_GRASSY_TERRAIN)
& STATUS_FIELD_GRASSY

2023-03-24 13:23 UTC, AsparagusEduardo commented
Changes applied. Ready for re-review.

2023-03-26 11:25 UTC, ghoulslash approved these changes
fix conflicts

2023-03-26 19:16 UTC, AsparagusEduardo commented
Conflict solved.

2023-03-26 19:18 UTC, ghoulslash approved these changes

2023-03-26 19:18 UTC, merged