Reusable TMs
rh-hideout/pokeemerald-expansion pull request #2903
Opened 2023-04-12 15:05 UTC by Bassoonian

A quick and straightforward way to make TMs reusable by assigning them an importance value of 1. Any TM that does not have this importance value functions as expected. Item removal after teaching a move is no longer based on item ID but rather on importance now. A gen-based config has been added for easy toggling for now, but perhaps a plain TRUE/FALSE config would be more straightforward to use.

This PR does NOT include retaining PP of the older move when a new one is taught, as is the case in the official games. This mechanic would also affect the move relearner if it can be accessed from the party menu and should perhaps evaluate a different config.

## **Discord contact info**
Jasper#5206

2023-04-12 15:17 UTC, LOuroboros commented
> This PR does NOT include retaining PP of the older move when a new one is taught

You *could* include it though. There kind of isn't a reason not to, it's quick and it'd save the trouble of having to submit it in a separate PR, not to mention it's obviously related to the action of making TMs reusable.

In `include/config/item.h`
```
#define I_TMS_RESTORE_PP          TRUE  // If TRUE, TMs will teach a move at full PP.
```

In `src/party_menu.c`, I think modifying `Task_PartyMenuReplaceMove` like this would be good enough, and makes the function more readable too *imo*.
```c
 static void Task_PartyMenuReplaceMove(u8 taskId)
 {
     struct Pokemon *mon = &gPlayerParty[gPartyMenu.slotId];
     u16 move = gPartyMenu.data1;
     u8 oldPP = GetMonData(mon, MON_DATA_PP1 + GetMoveSlotToReplace(), NULL);
 
     if (IsPartyMenuTextPrinterActive() != TRUE)
     {
         RemoveMonPPBonus(mon, GetMoveSlotToReplace());
         SetMonMoveSlot(mon, move, GetMoveSlotToReplace());
     #if I_TMS_RESTORE_PP == TRUE
         if (GetMonData(mon, MON_DATA_PP1 + GetMoveSlotToReplace(), NULL) > oldPP)
             SetMonData(mon, MON_DATA_PP1 + GetMoveSlotToReplace(), &oldPP);
     #endif
         Task_LearnedMove(taskId);
     }
 }
```

2023-04-12 20:33 UTC, Bassoonian commented
Ready for re-review. Doesn't include the PP restoration thing because tasks and my lack of expertise in regards to them.

2023-04-17 02:24 UTC, AsparagusEduardo requested changes

2023-04-17 02:24 UTC, AsparagusEduardo commented on include/config/item.h
> +#define I_REUSABLE_TMS          TRUE        // In Generations 5 to 8, TMs are reusable. If this config is on, TRs can be made by removing the importance field from TMs.
```suggestion
#define I_REUSABLE_TMS          FALSE       // In Gen5-8, TMs are reusable. Setting this to TRUE will make all vanilla TMs reusable, though they can also be cherry-picked by setting their importance to 1.
```

2023-04-18 23:51 UTC, AsparagusEduardo approved these changes

2023-04-18 23:52 UTC, merged