Add Frostbite status
rh-hideout/pokeemerald-expansion pull request #2942
Opened 2023-04-22 16:30 UTC by Bassoonian

Adds Frostbite as status next to Freeze.

## Description
WIP, will be expanded upon once it's more complete

## Images
![pokeemerald 2023-04-22 18 28 18](https://user-images.githubusercontent.com/16993385/233795946-60c0db16-7069-4584-bfd1-098ee12e099f.png)
![pokeemerald 2023-04-22 18 29 23](https://user-images.githubusercontent.com/16993385/233795947-bd19a1a7-2d66-4ab7-95f2-8c376d96de92.png)
![pokeemerald 2023-04-22 18 29 31](https://user-images.githubusercontent.com/16993385/233795948-fecf90ea-5ad0-4e00-a5ff-a826cd9861e1.png)

## Task list

- [x] Add status to the game
- [ ] Make it function in-battle
- [ ] Allow it to be healed with items/abilities/moves
- [ ] Allow it to be inflicted with relevant configs
- [ ] Include other interactions with items/abilities/moves
- [ ] Integrate AI interactions with this status

## **Discord contact info**
Jasper#5206

2023-04-23 19:27 UTC, Bassoonian commented
Ready for review! This still needs extensive testing and the `ITEM_CURE_EFFECT_FREEZE` issue still needs to be addressed, but I personally have no clue how. If someone has a solution (we should wait for that before merging it probably), please feel free to PR it!

We'll probably need tests to be written too, but as previously mentioned on Discord, I use OSX and can't do it myself.

2023-04-24 08:34 UTC, CallmeEchoo commented on include/battle_ai_util.h
>  #endif //GUARD_BATTLE_AI_UTIL_H
```suggestion
void IncreaseSleepScore(u8 battlerAtk, u8 battlerDef, u16 move, s16 *score);
void IncreaseConfusionScore(u8 battlerAtk, u8 battlerDef, u16 move, s16 *score);
void IncreaseFrostbiteScore(u8 battlerAtk, u8 battlerdef, u16 move, s16 *score);

#endif //GUARD_BATTLE_AI_UTIL_H

```

2023-04-25 17:51 UTC, Bassoonian commented
This should now be bugfree and behaviour should be as expected. Further testing is obviously recommended. Written tests would also be welcome if deemed necessary as I can't do them myself (see above).

2023-04-28 11:31 UTC, Bassoonian commented
Ready for re-review, now with tests and no more bugs!

2023-04-30 09:35 UTC, Jaizu commented
Please give proper credits for fixing the status icons. I know RHH doesn't have a proper credits list yet (it should) but there is no harm into adding the credits into the PR or commit name.

2023-04-30 09:37 UTC, Bassoonian commented
I attempted to add you as co-author to the commit, but it doesn't seem to have worked. I also mentioned you on the RHH Discord when I mentioned the fix:
![image](https://user-images.githubusercontent.com/16993385/235346285-d645df9e-5270-4e0c-88a7-511efe77fa04.png)

2023-04-30 09:49 UTC, Jaizu commented
That sounds good enough to me o/

2023-04-30 11:28 UTC, floodryan commented
Ive been looking to do this for a while. Is it available to add now? Also would it be hard to merge this with an existing project

2023-04-30 11:36 UTC, LOuroboros commented
> Is it available to add now?

It's code, and it's all here, so yes.

If you mean if it's available officially, then the answer is "No." though. As you can see above, this PR is still Open and not Merged.

> Also would it be hard to merge this with an existing project

It depends on whether said project uses the expansion and whether it's kept up-to-date or not.

You're better off pulling the branch that was submitted in this PR and solving the merge conflicts, or alternatively implement the changes manually as they're shown in the Files Changed tab.

Also, for future reference, keep any support questions in the Discord server. The only discussions that should take place here are those that concern the PR itself and the changes it makes with the goal of getting it reviewed, approved and merged.

2023-04-30 15:04 UTC, ghoulslash requested changes

2023-05-01 09:08 UTC, Bassoonian commented on src/battle_ai_util.c
> +    if (ability == ABILITY_MAGMA_ARMOR
I assume that means that `AI_CanBeBurned` is also missing the Comatose check?

2023-05-01 09:12 UTC, Bassoonian commented on src/battle_script_commands.c
> +            if (!CanBeFrozen(gEffectBattler))
Good one! I can't find any information about interactions between sunlight and frostbite, so I assume weather has nothing to do with whether or not a Pokémon can get Frostbite. I'll fix it, thanks!

2023-05-01 13:04 UTC, ghoulslash commented on src/battle_ai_util.c
> +    if (ability == ABILITY_MAGMA_ARMOR
Yeah if it missing a comatose check that should be added (may as well on this PR if you have other edits to make)

2023-05-01 13:35 UTC, Bassoonian commented on src/battle_ai_util.c
> +    if (ability == ABILITY_MAGMA_ARMOR
Added the Comatose check to some other status checks too while I was at it :)

2023-05-01 13:43 UTC, ghoulslash approved these changes

2023-05-01 13:45 UTC, merged