Fixes Triple Dive effect
rh-hideout/pokeemerald-expansion pull request #2947
Opened 2023-04-23 22:50 UTC by AlexOn1ine

## Description
Fixes Triple Dive effect by adding `FLAG_THREE_STRIKES`. The flag is additionally used for Surging Strikes. 

## Images
Triple Dive:
![triple_dive](https://user-images.githubusercontent.com/93446519/233870311-b296b4be-0760-4a49-adae-8be46109898b.gif)
Surging Strikes:
![surging_strikes](https://user-images.githubusercontent.com/93446519/233870320-fbeecc91-8a31-414e-b2e2-d5f2651d5d30.gif)

## Issue(s) that this PR fixes
Fixes #2795

## **Discord contact info**

2023-04-24 01:13 UTC, AsparagusEduardo commented on src/battle_util.c
> +            else if (gBattleMoves[gCurrentMove].flags & FLAG_THREE_STRIKES)
I think this breaks Triple Kick/Axel.

2023-04-24 07:04 UTC, AlexOn1ine commented on src/battle_util.c
> +            else if (gBattleMoves[gCurrentMove].flags & FLAG_THREE_STRIKES)
Fixed + added a couple tests

2023-04-24 23:00 UTC, AsparagusEduardo requested changes

2023-04-24 23:00 UTC, AsparagusEduardo commented on test/move_flag_three_strikes.c
> +SINGLE_BATTLE_TEST("Three Strikes on Surging Strikes do critical damage")
```suggestion
SINGLE_BATTLE_TEST("Surging Strikes hits 3 times with each hit being a critical hit")
```

2023-04-25 17:49 UTC, AlexOn1ine commented
Applied suggestions.

2023-05-02 19:06 UTC, AsparagusEduardo approved these changes

2023-05-02 19:06 UTC, merged