Fix for burn up/double shock
rh-hideout/pokeemerald-expansion pull request #2962
Opened 2023-04-28 21:42 UTC by AlexOn1ine

## Description
Fixes Burn Up and Double Shock not losing the typing when a target is killed and  double pp consumption when used.

## Images
![double_shock](https://user-images.githubusercontent.com/93446519/235258961-45d85f79-6453-415e-9a76-d1d4c1627174.gif)

## Issue(s) that this PR fixes
Fixes #2961, Fixes #2960

## **Discord contact info**
AlexOnline#2331

2023-04-29 22:46 UTC, AsparagusEduardo requested changes

2023-04-29 22:46 UTC, AsparagusEduardo commented on test/move_effect_burn_up.c
> +SINGLE_BATTLE_TEST("Burn Up user loses it's typing", s16 damage)
```suggestion
SINGLE_BATTLE_TEST("Burn Up user loses its Fire typing", s16 damage)
```

2023-04-29 22:46 UTC, AsparagusEduardo commented on test/move_effect_burn_up.c
> +SINGLE_BATTLE_TEST("Burn Up user loses it's typing if enemy faints", s16 damage)
```suggestion
SINGLE_BATTLE_TEST("Burn Up user loses its Fire typing if enemy faints", s16 damage)
```

2023-04-29 22:46 UTC, AsparagusEduardo commented on test/move_effect_burn_up.c
> +}
Needs the assumption that Cyndaquil is a fire type and that Wobbuffet is not.

2023-04-29 22:46 UTC, AsparagusEduardo commented on test/move_effect_double_shock.c
> +SINGLE_BATTLE_TEST("Double Shock user loses it's typing", s16 damage)
```suggestion
SINGLE_BATTLE_TEST("Double Shock user loses its Electric typing", s16 damage)
```

2023-04-29 22:46 UTC, AsparagusEduardo commented on test/move_effect_double_shock.c
> +}
Needs the assumption that Pikachu is an Electric type and that Wobbuffet is not.

2023-04-29 22:46 UTC, AsparagusEduardo commented on test/move_effect_double_shock.c
> +SINGLE_BATTLE_TEST("Double Shock user loses it's typing if enemy faints", s16 damage)
```suggestion
SINGLE_BATTLE_TEST("Double Shock user loses its Electric typing if enemy faints", s16 damage)
```

2023-04-29 22:46 UTC, AsparagusEduardo commented on test/move_effect_double_shock.c
> +SINGLE_BATTLE_TEST("Double Shock fails if the user isn't a fire type", s16 damage)
```suggestion
SINGLE_BATTLE_TEST("Double Shock fails if the user isn't an Electric-type", s16 damage)
```

2023-04-29 22:46 UTC, AsparagusEduardo commented on test/move_effect_burn_up.c
> +SINGLE_BATTLE_TEST("Burn Up fails if the user isn't a fire type", s16 damage)
```suggestion
SINGLE_BATTLE_TEST("Burn Up fails if the user isn't a Fire-type", s16 damage)
```

2023-04-30 08:38 UTC, AlexOn1ine commented
Applied all suggestions.

2023-04-30 14:45 UTC, AsparagusEduardo approved these changes

2023-04-30 14:46 UTC, merged