add opportunist
rh-hideout/pokeemerald-expansion pull request #2994
Opened 2023-05-11 17:13 UTC by ghoulslash

Now that mirror herb is merged, adding opportunist was relatively similar.

![opportunist](https://github.com/rh-hideout/pokeemerald-expansion/assets/41651341/699b8ad2-9793-44b2-9048-4d7890d95d1d)

I needed to add a new MOVEEND_ case and ABILITYEFFECT_ case because we needed all other ability, item, etc moveend effects to occur first. This might not be the right approach though. Would need to think if there's a simpler way to handle this. But I made the gTotemBoosts statValue setting a cumulative effect, so if two opponents have e.g. intrepid sword, the opportunist mon will get a sharp attack boost (see below) - This needs more research as far as official mechanics. Would opportunist trigger after each individual intrepid sword?

![opportunist_2](https://github.com/rh-hideout/pokeemerald-expansion/assets/41651341/b51fefa8-89c4-4143-b3ce-b83f468eb82e)

TODOs:
- need battle tests

2023-06-03 18:52 UTC, AgustinGDLV reviewed
Looks great on my local branch! I'm a little put off by `gTotemBoosts` staying the name for Mirror Herb and Opportunist cases. I think it's fine that we're reusing it, and I understand that this was already approved for Mirror Herb, so I'll let you decide if it should be changed to something a bit more accurate. I can only think of something like `gQueuedStatBoosts`, but that might be a bit misleading, too. 

![Illegal Ability Tests](https://github.com/rh-hideout/pokeemerald-expansion/assets/103095241/6a8607bb-be9c-4d15-952c-789be762662a)

2023-06-06 14:14 UTC, AsparagusEduardo commented
I agree, `gQueuedStatBoosts` would be a better name for the field now that it's used for other stuff than Totem boosts.

2023-06-16 15:08 UTC, ghoulslash commented
> I agree, `gQueuedStatBoosts` would be a better name for the field now that it's used for other stuff than Totem boosts.

Done

2023-06-21 17:37 UTC, AsparagusEduardo commented
Can you merge with upcoming so that it passed the checks thanks to #3045?

2023-06-28 01:27 UTC, AsparagusEduardo commented
It's failing due to a different reason 👀

2023-09-25 20:21 UTC, ghoulslash commented
branch updated and test fixed.ready for re-review

2023-09-25 21:41 UTC, DizzyEggg reviewed
Just a comment for now. 
Would you mind creating a test for Opportunist in a double battle where partner has Intimidate, but one of the foes has Contrary, so its Attack rises. This seems like an edge case that could explode, but if it works, then I'd feel pretty comfortable merging it.

2023-09-28 00:52 UTC, ghoulslash commented
> Just a comment for now. 
> Would you mind creating a test for Opportunist in a double battle where partner has Intimidate, but one of the foes has Contrary, so its Attack rises. This seems like an edge case that could explode, but if it works, then I'd feel pretty comfortable merging it.

As per issue #3356 that given test will fail but not because of opportunist. Do we want to make the test now or add it to whichever PR fixes the bug?

2023-09-28 05:03 UTC, mrgriffin commented
> As per issue #3356 that given test will fail but not because of opportunist. Do we want to make the test now or add it to whichever PR fixes the bug?

I would add it now, but marked with [`KNOWN_FAILING`](<https://github.com/rh-hideout/pokeemerald-expansion/blob/master/include/test/battle.h#L202>).

2023-09-30 22:17 UTC, AsparagusEduardo requested changes

2023-09-30 22:17 UTC, AsparagusEduardo commented on test/battle/ability/opportunist.c
> +    ASSUME(gSpeciesInfo[SPECIES_WOBBUFFET].abilities[2] == ABILITY_OPPORTUNIST);
Let's not add false assumptions ^^;

2023-09-30 22:17 UTC, AsparagusEduardo commented on test/battle/ability/opportunist.c
> +}
```suggestion
}

TO_DO_BATTLE_TEST("Opportunist doesn't copy ally stat increases");
TO_DO_BATTLE_TEST("Opportunist doesn't copy foe stat increases gained via Opportunist");
TO_DO_BATTLE_TEST("Opportunist copies foe stat increased gained via Swagger and Flatter");
```

2023-10-06 14:00 UTC, ghoulslash commented
Added contrary + intimidate + opportunist test. ready to review

2023-10-06 18:53 UTC, AsparagusEduardo requested changes

2023-10-06 18:53 UTC, AsparagusEduardo commented on test/battle/ability/opportunist.c
> +        EXPECT_EQ(opponentRight->statStages[STAT_ATK], (abilityRight == ABILITY_CONTRARY) ? DEFAULT_STAT_STAGE+1 : DEFAULT_STAT_STAGE-1);
```suggestion
        EXPECT_EQ(opponentLeft->statStages[STAT_ATK],  (abilityLeft == ABILITY_CONTRARY)  ? DEFAULT_STAT_STAGE + 1 : DEFAULT_STAT_STAGE - 1);
        EXPECT_EQ(opponentRight->statStages[STAT_ATK], (abilityRight == ABILITY_CONTRARY) ? DEFAULT_STAT_STAGE + 1 : DEFAULT_STAT_STAGE - 1);
```

2023-10-10 01:33 UTC, AsparagusEduardo approved these changes

2023-10-10 01:35 UTC, merged