Optimized battle gender checks
rh-hideout/pokeemerald-expansion pull request #3020
Opened 2023-05-21 05:21 UTC by AsparagusEduardo

## Description
Aka: Edu's PR Idea N°1 for when he had to rest his hands.

## **Discord contact info**
AsparagusEduardo#6051

2023-05-26 01:56 UTC, AgustinGDLV requested changes
I can't really find anything I'd want to change other than `u8` to `bool8` for `AreBattlersOfSameGender`. Really nice change, makes everything way more readable!

2023-05-26 01:56 UTC, AgustinGDLV commented on src/battle_util.c
> +u8 AreBattlersOfOppositeGender(u8 battler1, u8 battler2)
```suggestion
bool8 AreBattlersOfOppositeGender(u8 battler1, u8 battler2)
```

2023-05-26 01:56 UTC, AgustinGDLV commented on include/battle_util.h
> +u8 AreBattlersOfOppositeGender(u8 battler1, u8 battler2);
```suggestion
bool8 AreBattlersOfOppositeGender(u8 battler1, u8 battler2);
```

2023-05-27 17:09 UTC, AsparagusEduardo commented
> `AreBattlersOfSameGender`

By this mean that I should rename `AreBattlersOfOppositeGender`?

2023-05-27 17:15 UTC, AgustinGDLV commented
> > `AreBattlersOfSameGender`
> 
> By this mean that I should rename `AreBattlersOfOppositeGender`?

No I just can't read.

2023-05-27 17:36 UTC, AgustinGDLV approved these changes

2023-05-27 21:23 UTC, merged