Gender differences sprites, part 1
rh-hideout/pokeemerald-expansion pull request #3070
Opened 2023-06-22 15:40 UTC by SubzeroEclipse

## Description
First PR that adds sprites for some Pokémon with gender based differences, namely:
- Pikachu/Raichu
- Gloom/Vileplume
- Doduo/Dodrio
- Goldeen/Seaking
- Xatu
- Politoed
- Meditite/Medicham
- Gible/Gabite/Garchomp

Pikachu and Gloom's back sprites were taken from [Chaos Rush's resource](https://www.pokecommunity.com/showthread.php?t=267728); Pikachu's front was done by CyanSixFour.

## **Discord contact info**
SubzeroEclipse#2104

2023-06-22 15:49 UTC, AsparagusEduardo requested changes

2023-06-22 15:49 UTC, AsparagusEduardo commented on src/data/pokemon/species_info.h
> +        .flags = SPECIES_FLAG_GENDER_DIFFERENCE,                           \
Adding this in the macro will cause *all* Pikachu forms to be counted as having gender differences, which is not the case.

2023-06-23 06:08 UTC, SubzeroEclipse commented
Fixed and ready for review

2023-06-26 13:54 UTC, AsparagusEduardo requested changes
Looks good in-game, though #3051 made us realize that bit depths for some sprites were wrong.
You'll need to solve conflicts and fix the bit depths of the following sprites due to them being copied from the erroneous previous depths:
- Front Female Dodrio
- Front Female Xatu

2023-06-26 18:29 UTC, SubzeroEclipse commented
Ready for re-review! Fixed conflicts and Dodrio/Xatu sprites and swapped sprites as discussed on Discord

2023-06-26 23:03 UTC, AsparagusEduardo approved these changes

2023-06-26 23:04 UTC, merged