Fixed outstanding null dereferencing errors with -fanalyzer on modern
rh-hideout/pokeemerald-expansion pull request #3165
Opened 2023-07-21 20:26 UTC by gruxor

## Description
After this, all that stderr outputs are some palette issues with some item sprites that I'll PR later tonight probably.

There may still be additional fixes needed for other arguments that MGriffin was toying around with, but I think this is a good start and gets the core issues out of the way.

The change that looks big is the one in pokemon.c, but it's relatively simple - just separates the encrypted and unencrypted boxmon data behind an if/else instead of just playing fast and loose with the substruct pointers. The rest is relatively simple, but some of it revolves around some messy derefencing that we could clean up a bit better eventually. For the time being, some of these just check for null in the critical sections and output a warning via debug logging, which is at least safer than previously and keeps the analyzer off our backs.

I did some minimal testing, but let me know if you spot any issues.

## **Discord contact info**
crater.

2023-07-22 00:09 UTC, LOuroboros requested changes

2023-07-22 00:09 UTC, LOuroboros commented on src/pokemon.c
> +                retVal = substruct0->ppBonuses;
The cases should be aligned with the opening parenthesis of the `switch` statement.

2023-07-22 00:09 UTC, LOuroboros commented on src/fieldmap.c
> +            DebugPrintfLevel(MGBA_LOG_WARN, "GetIncomingConnection returned an invalid connection inside CameraMove!");
```suggestion
            MoveMapViewToBackup(direction);
        }
        else
        {
            DebugPrintfLevel(MGBA_LOG_WARN, "GetIncomingConnection returned an invalid connection inside CameraMove!");
        }
```

2023-07-22 18:51 UTC, gruxor commented
@LOuroboros Fixed style issues as directed, should be good to go now.

2023-07-31 13:00 UTC, DizzyEggg approved these changes

2023-07-31 18:49 UTC, merged