Improve how AI chooses damaging moves
rh-hideout/pokeemerald-expansion pull request #3199
Opened 2023-08-03 17:09 UTC by DizzyEggg

Fixes #3130
Fixes #3153

The general flow should be like this(assuming there are no special effects which would otherwise be more preferable):
if can faint -> choose the move without side effects(e.g. recoil, recharge, loading turn), and with better accuracy(e.g. Tackle over Mega Punch if both are 1hko)
if can't faint -> choose the move which takes the least no of hits to KO, but only if the other move doesn't have any advantages(otherwise it's a toss-up and depends on the battle conditions).

Also fixed Taunt's score to be minus 10 and improved handling of Solar Beam.

Before:
![pokeemerald_01](https://github.com/rh-hideout/pokeemerald-expansion/assets/16259973/a641b6b0-be93-47ff-91f3-9bdec71747de)

![254561947-0587a7ef-6651-4172-ba75-3bda57df9eeb](https://github.com/rh-hideout/pokeemerald-expansion/assets/16259973/d09c2a36-c0d5-4926-b0a7-0f5869a3a59e)

After:
![pokeemerald_06](https://github.com/rh-hideout/pokeemerald-expansion/assets/16259973/3615c646-0d53-4a11-8553-c3b405a853d5)

![pokeemerald_08](https://github.com/rh-hideout/pokeemerald-expansion/assets/16259973/19cffca8-2ed1-4f1a-b26a-b48c68369cc4)

2023-08-03 18:02 UTC, AlexOn1ine commented
What do you think about removing this switch block?
```
        switch (AI_DATA->effectiveness[battlerAtk][battlerDef][AI_THINKING_STRUCT->movesetIndex])
        {
        case AI_EFFECTIVENESS_x8:
            score += 8;
            break;
        case AI_EFFECTIVENESS_x4:
            score += 4;
            break;
        case AI_EFFECTIVENESS_x2:
            if (AI_RandLessThan(176))
                score += 2;
            else
                score++;
            break;
        }
```
Your PR takes care of a lot of edge cases and this block looks seems unnecessary with it. You would just get score increases for the sake of increasing it.

2023-08-28 09:41 UTC, AlexOn1ine commented
I did some testing and my suggestion generally would be to only decrease the score when compare to a better move. 
The problem with increases is that it inflates the score which might render status move unusable.
An example with the current behavior of this PR
```
Good move, score 101
Bad Move, score 101 
Bad Move, score 101
Bad Move, score 101 
```
Let's say all moves have a score of 101 before their comparison.

2023-08-28 09:47 UTC, AlexOn1ine commented
I did some testing and my suggestion generally would be to only decrease the score when compare to a better move.
The problem with increases is that it inflates the score which might render status move unusable.
Let's say we have the base 
```
Good move, score 101
Bad Move, score 101 
Bad Move, score 101
Bad Move, score 101
```
If the comparison from this PR are applied it ends up like this
```
Good move, score 104
Bad Move, score 100 
Bad Move, score 100
Bad Move, score 100
```
My suggestion would be to decrease the bad moves only
```
Good move, score 101
Bad Move, score 100 
Bad Move, score 100
Bad Move, score 100
```
Same result but you don't inflate the score

2023-09-27 21:32 UTC, DizzyEggg commented
Despite the issue you Alex mentioned I still think this PR does more good than evil. Would it be fine to merge it to upcoming and then improve it? The thing is even if it's not perfect with this PR, it is _still_ worse without it. Also, I hope to have AI tests soon, so it'll be easier to catch these issues.

2023-09-29 08:13 UTC, DizzyEggg commented
@AsparagusEduardo Should be ready to merge.

2023-10-01 17:00 UTC, AsparagusEduardo requested changes

2023-10-01 17:04 UTC, DizzyEggg commented on src/battle_ai_main.c
> +    return 2;
Which constants?

2023-10-01 23:36 UTC, AsparagusEduardo approved these changes

2023-10-01 23:36 UTC, merged