Remove redundant side macros/funcs
rh-hideout/pokeemerald-expansion pull request #3201
Opened 2023-08-03 18:54 UTC by gruxor

## Description
Replaces GET_BATTLER_SIDE and GET_BATTLER_SIDE2 with the existing GetBattlerSide, which is now inlined. Also changes all instances of GetBattlerPosition with direct gBattlerPositions usage.

## **Discord contact info**
crater.

2023-08-03 18:57 UTC, mrgriffin requested changes

2023-08-03 19:22 UTC, DizzyEggg commented
Is removing GetBattlerPosition a good idea? I think it's more readable the way it is now. 
Also, if someone modified that function to behave differently, it's gonna be a problem.

I would personally make it an inline function like the rest.

2023-08-03 19:58 UTC, gruxor commented
> Is removing GetBattlerPosition a good idea? I think it's more readable the way it is now. Also, if someone modified that function to behave differently, it's gonna be a problem.
> 
> I would personally make it an inline function like the rest.

Re-added and applied everywhere, only uses of `gBattlerPositions` should be on assignments now. Mostly regex'd and then proofread by the compiler, so could use a manual look-through if someone wants to check over the changed instances.

2023-08-04 20:01 UTC, mrgriffin commented
I can try to review this later in the weekend/next week. If somebody else wants to get to it first they're more than welcome to and I can change my review to approve.

2023-09-05 07:41 UTC, DizzyEggg requested changes
Other than the weird extern and conflicts, I think this should be good to go.

2023-09-05 07:41 UTC, DizzyEggg commented on include/battle.h
> +    extern u8 GetBattlerSide(u8 battler);
Why is this extern needed here?

2023-09-14 12:11 UTC, DizzyEggg commented
Replaced by #3299

2023-09-14 12:11 UTC, closed without merging