Simplify/Clean battle controllers code
rh-hideout/pokeemerald-expansion pull request #3202
Opened 2023-08-04 19:49 UTC by DizzyEggg

As we are all aware of, battle controllers' code is one of GF's worst creations. The amount of duplicated code over the controllers files is truly unmatched. 

Goals of this PR:
- remove all of the duplicated code
- simplify to make the code easier to follow
- get rid of unused data and code

It's not yet done, but once it is, this should be thoroughly tested as I may accidentally omit something while copying the functions. Things to keep an eye on are link battles, multi battles, recorded battles and multi link battles as things may break the most there.

Suggestions and reviews are welcome.

2023-08-04 19:59 UTC, AsparagusEduardo commented
On one hand, I'm glad we're able to untangle this mess :D
On the other, I wonder if this will break the potential vanilla compatibility, as we've found out that it's actually surprisingly compatible due to all the logic and data being handled by a single game 👀

2023-08-04 20:05 UTC, DizzyEggg commented
> On one hand, I'm glad we're able to untangle this mess :D On the other, I wonder if this will break the potential vanilla compatibility, as we've found out that it's actually surprisingly compatible due to all the logic and data being handled by a single game 👀

I see no reason why the compatibility would be broken. I want the flow to remain the same, the difference being there is 1 function doing 1 thing, instead of 5 functions doing the same thing :D

2023-08-04 20:11 UTC, AsparagusEduardo commented
> I see no reason why the compatibility would be broken. I want the flow to remain the same, the difference being there is 1 function doing 1 thing, instead of 5 functions doing the same thing :D

Awesome, we're on the same league then :D

2023-08-07 11:28 UTC, DizzyEggg commented
Ready for review. I also updated the first post with some more information.

2023-08-07 20:09 UTC, DizzyEggg commented
> If it's not breaking, why does it have the `BREAKING` tag? 👀

You're right, I removed the tag.

2023-08-18 23:39 UTC, ghoulslash requested changes

2023-08-18 23:39 UTC, ghoulslash commented
I love this PR :)

2023-08-21 07:44 UTC, DizzyEggg commented on src/battle_controllers.c
> +void BtlController_HandleLoadMonSprite(u32 battler, struct Pokemon *party, void (*controllerCallback)(u32 battler))
fixed

2023-08-21 12:29 UTC, ghoulslash requested changes

2023-08-21 12:29 UTC, ghoulslash commented on src/battle_controllers.c
> +    struct Pokemon *party = GetBattlerParty(battler);
Actually I think we can just consolidate all of these GetBattlerParty and gBattlerPartyIndexes into just GetBattlerPartyData calls. Sorry I should have noticed earlier

2023-08-21 19:56 UTC, ghoulslash commented
It might also make sense to replace the gActiveBattler check in `PrepareBufferDataTransfer` with a battler argument, but that would require changing all battle controller emit function calls. But currently calling any of those without properly setting gActiveBattler can be problematic. especially since gActiveBattler is used a loop index in some places so can be set to gBattlersCount and therefore emitting data to that battler Id would result in bad UB

2023-08-22 18:08 UTC, DizzyEggg commented
> It might also make sense to replace the gActiveBattler check in `PrepareBufferDataTransfer` with a battler argument, but that would require changing all battle controller emit function calls. But currently calling any of those without properly setting gActiveBattler can be problematic. especially since gActiveBattler is used a loop index in some places so can be set to gBattlersCount and therefore emitting data to that battler Id would result in bad UB
> 
> edit: actually does this not break some implementations of calling BtlController_x inside the battle controller files since gActiveBattler is not explicitly set?

This should also be done, but I think this PR is big enough as it is. 
I don't think it should break anything, if the battler is provided via an argument instead of gActiveBattler.

2023-08-28 21:08 UTC, ghoulslash approved these changes
Alex confirmed link battles work, singles and doubles work as expected locally as well

2023-08-28 21:08 UTC, merged