Add support for legendary fusion
rh-hideout/pokeemerald-expansion pull request #3274
Opened 2023-09-03 02:57 UTC by kittenchilly

## Description
Picked up from #2621 with permission.
Adds the ability to use their respective items to fuse Kyurem, Necrozma, and Calyrex.
Fixes the animation and cleans up a bit from the previous PR.
Also adds a function to refresh the party menu on the fly, if that'd be useful anywhere else.

## Images

![fusion](https://github.com/rh-hideout/pokeemerald-expansion/assets/23617175/b67876e9-a69a-4d0b-b434-04b81edd5c0e)

## **Discord contact info**
kittenchilly

2023-09-08 03:54 UTC, AsparagusEduardo requested changes
This is an initial review, likely more to come.

Can you change the fade in from white instead of black when reloading the party screen after fusion/unfusion?

Also, I'm pretty sure we can have a single Fusion table that can handle all data.
```c
static const struct Fusion sFusions[] = {
    {0, ITEM_DNA_SPLICERS, SPECIES_KYUREM, SPECIES_RESHIRAM, SPECIES_KYUREM_WHITE},
    {0, ITEM_DNA_SPLICERS, SPECIES_KYUREM, SPECIES_ZEKROM, SPECIES_KYUREM_BLACK},
    {1, ITEM_N_SOLARIZER, SPECIES_NECROZMA, SPECIES_SOLGALEO, SPECIES_NECROZMA_DUSK_MANE, MOVE_SUNSTEEL_STRIKE, MOVE_CONFUSION},
    {2, ITEM_N_LUNARIZER, SPECIES_NECROZMA, SPECIES_LUNALA, SPECIES_NECROZMA_DAWN_WINGS, MOVE_MOONGEIST_BEAM, MOVE_CONFUSION},
    {3, ITEM_REINS_OF_UNITY, SPECIES_CALYREX, SPECIES_GLASTRIER, SPECIES_CALYREX_ICE_RIDER, MOVE_GLACIAL_LANCE, MOVE_CONFUSION},
    {3, ITEM_REINS_OF_UNITY, SPECIES_CALYREX, SPECIES_SPECTRIER, SPECIES_CALYREX_SHADOW_RIDER, MOVE_ASTRAL_BARRAGE, MOVE_CONFUSION},
```

2023-09-08 03:54 UTC, AsparagusEduardo commented on src/data/pokemon/form_change_table_pointers.h
> +};
New line at the end of file

2023-09-08 03:54 UTC, AsparagusEduardo commented on include/pokemon_storage_system.h
> +#define MAX_FUSION_STORAGE      5
`FusionStorageIndex` doesn't return 4, so there's no point on reserving space for a 5th slot.

2023-09-08 16:39 UTC, kittenchilly commented
> Also, I'm pretty sure we can have a single Fusion table that can handle all data.

I wouldn't be able to separate stuff by gen config then.

2023-09-08 16:42 UTC, kittenchilly commented
> Can you change the fade in from white instead of black when reloading the party screen after fusion/unfusion?

I don't think I can change it to white due to how it reloads by clearing all sprites... I can make it fade to black instead though

2023-09-08 16:51 UTC, AsparagusEduardo commented
> > Also, I'm pretty sure we can have a single Fusion table that can handle all data.
> 
> I wouldn't be able to separate stuff by gen config then.

https://www.youtube.com/watch?v=kcc9hXWLDbI
```diff
+#define FUSION_TERMINATOR                  0xFF
static const struct Fusion sFusions[] = {
+#if P_GEN_5_POKEMON == TRUE
    {0, ITEM_DNA_SPLICERS,   SPECIES_KYUREM,   SPECIES_RESHIRAM,  SPECIES_KYUREM_WHITE},
    {0, ITEM_DNA_SPLICERS,   SPECIES_KYUREM,   SPECIES_ZEKROM,    SPECIES_KYUREM_BLACK},
+#endif
+#if P_GEN_7_POKEMON == TRUE
    {1, ITEM_N_SOLARIZER,    SPECIES_NECROZMA, SPECIES_SOLGALEO,  SPECIES_NECROZMA_DUSK_MANE,   MOVE_SUNSTEEL_STRIKE, MOVE_CONFUSION},
    {2, ITEM_N_LUNARIZER,    SPECIES_NECROZMA, SPECIES_LUNALA,    SPECIES_NECROZMA_DAWN_WINGS,  MOVE_MOONGEIST_BEAM,  MOVE_CONFUSION},
+#endif
+#if P_GEN_8_POKEMON == TRUE
    {3, ITEM_REINS_OF_UNITY, SPECIES_CALYREX,  SPECIES_GLASTRIER, SPECIES_CALYREX_ICE_RIDER,    MOVE_GLACIAL_LANCE,   MOVE_CONFUSION},
    {3, ITEM_REINS_OF_UNITY, SPECIES_CALYREX,  SPECIES_SPECTRIER, SPECIES_CALYREX_SHADOW_RIDER, MOVE_ASTRAL_BARRAGE,  MOVE_CONFUSION},
+#endif
+   {FUSION_TERMINATOR}
};
```

> > Can you change the fade in from white instead of black when reloading the party screen after fusion/unfusion?
> 
> I don't think I can change it to white due to how it reloads by clearing all sprites... I can make it fade to black instead though

I don't see how that has to do with palette blending. Wouldn't clearing all sprites mean that there's no visible stuff going on?

2023-09-08 17:09 UTC, kittenchilly commented
> > > Also, I'm pretty sure we can have a single Fusion table that can handle all data.
> > 
> > 
> > I wouldn't be able to separate stuff by gen config then.
> 
> https://www.youtube.com/watch?v=kcc9hXWLDbI
> 
> ```diff
> +#define FUSION_TERMINATOR                  0xFF
> static const struct Fusion sFusions[] = {
> +#if P_GEN_5_POKEMON == TRUE
>     {0, ITEM_DNA_SPLICERS,   SPECIES_KYUREM,   SPECIES_RESHIRAM,  SPECIES_KYUREM_WHITE},
>     {0, ITEM_DNA_SPLICERS,   SPECIES_KYUREM,   SPECIES_ZEKROM,    SPECIES_KYUREM_BLACK},
> +#endif
> +#if P_GEN_7_POKEMON == TRUE
>     {1, ITEM_N_SOLARIZER,    SPECIES_NECROZMA, SPECIES_SOLGALEO,  SPECIES_NECROZMA_DUSK_MANE,   MOVE_SUNSTEEL_STRIKE, MOVE_CONFUSION},
>     {2, ITEM_N_LUNARIZER,    SPECIES_NECROZMA, SPECIES_LUNALA,    SPECIES_NECROZMA_DAWN_WINGS,  MOVE_MOONGEIST_BEAM,  MOVE_CONFUSION},
> +#endif
> +#if P_GEN_8_POKEMON == TRUE
>     {3, ITEM_REINS_OF_UNITY, SPECIES_CALYREX,  SPECIES_GLASTRIER, SPECIES_CALYREX_ICE_RIDER,    MOVE_GLACIAL_LANCE,   MOVE_CONFUSION},
>     {3, ITEM_REINS_OF_UNITY, SPECIES_CALYREX,  SPECIES_SPECTRIER, SPECIES_CALYREX_SHADOW_RIDER, MOVE_ASTRAL_BARRAGE,  MOVE_CONFUSION},
> +#endif
> +   {FUSION_TERMINATOR}
> };
> ```
> 

Ah, right... I still think it should be as similar to the other form change tables as possible so hack makers can add onto it easier

> > > Can you change the fade in from white instead of black when reloading the party screen after fusion/unfusion?
> > 
> > 
> > I don't think I can change it to white due to how it reloads by clearing all sprites... I can make it fade to black instead though
> 
> I don't see how that has to do with palette blending. Wouldn't clearing all sprites mean that there's no visible stuff going on?

I think we're talking about different things here... are you talking about how it seems to cut to black after it fades to white?

2023-09-08 17:16 UTC, kittenchilly commented
Oh wait, I think I get what you're saying, you're talking about the fade IN after it cuts to black, not the fade out before it. Oops.

2023-09-08 17:19 UTC, AsparagusEduardo commented
> Ah, right... I still think it should be as similar to the other form change tables as possible so hack makers can add onto it easier

I feel it is, there's:
- Storage ID
- Fusion Item
- The Pokémon that will be converted
- The Pokémon that will be stored
- Resulting form
- Move learned upon fusion
- Failsafe move upon defusion

Naturally, the logic will need to be adapted to this change in the data, which I feel it's easier to understand than multiple tables.
The difference is that a Pokémon may change forms in so many ways, but Fusions so far are pretty much the same.

> Oh wait, I think I get what you're saying, you're talking about the fade IN after it cuts to black, not the fade out before it. Oops.

Yeah. I think the issue with the cutting to black is that it's trying to transition from a fade out to *white* into a fade in to *black*, so there's a middle thing that tries to switch from white to black in a single frame. Let's try changing the fade in to white.

2023-09-08 17:51 UTC, kittenchilly commented
> Yeah. I think the issue with the cutting to black is that it's trying to transition from a fade out to _white_ into a fade in to _black_, so there's a middle thing that tries to switch from white to black in a single frame. Let's try changing the fade in to white.

Alright I tried making it fade in to white but it still cut to black, so it must have something to do with resetting all the sprites...

2023-09-14 17:42 UTC, kittenchilly commented
I think this is done, needs to be rereviewed.

2023-09-14 20:57 UTC, AsparagusEduardo submitted a review, later dismissed

2023-10-18 18:46 UTC, kittenchilly commented on src/party_menu.c
> +        case SPECIES_CALYREX_ICE_RIDER:
Actually, what if I make them a pokemon flag, instead of a table? It fits nicely.

2023-11-13 21:21 UTC, kittenchilly commented on src/party_menu.c
> +        case SPECIES_CALYREX_ICE_RIDER:
I managed to figure out some way to have IsFusionMon use data from the tables instead of being hardcoded.

2023-11-21 15:20 UTC, Bassoonian commented
Has it been explicitly verified that the addition of `struct Pokemon fusions[MAX_FUSION_STORAGE];` does not break saves?

2023-11-22 16:09 UTC, kittenchilly commented
> Has it been explicitly verified that the addition of `struct Pokemon fusions[MAX_FUSION_STORAGE];` does not break saves?

I've been switching between this branch and other branches, using the same save for each, and it hasn't broken or corrupted anything.

2023-11-22 17:16 UTC, AsparagusEduardo commented
> Has it been explicitly verified that the addition of `struct Pokemon fusions[MAX_FUSION_STORAGE];` does not break saves?

It has. It's also the reason why I suggested adding the struct to `PokemonStorage`, since it has enough unused free space to append the fusions.

2023-11-23 19:00 UTC, Bassoonian requested changes

2023-11-23 21:59 UTC, Bassoonian approved these changes

2023-11-23 21:59 UTC, merged