HGSS Style Pokedex
rh-hideout/pokeemerald-expansion pull request #3288
Opened 2023-09-08 16:40 UTC by AaghatIsLive

## Description
This PR adds @TheXaman's HGSS Style Pokedex

## Images
![pokedex_plus_hgss](https://github.com/rh-hideout/pokeemerald-expansion/assets/109757010/69d6b59b-6d90-4d0e-b65a-b19eb6c221cd)

## **Discord contact info**
aaghat

2023-09-08 17:03 UTC, AsparagusEduardo commented
Note for the reviewer: ***DON'T*** squash this one to avoid conflicts with users that already use this feature branch.

2023-09-09 05:30 UTC, AaghatIsLive commented
Ready for Review!

2023-09-10 17:25 UTC, AsparagusEduardo requested changes
Initial review.

2023-09-10 17:25 UTC, AsparagusEduardo commented on include/daycare.h
> +#endif
These 2 functions might be useful to have available, regardless of the `POKEDEX_PLUS_HGSS` config, so I would remove the ifdefs here and in the definitions.

2023-09-10 17:25 UTC, AsparagusEduardo commented on src/fonts.c
> +#if POKEDEX_PLUS_HGSS == TRUE
Since we're adding the Egg icon to the font itself, I would just modify the specific width.

2023-09-10 17:25 UTC, AsparagusEduardo commented on src/graphics.c
> +const u16 gPokedexPlusHGSS_Default_Pal[]             = INCBIN_U16("graphics/pokedex/hgss/HGSS_palette_default.gbapal");
Alignment here is weird. Let's remove it to keep consistant with previous graphics.

2023-09-10 17:25 UTC, AsparagusEduardo commented on src/strings.c
> +const u8 gText_Stats_Buttons[]  = _("{A_BUTTON}TOGGLE   {DPAD_UPDOWN}MOVES");
Remove alignment to keep consistency with previous strings.

2023-09-10 17:25 UTC, AsparagusEduardo commented on src/pokedex_plus_hgss.c
> +    struct FromScreenData sFormScreenData; //HGSS_Ui
Remove the unneeded `HGSS_Ui` comments.

2023-09-10 17:25 UTC, AsparagusEduardo commented on src/pokedex.c
> +#include "pokedex_plus_hgss.h"
`include/pokedex_plus_hgss.h` is already cleared out when `POKEDEX_PLUS_HGSS` is false, so there's no need to hide this include as well.

2023-09-10 17:25 UTC, AsparagusEduardo commented on src/pokedex_area_screen.c
>          if (JOY_NEW(B_BUTTON))
There's no differences between the 2 settings here.

2023-09-11 12:26 UTC, AaghatIsLive commented
Applied requested changes.

2023-09-14 18:28 UTC, AsparagusEduardo requested changes

2023-09-14 18:28 UTC, AsparagusEduardo commented on graphics/pokedex/hgss/RES_HGSS_palette.pal
Is this unused?

2023-09-14 18:28 UTC, AsparagusEduardo commented on src/pokemon_summary_screen.c
> +const struct CompressedSpriteSheet sSpriteSheet_MoveTypes =
```suggestion
const struct CompressedSpriteSheet gSpriteSheet_MoveTypes =
```

2023-09-14 18:28 UTC, AsparagusEduardo commented on src/pokemon_summary_screen.c
> +const struct SpriteTemplate sSpriteTemplate_MoveTypes =
```suggestion
const struct SpriteTemplate gSpriteTemplate_MoveTypes =
```

2023-09-14 19:21 UTC, AsparagusEduardo commented
Oh and one more thing, in the Discord we discussed adding special handling for Mew so that it shows a single entry that says "ALL" for TMs and Tutors. Could you add this?

2023-09-15 12:02 UTC, AsparagusEduardo commented
> Oh and one more thing, in the Discord we discussed adding special handling for Mew so that it shows a single entry that says "ALL" for TMs and Tutors. Could you add this?

If not, I'll try to PR it myself.

2023-10-02 20:28 UTC, AsparagusEduardo approved these changes

2023-10-02 20:28 UTC, merged