fix entry hazards switch in issue #3207
rh-hideout/pokeemerald-expansion pull request #3316
Opened 2023-09-16 23:22 UTC by DizzyEggg

Fixes #3207
Replaces #3275

Added test for fixed Toxic Spikes issue(and additional one which stemmed from the same bug).

The issue was that the side status for hazard damge was not properly set/cleared after every switch-in. I fixed it by placing it in the Disable Struct instead, which is by default cleared on fainting/switching. Also, this shouldn't have been a side status in the first place, since it affects individual battlers.

2023-09-30 23:06 UTC, AsparagusEduardo requested changes

2023-09-30 23:06 UTC, AsparagusEduardo commented on test/battle/move_effect/toxic_spikes.c
> +SINGLE_BATTLE_TEST("Toxic Spikes inflicts poison on switch in after Pecha Berry's activation") // #3207
This test is essentially the same as `Pokemon can be further poisoned with Toxic spikes after a status healing hold effect was previously used` in `test/battle/hold_effect/cure_status.c` except with the sides reversed.

Please move this test over there and edit them both to march with the following:
- `PARAMETRIZE` for Lum and Pecha berries.
- Messages for both.
- Same test name, except with a ` - Player` and ` - Opponent` suffix.
- Removing the issue number.

2023-10-01 12:00 UTC, DizzyEggg commented
Ready for review

2023-10-01 13:29 UTC, AsparagusEduardo approved these changes

2023-10-01 13:30 UTC, merged