Fix Shiny Charm doing too many rerolls by default
rh-hideout/pokeemerald-expansion pull request #3327
Opened 2023-09-20 18:32 UTC by kittenchilly

## Description
Fixes us accidentally adding 3 rerolls with the shiny charm resulting in 4 total rolls for shininess, when it should be only 2 like on cart (3 total).
This is corroborated by the SV shiny rate chart by Anubis: https://twitter.com/Sibuna_Switch/status/1593266100627709957

## **Discord contact info**
kittenchilly

2023-09-25 01:36 UTC, ghoulslash commented
The config name should probably be changed to something like SHINY_CHARM_ADDITIONAL_ROLLS, or the code changed to mimic the current config to not be confusing.

2023-09-25 17:43 UTC, kittenchilly commented
> The config name should probably be changed to something like SHINY_CHARM_ADDITIONAL_ROLLS, or the code changed to mimic the current config to not be confusing.
Good idea, I'll do the first one.

2023-09-30 23:14 UTC, AsparagusEduardo requested changes

2023-09-30 23:14 UTC, AsparagusEduardo commented on include/config/item.h
> +#define I_SHINY_CHARM_ADDITIONAL_ROLLS  2           // Amount of addition rolls added to the initial shiny roll if the player has the Shiny Charm. Set to 0 to disable Shiny Charm's effects.
```suggestion
#define I_SHINY_CHARM_ADDITIONAL_ROLLS  2           // Amount of additional shiny rolls if the player has the Shiny Charm. Set it to 0 to disable Shiny Charm's effects.
```

2023-09-30 23:34 UTC, AsparagusEduardo approved these changes

2023-09-30 23:34 UTC, merged