Fix Berserk gene issue in double battles
rh-hideout/pokeemerald-expansion pull request #3363
Opened 2023-09-30 23:04 UTC by DizzyEggg

Fixes #3180

With tests

2023-09-30 23:34 UTC, AsparagusEduardo requested changes

2023-09-30 23:34 UTC, AsparagusEduardo commented on test/battle/hold_effect/berserk_gene.c
> +    PARAMETRIZE { useItem = TRUE; }
```suggestion
    u16 item;
    PARAMETRIZE { item = ITEM_NONE; }
    PARAMETRIZE { item = ITEM_BERSERK_GENE; }
```

2023-09-30 23:34 UTC, AsparagusEduardo commented on test/battle/hold_effect/berserk_gene.c
> +    PARAMETRIZE { useItem = TRUE; slowbroPosLeft = FALSE; }
```suggestion
    u16 item;
    bool8 positionLeft = FALSE;

    PARAMETRIZE { item = ITEM_NONE; }
    PARAMETRIZE { item = ITEM_BERSERK_GENE; positionLeft = TRUE; }
    PARAMETRIZE { item = ITEM_BERSERK_GENE; positionLeft = FALSE; }
```

2023-10-01 09:02 UTC, DizzyEggg commented
Review changes done

2023-10-01 13:24 UTC, AsparagusEduardo approved these changes

2023-10-01 13:25 UTC, merged