Made function for time-based evolutions
rh-hideout/pokeemerald-expansion pull request #3369
Opened 2023-10-02 02:37 UTC by fdeblasio

## Description
This PR creates a function that gets the time of day and uses that function for time-based evolutions. This helps prevent needing to specify the day/night hours in multiple locations

## **Discord contact info**
Frankfurter#8828

2023-10-02 02:48 UTC, Pawkkie commented
Disclaimer, I am not a reviewer! :D

I'm on board for this idea, but I'd like to put forward the suggestion of renaming the function something like IsDaytime that returns a 1 or 0 depending on the result. 

You then don't need to add more defines (it's intuitive that IsDaytime would return a 1 in the daytime), and you also don't run into function name confusion, as this function does _not_ return a time of day as its current name implies (which IS a function that a lot of day night implementations have, for example), but rather a boolean.

Great to see a new contributor!

2023-10-02 11:07 UTC, fdeblasio commented
> Disclaimer, I am not a reviewer! :D
> 
> I'm on board for this idea, but I'd like to put forward the suggestion of renaming the function something like IsDaytime that returns a 1 or 0 depending on the result.
> 
> You then don't need to add more defines (it's intuitive that IsDaytime would return a 1 in the daytime), and you also don't run into function name confusion, as this function does _not_ return a time of day as its current name implies (which IS a function that a lot of day night implementations have, for example), but rather a boolean.
> 
> Great to see a new contributor!

Good idea! My original idea for this included dusk, but I never ended up implementing it due to the times overlapping with day/night, so with only two options, a boolean definitely works better

2023-10-02 12:04 UTC, LOuroboros commented on src/rtc.c
> +
```suggestion
bool8 IsDaytime(void)
{
    RtcCalcLocalTime();
    if (gLocalTime.hours >= 12 && gLocalTime.hours < 24)
        return TRUE;
    return FALSE;
}

```

2023-10-02 12:07 UTC, LOuroboros commented
I think it may be too early to add a function like this one, personally. The expansion would get such a function in due time when a DN system is merged in. Sierra's system has one, and I'd be surprised if Merp's didn't have one too. A `GetTimeOfDay` function.
It doesn't even take into account Dusk, which is the time frame to evolve Own Tempo Rockruff.

2023-10-23 17:49 UTC, AsparagusEduardo commented
Forgot to comment on this, sorry :(
Regardless of upcoming plans, this would've been a good thing to centralize via function ^^;
I disagree that it should've been converted to boolean, because we need to take into account the Dusk time of day.
Evolutions are based on the fact that something is night or not, so `GetTimeOfDay != TIME_NIGHT` should be enough to check for day evolutions.

2023-10-23 19:13 UTC, AsparagusEduardo requested changes

2023-11-18 14:46 UTC, Bassoonian commented
You updated the times to match SwSh now, but I think a generational config that defines what time morning/day/night changes would be welcome for extra customisability.

2023-11-18 14:52 UTC, AsparagusEduardo commented
> You updated the times to match SwSh now, but I think a generational config that defines what time morning/day/night changes would be welcome for extra customisability.

This I'm not sure. Gen 7 times were designed with the 12-hour night in mind for the inverted time (Ultra)Moon has, while previous times have the 3-hour evening that wasn't designed around Rockruff's dusk evolution.

I think SwSh strikes the balance well enough of having good night length + the evening being 1-hour long for Rockruff.

2023-11-18 14:53 UTC, Bassoonian commented
I can see where you're coming from, but it's also a subjective thing and some people may (for whatever reason) prefer the vanilla "midnight to noon is night, everything else is day". Besides, not everyone may be planning on using Rockruff regardless. Don't we want to maximise customisability and let the users choose?

2023-11-18 14:57 UTC, AsparagusEduardo commented
> I can see where you're coming from, but it's also a subjective thing and some people may (for whatever reason) prefer the vanilla "midnight to noon is night, everything else is day". Besides, not everyone may be planning on using Rockruff regardless. Don't we want to maximise customisability and let the users choose?

Hmm, you're right that there should be at least a vanilla setting. Alright, would be good, though not PR-blocking.

By the way @Bassoonian, can you confirm for me if the inverted (Ultra)Moon times work as intended? I'm still a bit busy a different PR ^^;

2023-11-18 15:53 UTC, Bassoonian approved these changes

2023-11-18 15:53 UTC, merged