New tests + Sheer Force / Last Resort minor bug fixes
rh-hideout/pokeemerald-expansion pull request #3378
Opened 2023-10-04 13:45 UTC by DizzyEggg

Out of curiosity I decided to take a look at Pokemon Inclement Emerald's known bug docs. It uses an older version of pokemon expansion, but I wanted to check if any of the bugs managed to persist until now. 

So far I only checked the first page, and wrote tests for all the scenarios. And surprisingly there were _still_ 2 bugs present! 

I may take a look at the doc later and check the rest, but in any case I feel like this PR is big enough currently.

2023-10-05 12:52 UTC, AsparagusEduardo commented
Can you add to the description what bugs were fixed in this PR?

2023-10-05 13:20 UTC, DizzyEggg commented on test/battle/move_effect/encore.c
> +SINGLE_BATTLE_TEST("Encore forces consecutive move uses for 2 turns for opponent")
Wait, there are two types of Encore?

2023-10-05 13:22 UTC, DizzyEggg commented
> Can you add to the description what bugs were fixed in this PR?

Done

2023-10-09 10:21 UTC, DizzyEggg commented on test/battle/move_effect/encore.c
> +SINGLE_BATTLE_TEST("Encore forces consecutive move uses for 2 turns for opponent")
I see. Could a separate issue be opened for this?

2023-10-09 10:40 UTC, AlexOn1ine commented on test/battle/move_effect/encore.c
> +SINGLE_BATTLE_TEST("Encore forces consecutive move uses for 2 turns for opponent")
Will do (later today).

2023-10-10 08:49 UTC, DizzyEggg commented
This is ready to review

2023-10-21 20:22 UTC, Bassoonian requested changes

2023-10-21 20:22 UTC, Bassoonian commented on test/battle/ability/weak_armor.c
> +    THEN {
```} THEN {```

2023-10-21 20:22 UTC, Bassoonian commented on test/battle/ability/weak_armor.c
> +    THEN {
```} THEN {```

2023-10-30 09:34 UTC, DizzyEggg commented
@Bassoonian ready to merge

2023-10-30 10:39 UTC, Bassoonian approved these changes

2023-10-30 10:39 UTC, merged