Add Snow weather animation
rh-hideout/pokeemerald-expansion pull request #3440
Opened 2023-10-20 21:20 UTC by kittenchilly

## Description
Adds a unique animation for the snow weather, created by Dat.H A.

## Images
![snow](https://github.com/rh-hideout/pokeemerald-expansion/assets/23617175/2a9e2074-8b0c-460b-a0ef-6d13fc262695)

## Issue(s) that this PR fixes
Fixes #3008

## **Discord contact info**
kittenchilly

2023-10-21 19:26 UTC, AsparagusEduardo requested changes

2023-10-21 19:26 UTC, AsparagusEduardo commented on src/battle_anim_ice.c
> +	.callback = AnimSnowflakes,
Spaces instead of tabs

2023-10-21 19:26 UTC, AsparagusEduardo commented on include/graphics.h
> +
Remvoe extra line

2023-10-22 18:26 UTC, kittenchilly commented
All reviews applied

2023-10-22 18:28 UTC, AsparagusEduardo approved these changes

2023-10-22 19:15 UTC, merged