Fixes Synchronize's OW effect and adds configs
rh-hideout/pokeemerald-expansion pull request #3480
Opened 2023-10-28 14:09 UTC by Bassoonian

This PR fixes Synchronize's OW effect (which was still limited to Emerald's and didn't include gift Pokémon etc) and adds configs (with appropriate changed effects) for all other abilities with OW effects (if appropriate, of course).

## **Discord contact info**
bassoonian

2023-10-28 14:29 UTC, AsparagusEduardo commented on src/script_pokemon_util.c
> +#if OW_SYNCHRONIZE_NATURE >= GEN_6
We're moving away from #ifdef blocks. Please use proper ifs.

2023-10-28 15:00 UTC, Bassoonian commented
This one is ready for review too!

2023-10-28 19:52 UTC, AsparagusEduardo requested changes

2023-10-28 19:52 UTC, AsparagusEduardo commented on src/pokemon.c
> +                || (GetMonAbility(&gPlayerParty[0]) == ABILITY_SUPER_LUCK && OW_SUPER_LUCK == GEN_8)))
Use a local variable and move the config checks before the ability ones.

2023-10-29 02:24 UTC, AsparagusEduardo approved these changes

2023-10-29 02:24 UTC, merged