Adds Illuminate's Gen9 effect
rh-hideout/pokeemerald-expansion pull request #3482
Opened 2023-10-28 14:26 UTC by Bassoonian

See title

## Issue(s) that this PR fixes
Fixes #3478 

## **Discord contact info**
bassoonian

2023-10-28 14:29 UTC, AsparagusEduardo commented on src/battle_ai_main.c
> +        #if B_ILLUMINATE_EFFECT == GEN_9
We're moving away from #ifdef blocks. Please use proper ifs.

2023-10-28 14:42 UTC, Bassoonian commented
Ready for actual review!

2023-10-28 16:57 UTC, AlexOn1ine commented
Could you write some tests for Illuminate?

2023-10-28 19:55 UTC, AsparagusEduardo requested changes

2023-10-28 19:55 UTC, AsparagusEduardo commented on src/battle_ai_main.c
> +            else if (aiData->abilities[battlerDef] == ABILITY_KEEN_EYE || (aiData->abilities[battlerDef] == ABILITY_ILLUMINATE && B_ILLUMINATE_EFFECT == GEN_9))
```suggestion
            else if (aiData->abilities[battlerDef] == ABILITY_KEEN_EYE || (B_ILLUMINATE_EFFECT >= GEN_9 && aiData->abilities[battlerDef] == ABILITY_ILLUMINATE))
```

2023-10-28 19:55 UTC, AsparagusEduardo commented on src/battle_ai_switch_items.c
> +                && (AI_DATA->abilities[opposingBattler] != ABILITY_ILLUMINATE && B_ILLUMINATE_EFFECT == GEN_9)
```suggestion
                && (B_ILLUMINATE_EFFECT >= GEN_9 && AI_DATA->abilities[opposingBattler] != ABILITY_ILLUMINATE)
```

2023-10-28 19:55 UTC, AsparagusEduardo commented on src/battle_ai_util.c
> +      && (defAbility != ABILITY_ILLUMINATE && B_ILLUMINATE_EFFECT == GEN_9)
```suggestion
      && (B_ILLUMINATE_EFFECT >= GEN_9 && defAbility != ABILITY_ILLUMINATE)
```

2023-10-28 19:55 UTC, AsparagusEduardo commented on src/battle_script_commands.c
> +    if (atkAbility == ABILITY_UNAWARE || atkAbility == ABILITY_KEEN_EYE || (atkAbility == ABILITY_ILLUMINATE && B_ILLUMINATE_EFFECT == GEN_9))
```suggestion
    if (atkAbility == ABILITY_UNAWARE || atkAbility == ABILITY_KEEN_EYE || (B_ILLUMINATE_EFFECT >= GEN_9 && atkAbility == ABILITY_ILLUMINATE))
```

2023-10-28 19:55 UTC, AsparagusEduardo commented on src/battle_script_commands.c
> +                        && !(ability == ABILITY_ILLUMINATE && currStat == STAT_ACC && B_ILLUMINATE_EFFECT == GEN_9)
```suggestion
                        && !(B_ILLUMINATE_EFFECT >= GEN_9 && ability == ABILITY_ILLUMINATE && currStat == STAT_ACC)
```

2023-10-28 19:55 UTC, AsparagusEduardo commented on src/battle_script_commands.c
> +                || (battlerAbility == ABILITY_ILLUMINATE && statId == STAT_ACC && B_ILLUMINATE_EFFECT == GEN_9)
```suggestion
                || (B_ILLUMINATE_EFFECT >= GEN_9 && battlerAbility == ABILITY_ILLUMINATE && statId == STAT_ACC)
```

2023-10-29 02:22 UTC, AsparagusEduardo approved these changes

2023-10-29 02:22 UTC, merged