Remove powerfulMoveEffects array
rh-hideout/pokeemerald-expansion pull request #3515
Opened 2023-11-01 19:30 UTC by AlexOn1ine

The powerfulMoveEffects array is a Game Freak leftover that doesn't have much purpose at this point. The idea was that it should discourage certain moves but some of it doesn't make that much sense. E.g. Dream Eater should only be discouraged if the target isn't asleep or Solar Beam is just a normal move under Sun.
 
Things I've done with each entry:

 - EFFECT_EXPLOSION,
 - EFFECT_DREAM_EATER,
    EFFECT_RECHARGE,
    EFFECT_SKULL_BASH,
    
    EFFECT_SUPERPOWER,
    EFFECT_ERUPTION,
    EFFECT_OVERHEAT,
    EFFECT_MIND_BLOWN,
    EFFECT_MAKE_IT_RAIN,

2023-11-01 20:17 UTC, DizzyEggg requested changes
Nice changes!

I would also add one new AI test which checks that Solarbeam is expected to use with Sun active, but otherwise it's discouraged.

2023-11-01 20:17 UTC, DizzyEggg commented on src/battle_ai_main.c
> +                DebugPrintf("isChargingMoveEffect[i]: %d", isChargingMoveEffect[i]);
Is this a testing leftover?

2023-11-01 20:18 UTC, DizzyEggg commented
Also.

This branch is out-of-date with the base branch
Merge the latest changes from upcoming into this branch.

2023-11-01 20:18 UTC, AlexOn1ine commented on src/battle_ai_main.c
> +                DebugPrintf("isChargingMoveEffect[i]: %d", isChargingMoveEffect[i]);
Yep

2023-11-01 20:37 UTC, AlexOn1ine commented
> Nice changes!
> 
> I would also add one new AI test which checks that Solarbeam is expected to use with Sun active, but otherwise it's discouraged.

Would you say that recharge moves should always be discouraged if there is no Power Herb and in case of Solar Beam sun, or only if the number of hits is the same as other moves?

2023-11-01 20:38 UTC, DizzyEggg commented
> > Nice changes!
> > I would also add one new AI test which checks that Solarbeam is expected to use with Sun active, but otherwise it's discouraged.
> 
> Would you say that recharge moves should always be discouraged if there is no Power Herb and in case of Solar Beam sun, or only if the number of hits is the same as other moves?

For now let's just consider the scenario where the number of hits is the same. In the future, we may think of some algorithms whether it's beneficial to use said moves or not.

2023-11-01 21:44 UTC, AlexOn1ine commented
> Nice changes!
> 
> I would also add one new AI test which checks that Solarbeam is expected to use with Sun active, but otherwise it's discouraged.

Done. 

I used Knock Off to circumvent a problem where Solar Beam was expected turn 2 whenever it wasn't used turn 1. I guess it's not 100% accurate but I wanted to test that Solar Beam won't be chosen once Power Herb is gone.

2023-11-02 07:44 UTC, DizzyEggg approved these changes

2023-11-02 07:44 UTC, merged