Added sprite and palettes for Mochi items
rh-hideout/pokeemerald-expansion pull request #3527
Opened 2023-11-04 18:44 UTC by hedara90

## Description
Added a single sprite for the all Mochi items introduced in the Teal Mask with different palettes for each option.

## Images
![mochi](https://github.com/rh-hideout/pokeemerald-expansion/assets/149414898/6ec4b0a6-d858-4344-855f-249f81039df1)

## **Discord contact info**
hedara#5073

2023-11-05 20:34 UTC, AsparagusEduardo commented
> Waiting for [#3530 ](https://github.com/rh-hideout/pokeemerald-expansion/pull/3530) to be merged. CI will fail until then.

Can you temporarely apply the changes in that PR to make sure that it solves the issue?

2023-11-05 20:55 UTC, hedara90 commented
Applied the fix.

2023-11-05 22:27 UTC, AsparagusEduardo requested changes

2023-11-05 22:27 UTC, AsparagusEduardo commented on graphics/items/icons/health_mochi.png
Rename to just `mochi.png`

2023-11-05 22:27 UTC, AsparagusEduardo commented on INSTALL.md
Can you go into detail why update these instructions?

2023-11-06 09:05 UTC, hedara90 commented
> > Waiting for [#3530 ](https://github.com/rh-hideout/pokeemerald-expansion/pull/3530) to be merged. CI will fail until then.
> 
> Can you temporarely apply the changes in that PR to make sure that it solves the issue?

Those changes were supposed to be in a different branch I had, I don't know how I messed up that.
But the changes are due the switch to using MODERN=1 as the default build option. On Linux systems the project won't compile without the packages arm-none-eabi-gcc and arm-none-eabi-newlib on Arch and their equivalent on Ubuntu.
So I was updating the installation instructions to match the new requirements.
![2023-11-05T11:04:31](https://github.com/rh-hideout/pokeemerald-expansion/assets/149414898/d9ccf826-559b-4591-b53e-5babe018f73c)
![2023-11-05T10:56:23](https://github.com/rh-hideout/pokeemerald-expansion/assets/149414898/f00e2ff8-96b1-4a80-b84e-d646613fda57)

2023-11-06 10:28 UTC, hedara90 commented on INSTALL.md
Apparently didn't write the reply in the correct box [here it is](https://github.com/rh-hideout/pokeemerald-expansion/pull/3527#issuecomment-1794362492)

2023-11-06 15:08 UTC, AsparagusEduardo commented on INSTALL.md
Understood.

2023-11-06 15:46 UTC, hedara90 commented
I finished the rest of the items (excluding glimmering charm), I can add them too. (and rename the PR, since it's gone beyond the scope of initial title)

2023-11-06 16:02 UTC, AsparagusEduardo commented
> I finished the rest of the items (excluding glimmering charm), I can add them too. (and rename the PR, since it's gone beyond the scope of initial title)

Sure, it should still be a small-enough to not disrupt the previously-reviewed stuff :)

2023-11-06 16:19 UTC, hedara90 commented on graphics/items/icons/health_mochi.png
Renamed the file.
And added the rest of the items

2023-11-06 19:17 UTC, AsparagusEduardo commented
Please update title and description (with images) to reflect the newer changes.

2023-11-10 00:36 UTC, AsparagusEduardo approved these changes

2023-11-10 00:57 UTC, merged