5 Parental Bond tests
rh-hideout/pokeemerald-expansion pull request #3606
Opened 2023-11-26 15:26 UTC by Bassoonian

Adds five of the many Parental Bond tests that still need to be written

## Issue(s) that this PR fixes
Partially fixes #3430 

## **Discord contact info**
bassoonian

2023-11-27 00:28 UTC, AlexOn1ine requested changes
Could you also check a normal double target move like Icy wind so both target conditions are tested?

2023-11-27 00:28 UTC, AlexOn1ine commented on test/battle/ability/parental_bond.c
> +        ASSUME(gBattleMoves[MOVE_TRIPLE_KICK].effect == EFFECT_TRIPLE_KICK);
Is the assume for the effect needed here it shouldn't effect the test in any way?

2023-11-27 00:28 UTC, AlexOn1ine commented on test/battle/ability/parental_bond.c
> +        ASSUME(gBattleMoves[MOVE_EARTHQUAKE].effect == EFFECT_EARTHQUAKE);
Again not sure if assuming Earthquake effect matters here but I think the assume for `MOVE_TARGET_FOES_AND_ALLY` should be added.

2023-11-27 00:28 UTC, AlexOn1ine commented on test/battle/ability/parental_bond.c
> +    GIVEN {
Assume for `MOVE_TARGET_FOES_AND_ALLY`

2023-11-27 00:28 UTC, AlexOn1ine commented on test/battle/ability/parental_bond.c
> +        ASSUME(gBattleMoves[MOVE_EARTHQUAKE].effect == EFFECT_EARTHQUAKE);
Again maybe remove effect EQ and add `MOVE_TARGET_FOES_AND_ALLY`

2023-11-27 11:44 UTC, Bassoonian commented
> Could you also check a normal double target move like Icy wind so both target conditions are tested?

That's why Rock Slide is there :)

2023-11-27 14:54 UTC, AlexOn1ine commented
> > Could you also check a normal double target move like Icy wind so both target conditions are tested?
> 
> That's why Rock Slide is there :)

Oh sorry, mb. Though I would also remove the flinch effect assume.

2023-11-27 15:08 UTC, Bassoonian commented
> > > Could you also check a normal double target move like Icy wind so both target conditions are tested?
> > 
> > 
> > That's why Rock Slide is there :)
> 
> Oh sorry, mb. Though I would also remove the flinch effect assume.

The flinch assume is necessary in this case, since it does in fact make the two opponents flinch (and the messages depend on that). I could alternatively move the flinch check there and make it check for regular Celebrate usage if the effect is not set to flinching, though

2023-11-27 15:13 UTC, AlexOn1ine commented
> > > > Could you also check a normal double target move like Icy wind so both target conditions are tested?
> > > 
> > > 
> > > That's why Rock Slide is there :)
> > 
> > 
> > Oh sorry, mb. Though I would also remove the flinch effect assume.
> 
> The flinch assume is necessary in this case, since it does in fact make the two opponents flinch (and the messages depend on that). I could alternatively move the flinch check there and make it check for regular Celebrate usage if the effect is not set to flinching, though

In this case I would check the HP bar a second time but negated instead of the messages and celebrate.

2023-12-21 10:20 UTC, DizzyEggg commented
What's the status of this? 👀

2024-01-11 19:49 UTC, AlexOn1ine commented
superseded by #3973

2024-01-11 19:49 UTC, closed without merging