New Feature: Level Caps
rh-hideout/pokeemerald-expansion pull request #3632
Opened 2023-12-04 18:48 UTC by AlexOn1ine

## Level Caps
- Hard Caps
- Soft Caps
- Rare Candy toggle 
- Choice between a variable and flags for setting the level caps

Credits to SBird for initial outline and PokemonCrazy for soft caps, though I deviated from their implementation.

2023-12-05 00:33 UTC, PCG06 commented
Can you try an interaction with EXP candies please?

2023-12-05 19:44 UTC, AlexOn1ine commented
> Can you try an interaction with EXP candies please?

Can't be used if `B_RARE_CANDY_CAP` is set.

2024-01-05 19:12 UTC, DizzyEggg requested changes

2024-01-05 19:12 UTC, DizzyEggg commented on include/level_caps.h
> +u8 GetCurrentLevelCap();
Let's use u32 for all arguments.
Also if the function takes no arguments, use `(void)`

2024-01-05 19:12 UTC, DizzyEggg commented on src/level_caps.c
> +    u8 i;
u32 i;

2024-01-05 19:12 UTC, DizzyEggg commented on src/level_caps.c
> +const u16 sExpScalingDown[5] = { 4, 8, 16, 32, 64 };
const u8 to reduce rom size

2024-01-05 19:52 UTC, AlexOn1ine commented
Reviews applied :eyes:

2024-01-05 21:34 UTC, katykat5099 commented
@AlexOn1ine there are level caps in thexamans challenges.

2024-01-05 21:41 UTC, AlexOn1ine commented
> @AlexOn1ine there are level caps in thexamans challenges.

I haven't looked into thexamans version level caps but this one extensively covers all cases that users can easily choose from.

2024-01-09 17:46 UTC, Bassoonian approved these changes

2024-01-09 17:47 UTC, merged

2024-03-18 15:38 UTC, zsd7200 commented
hey, PokemonCrazy here! thank you for putting this in! just saw this in the release and freaked out seeing my name in the release notes lol

i was just getting back into my project after like 3 years of being dormant and planned to clean this code up a bit but now i can just use this, this is awesome :)