Add ITEMS_COUNT to RHH rom header
rh-hideout/pokeemerald-expansion pull request #3988
Opened 2024-01-13 14:10 UTC by Ninjdai1

## Description
There was no way for an external program to access the ITEMS_COUNT.
This PR adds ITEMS_COUNT to the RHH rom header*

## **Discord contact info**
ninjdai

2024-01-13 22:18 UTC, AsparagusEduardo requested changes

2024-01-13 22:18 UTC, AsparagusEduardo commented on src/rom_header_rhh.c
> +    /*0x20*/ u8 itemNameLength;
To make the most out of this space, let's add some padding here for other `u8`s
```suggestion
    /*0x20*/ u8 itemNameLength;
    /*0x21*/ u8 padding[3];
```

2024-01-14 16:05 UTC, GraionDilach commented on src/rom_header_rhh.c
> +    /*0x14*/ u32 itemsCount;
Shouldn't this also be u16?

2024-01-14 16:06 UTC, Ninjdai1 commented on src/rom_header_rhh.c
> +    /*0x14*/ u32 itemsCount;
It should, that's an oversight

2024-01-14 17:31 UTC, AsparagusEduardo commented on src/rom_header_rhh.c
> +    /*0x17*/ u8 padding[3];
Now that `itemsCount` is u16, there's no need for the 2 extra bytes of padding.
```suggestion
    /*0x17*/ u8 padding;
```

2024-01-21 09:43 UTC, Bassoonian approved these changes

2024-01-21 21:25 UTC, AsparagusEduardo approved these changes

2024-01-21 21:25 UTC, merged