Jet Punch animation
rh-hideout/pokeemerald-expansion pull request #4067
Opened 2024-01-25 20:52 UTC by PCG06

## Description
Adds a simple animation for Jet Punch.

## Images
![jetpunch1](https://github.com/rh-hideout/pokeemerald-expansion/assets/75729017/1191180d-5a89-4117-9f10-c033e045ac55)

## Issue(s) that this PR fixes

## Feature(s) this PR does NOT handle:

## **Discord contact info**
pcg06

2024-01-25 20:54 UTC, PCG06 commented
Here's another version of the animation I made awhile before this

![jetpunch2](https://github.com/rh-hideout/pokeemerald-expansion/assets/75729017/e3096967-9ab8-4989-ab63-ba3aef307107)

2024-01-26 16:05 UTC, Jaizu commented
Mix of tabs and spaces

2024-01-26 17:48 UTC, PCG06 commented
> Mix of tabs and spaces

Done

2024-01-30 16:19 UTC, ghoulslash commented
The second version seems more true to the SV animation so I would probably vote for that one. Might look better using the waterfall hits instead of the dive sprite?

2024-01-30 16:21 UTC, PCG06 commented
> The second version seems more true to the SV animation so I would probably vote for that one. Might look better using the waterfall hits instead of the dive sprite?

Thank you! I'll try that

2024-01-30 18:57 UTC, PCG06 commented
Does this look good enough?

![jetpunch2](https://github.com/rh-hideout/pokeemerald-expansion/assets/75729017/68d801a0-5c19-426b-9a9f-9e4b4538ee5b)

2024-01-30 19:40 UTC, Bassoonian commented
I like it a lot!

2024-02-01 20:42 UTC, PCG06 commented
Can the PR be accepted or does the animation need some more improvements?

2024-02-01 20:44 UTC, AsparagusEduardo requested changes
Did you test on doubles?

2024-02-01 20:44 UTC, AsparagusEduardo commented on data/battle_anim_scripts.s
> +	createvisualtask AnimTask_AttackerStretchAndDisappear, 2
Trailing whitespace

2024-02-03 07:44 UTC, PCG06 commented
> Did you test on doubles?

Sorry for the delay, I was super busy with school. But I will send a gif within a few hours. Sorry :)

2024-02-03 17:16 UTC, PCG06 commented
> Did you test on doubles?

This is weird 🤔 
![jetpunch](https://github.com/rh-hideout/pokeemerald-expansion/assets/75729017/1cada916-341d-4e31-9889-072dc80d6d14)

2024-02-03 18:07 UTC, PCG06 commented
The issue came from `monbg ANIM_TARGET`. Clearing it didn't solve it, but removing it did.

![jetpunch](https://github.com/rh-hideout/pokeemerald-expansion/assets/75729017/2d2e7be6-4333-40dc-8346-45b4cde253b4)

2024-02-03 20:51 UTC, ghoulslash approved these changes

2024-02-06 09:07 UTC, PCG06 reviewed
I've done the changes. Can this PR be merged or are there any improvements suggested?

2024-02-06 09:18 UTC, AlexOn1ine commented on data/battle_anim_scripts.s
> +	createvisualtask AnimTask_AttackerStretchAndDisappear, 2
Edu, do you have any follow up? :eyes:

2024-02-06 10:54 UTC, AsparagusEduardo approved these changes

2024-02-06 10:55 UTC, merged