Use a 32 bit seed for new game seeding in HQ mode.
rh-hideout/pokeemerald-expansion pull request #4218
Opened 2024-02-21 14:22 UTC by tertu-m

Also adjust some comments.

## Description
Use TM1 and TM2 together for seeding during new games if `HQ_RANDOM` is enabled.

## **Discord contact info**
tertu

2024-02-21 14:32 UTC, LOuroboros commented
You might want to avoid using terms like "TM1" and "TM2" for stuff that is unrelated to technical machines, since that would taint searches involving TMs 10 to 29. I could see that being a small pita for users.

2024-02-27 12:36 UTC, mrgriffin requested changes
How doable do you think it would be to use `if (HQ_RANDOM)` rather than `#if HQ_RANDOM == TRUE`?

2024-02-27 12:36 UTC, mrgriffin commented on src/main.c
> +        REG_TM2CNT_H = 0x84;
```suggestion
        REG_TM2CNT_H = TIMER_ENABLE | TIMER_COUNTUP;
```

2024-02-27 23:51 UTC, tertu-m commented on src/main.c
> +        REG_TM2CNT_H = 0x84;
Addressed both of these.

2024-02-28 06:04 UTC, mrgriffin approved these changes

2024-02-28 06:04 UTC, merged