A bunch of Pokemon sprite changes and fixes
rh-hideout/pokeemerald-expansion pull request #4552
Opened 2024-05-11 16:27 UTC by cafei-uh

## Description
- New Basculin Blue and White entry animations
- New Xerneas Neutral entry animation based on its Active form animation
- Recolored Iron Hands and Iron Bundle back sprites
- Fixed floating back sprite of Munkidori

## Images
![TGAGcyfOazc 1](https://github.com/rh-hideout/pokeemerald-expansion/assets/46283144/3bac5b55-f702-4084-84ce-4b6291f76f42)  ![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/46283144/304dcfb8-11ad-4d8a-8a8b-5b40e653ada6)
![okngwzUUy18 1](https://github.com/rh-hideout/pokeemerald-expansion/assets/46283144/3c464f8b-f09b-4181-a9ee-baa10e015c8e)  ![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/46283144/8f5727b0-14be-4f09-abd2-8debef21d074)
![P1k5qUe-UTk 1](https://github.com/rh-hideout/pokeemerald-expansion/assets/46283144/0cd02039-1549-43ab-92cc-a380bd2943fd) ![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/46283144/303c5910-7ad7-4797-ab7f-5182a62c4e63)

https://github.com/rh-hideout/pokeemerald-expansion/assets/46283144/b0ac205d-b6f9-472b-9b67-f68e937408b5

https://github.com/rh-hideout/pokeemerald-expansion/assets/46283144/432f056c-8643-4f33-8ecc-10d7955b1f18

2024-05-11 17:46 UTC, AsparagusEduardo requested changes
Looks good! Just two things to tweak :)

2024-05-11 17:46 UTC, AsparagusEduardo commented on graphics/pokemon/iron_bundle/back.png
Our standard is to have the shiny palettes for thr backsprite pngs. Can you do that for this?

2024-05-11 17:46 UTC, AsparagusEduardo commented on graphics/pokemon/iron_hands/back.png
Here as well.

2024-05-11 20:25 UTC, cafei-uh commented on graphics/pokemon/iron_hands/back.png
Done

2024-05-12 20:07 UTC, AsparagusEduardo approved these changes

2024-05-12 20:08 UTC, merged