Force species in tests
rh-hideout/pokeemerald-expansion pull request #4810
Opened 2024-06-15 18:02 UTC by AlexOn1ine

This forces all species to be always enabled in tests. Prevent users from having a lot of tests failing. Especially applies to tests with forms because there are no assumes for them.

2024-06-15 18:11 UTC, AsparagusEduardo requested changes

2024-06-15 18:11 UTC, AsparagusEduardo commented on include/config/test.h
> +#undef P_FAMILY_BULBASAUR
```suggestion
#define P_GEN_9_CROSS_EVOS               TRUE

#undef P_FAMILY_BULBASAUR
```

2024-06-15 18:11 UTC, AsparagusEduardo commented on include/config/test.h
> +#undef P_ALOLAN_FORMS
we don't need the ones for stuff like `P_REGIONAL_FORMS` if they're only used as an easy way to disable multiple other defines
```suggestion
#define P_FUSION_FORMS                   TRUE
#undef P_ALOLAN_FORMS
```

2024-06-15 18:11 UTC, AsparagusEduardo commented on include/config/test.h
> +#undef P_GEN_2_CROSS_EVOS
```suggestion
#define P_CAP_PIKACHU_FORMS              TRUE
#undef P_GEN_2_CROSS_EVOS
```

2024-06-15 18:11 UTC, AsparagusEduardo commented on include/config/test.h
> +#undef P_FAMILY_CHIKORITA
```suggestion
#define P_FAMILY_MEW                     TRUE

#undef P_FAMILY_CHIKORITA
```

2024-06-15 18:11 UTC, AsparagusEduardo commented on include/config/test.h
> +#undef P_FAMILY_TREECKO
```suggestion
#define P_FAMILY_CELEBI                  TRUE

#undef P_FAMILY_TREECKO
```

2024-06-15 18:11 UTC, AsparagusEduardo commented on include/config/test.h
> +#undef P_FAMILY_TURTWIG
```suggestion
#define P_FAMILY_DEOXYS                  TRUE

#undef P_FAMILY_TURTWIG
```

2024-06-15 18:11 UTC, AsparagusEduardo commented on include/config/test.h
> +#undef P_FAMILY_CHESPIN
```suggestion
#define P_FAMILY_GENESECT                TRUE

#undef P_FAMILY_CHESPIN
```

2024-06-15 18:11 UTC, AsparagusEduardo commented on include/config/test.h
> +#undef P_FAMILY_ROWLET
```suggestion
#define P_FAMILY_VOLCANION               TRUE

#undef P_FAMILY_ROWLET
```

2024-06-15 18:11 UTC, AsparagusEduardo commented on include/config/test.h
> +#undef P_FAMILY_GROOKEY
```suggestion
#define P_FAMILY_MELTAN                  TRUE

#undef P_FAMILY_GROOKEY
```

2024-06-15 18:11 UTC, AsparagusEduardo commented on include/config/test.h
> +#undef P_FAMILY_SPRIGATITO
```suggestion
#define P_FAMILY_ENAMORUS                TRUE

#undef P_FAMILY_SPRIGATITO
```

2024-06-15 20:04 UTC, Bassoonian commented
We can consider this out of scope, but I really wonder if a `TEST_OVERRIDE` or `OVERRIDE` macro would be easier here so we don't need to manually undefine it and then define it once again

2024-06-16 15:10 UTC, AlexOn1ine commented
> We can consider this out of scope, but I really wonder if a `TEST_OVERRIDE` or `OVERRIDE` macro would be easier here so we don't need to manually undefine it and then define it once again

Could you elaborate what you mean?

2024-06-26 08:50 UTC, AlexOn1ine commented
> We can consider this out of scope, but I really wonder if a `TEST_OVERRIDE` or `OVERRIDE` macro would be easier here so we don't need to manually undefine it and then define it once again

Can we do this in an other pr? I don't want to modify this right now

2024-06-26 16:29 UTC, Bassoonian commented
Sure, fine by me! Feel free to open an issue and I'll look into it later

2024-06-26 16:37 UTC, Bassoonian approved these changes

2024-06-26 16:38 UTC, merged