Allowed rematches to occur if I_VS_SEEKER_CHARGING isn't enabled
rh-hideout/pokeemerald-expansion pull request #4866
Opened 2024-06-24 10:41 UTC by fdeblasio

## Description
The way the code is currently written, the step counter for rematches will never increment if `I_VS_SEEKER_CHARGING` is disabled

## **Discord contact info**
Frankfurter

2024-06-24 18:44 UTC, pkmnsnfrn commented
In plain English, does this mean that:

On `master` right now, if the Match Call is enabled _and_ the player does not have the Vs. Seeker, they will never get rematches because the counter does not increment?

2024-06-24 18:49 UTC, fdeblasio commented
> In plain English, does this mean that:
> 
> On `master` right now, if the Match Call is enabled _and_ the player does not have the Vs. Seeker, they will never get rematches because the counter does not increment?

Correct

2024-06-24 19:19 UTC, pkmnsnfrn requested changes
Okay this is my first review so I truly have no idea what I'm doing. I tried to do this in codespace but it didn't quite work, so hopefully this does.

2024-06-24 19:19 UTC, pkmnsnfrn commented on src/battle_setup.c
> +#if I_VS_SEEKER_CHARGING != 0
```c
void IncrementRematchStepCounter(void)
{
#if FREE_MATCH_CALL == FALSE
    if (!HasAtLeastFiveBadges())
        return;
    
    if (IsVsSeekerEnabled())
        return;

    if (gSaveBlock1Ptr->trainerRematchStepCounter >= STEP_COUNTER_MAX)
        gSaveBlock1Ptr->trainerRematchStepCounter = STEP_COUNTER_MAX;
    else
        gSaveBlock1Ptr->trainerRematchStepCounter++;
#endif //FREE_MATCH_CALL
}
```

I think this is easier to parse.

2024-06-24 19:19 UTC, pkmnsnfrn commented on src/battle_setup.c
> +        && (!CheckBagHasItem(ITEM_VS_SEEKER, 1))
```c
bool32 IsVsSeekerEnabled(void);
// add to include/vs.seeker.h
```


```c
bool32 IsVsSeekerEnabled(void)
{
    if (I_VS_SEEKER_CHARGING == 0)
        return FALSE;
    
    return (CheckBagHasItem(ITEM_VS_SEEKER, 1));
}
// add to src/vs.seeker.c
```

2024-06-24 20:34 UTC, fdeblasio commented on src/battle_setup.c
> +#if I_VS_SEEKER_CHARGING != 0
Done!

2024-06-24 20:34 UTC, fdeblasio commented on src/battle_setup.c
> +        && (!CheckBagHasItem(ITEM_VS_SEEKER, 1))
Done!

2024-06-26 01:28 UTC, pkmnsnfrn submitted a review, later dismissed

2024-06-26 01:35 UTC, pkmnsnfrn commented
I have tested the following scenarios:

- When the player has more than four badges, and 
    - `I_VS_SEEKER_CHARGING` is not set, `IncrementRematchStepCounter` runs and `UpdateVsSeekerStepCounter` does not.
    - `I_VS_SEEKER_CHARGING` is  not set, and the player has `ITEM_VS_SEEKER`, `IncrementRematchStepCounter` runs and `UpdateVsSeekerStepCounter` does not.
    - `I_VS_SEEKER_CHARGING` is set, and the player has `ITEM_VS_SEEKER`, `IncrementRematchStepCounter` does not run and `UpdateVsSeekerStepCounter` runs.
- When the player has less than five badges, neither function runs.

2024-06-26 08:42 UTC, AlexOn1ine commented
@fdeblasio could you please retarget this to master? It is an improtant bugfix that I think 1.8.5 should get.

2024-06-26 09:48 UTC, fdeblasio commented
> @fdeblasio could you please retarget this to master? It is an improtant bugfix that I think 1.8.5 should get.

Done! I think it needs re-approval though

2024-06-26 09:52 UTC, AlexOn1ine commented
> > @fdeblasio could you please retarget this to master? It is an improtant bugfix that I think 1.8.5 should get.
> 
> Done! I think it needs re-approval though

thx

2024-06-29 18:04 UTC, AlexOn1ine approved these changes

2024-06-29 18:18 UTC, AlexOn1ine commented
@fdeblasio weird ask but could you squash the pr and force push so CI runs again?

2024-06-29 19:52 UTC, fdeblasio commented
> @fdeblasio weird ask but could you squash the pr and force push so CI runs again?

Done!

2024-06-29 19:58 UTC, AlexOn1ine commented
> > @fdeblasio weird ask but could you squash the pr and force push so CI runs again?
> 
> Done!

Thx

2024-06-29 20:12 UTC, AlexOn1ine approved these changes

2024-06-29 20:12 UTC, merged