Add Axe Kick animation
rh-hideout/pokeemerald-expansion pull request #5039
Opened 2024-07-25 19:07 UTC by kittenchilly

## Description
Fairly simple Axe Kick animation, made by me

## Images
![axekick](https://github.com/user-attachments/assets/4d5ae57a-2f9f-4db0-9f81-d02ae99ee032)

## **Discord contact info**
kittenchilly

2024-07-25 20:01 UTC, hedara90 commented
The delay between squish and unsquish feels a bit long. Probably because what the animation is used for in other places needed it.
It can be shortened by making a new `static const union AffineAnimCmd sSquishTargetAffineAnimCmds` for this animation.

https://github.com/user-attachments/assets/e112915b-547c-4136-bf31-9af79120cc21

2024-07-25 20:04 UTC, hedara90 requested changes
hex to dec

2024-07-25 20:04 UTC, hedara90 commented on data/battle_anim_scripts.s
> +	delay 0x7
```suggestion
	delay 7
```
Use decimal numbers unless there's a good reason for hex

2024-07-25 20:04 UTC, hedara90 commented on data/battle_anim_scripts.s
> +	delay 0x2
```suggestion
	delay 2
```
Use decimal numbers unless there's a good reason for hex

2024-07-25 20:04 UTC, hedara90 commented on data/battle_anim_scripts.s
> +	createvisualtask AnimTask_SquishTarget, 0x2
```suggestion
	createvisualtask AnimTask_SquishTarget, 2
```
Use decimal numbers unless there's a good reason for hex

2024-07-26 22:05 UTC, Brandon-M-Hartman approved these changes

2024-07-26 22:07 UTC, Brandon-M-Hartman approved these changes

2024-07-28 16:56 UTC, kittenchilly commented
Alright, reviews addressed and I shortened the squish animation

2024-07-28 18:01 UTC, hedara90 approved these changes

2024-07-28 18:03 UTC, merged