Round Tests
rh-hideout/pokeemerald-expansion pull request #5196
Opened 2024-08-18 11:40 UTC by hedara90

Tests for the move Round.

## Description

Tests that other battlers that selected Round moves immediately after the first user of Round, both allies and foes.
Tests that the turn order doesn't change otherwise (no exhaustive)
Tests that the other usages of Round has doubled Base Power.
Tests that #5148 hasn't been fixed.

## Feature(s) this PR does NOT handle:

This PR does not fix #5148, it simply implements tests for the move and the bugged behavior.

## **Discord contact info**

hedara

2024-08-18 22:33 UTC, AsparagusEduardo requested changes

2024-08-18 22:33 UTC, AsparagusEduardo commented on test/battle/move_effect/round.c
> +        TURN { MOVE(playerRight, MOVE_CELEBRATE); MOVE(opponentLeft, MOVE_ROUND, target: playerLeft); MOVE(playerLeft, MOVE_IRON_HEAD, target: opponentRight); MOVE(opponentRight, MOVE_ROUND, target:
```suggestion
        TURN {
            MOVE(playerRight, MOVE_CELEBRATE);
            MOVE(opponentLeft, MOVE_ROUND, target: playerLeft);
            MOVE(playerLeft, MOVE_IRON_HEAD, target: opponentRight);
            MOVE(opponentRight, MOVE_ROUND, target: playerLeft);
        }
```

2024-08-18 22:33 UTC, AsparagusEduardo commented on test/battle/move_effect/round.c
> +        TURN { MOVE(opponentLeft, MOVE_ROUND, target: playerLeft); MOVE(opponentRight, MOVE_ROUND, target: playerLeft); }
```suggestion
        TURN {
            MOVE(opponentLeft, MOVE_ROUND, target: playerLeft);
            MOVE(opponentRight, MOVE_ROUND, target: playerLeft);
        }
```

2024-08-18 22:33 UTC, AsparagusEduardo commented on test/battle/move_effect/round.c
> +        TURN { MOVE(opponentLeft, MOVE_ROUND, target: playerLeft); MOVE(playerRight, MOVE_CELEBRATE); MOVE(playerLeft, MOVE_CELEBRATE); MOVE(opponentRight, MOVE_ROUND, target: playerLeft); }
```suggestion
        TURN {
            MOVE(opponentLeft, MOVE_ROUND, target: playerLeft);
            MOVE(playerRight, MOVE_CELEBRATE);
            MOVE(playerLeft, MOVE_CELEBRATE);
            MOVE(opponentRight, MOVE_ROUND, target: playerLeft); }
```

2024-08-18 22:33 UTC, AsparagusEduardo commented on test/battle/move_effect/round.c
> +        TURN { SWITCH(playerRight, 2); MOVE(opponentLeft, MOVE_ROUND, target: playerLeft); MOVE(playerLeft, MOVE_CELEBRATE); MOVE(opponentRight, MOVE_ROUND, target: playerLeft); }
```suggestion
        TURN {
            SWITCH(playerRight, 2);
            MOVE(opponentLeft, MOVE_ROUND, target: playerLeft);
            MOVE(playerLeft, MOVE_CELEBRATE);
            MOVE(opponentRight, MOVE_ROUND, target: playerLeft);
        }
```

2024-08-18 22:33 UTC, AsparagusEduardo commented on test/battle/move_effect/round.c
> +        ANIMATION(ANIM_TYPE_MOVE, MOVE_ROUND, opponentRight);
```suggestion
        ANIMATION(ANIM_TYPE_MOVE, MOVE_CELEBRATE, opponentLeft);
        ANIMATION(ANIM_TYPE_MOVE, MOVE_ROUND, playerRight);
        NOT ANIMATION(ANIM_TYPE_MOVE, MOVE_CELEBRATE, playerLeft);
        ANIMATION(ANIM_TYPE_MOVE, MOVE_ROUND, opponentRight);
        ANIMATION(ANIM_TYPE_MOVE, MOVE_CELEBRATE, playerLeft);
```

2024-08-18 22:33 UTC, AsparagusEduardo commented on test/battle/move_effect/round.c
> +        ANIMATION(ANIM_TYPE_MOVE, MOVE_ROUND, opponentRight);
```suggestion
        ANIMATION(ANIM_TYPE_MOVE, MOVE_CELEBRATE, playerRight);
        ANIMATION(ANIM_TYPE_MOVE, MOVE_ROUND, opponentLeft);
        NOT ANIMATION(ANIM_TYPE_MOVE, MOVE_IRON_HEAD, playerLeft);
        ANIMATION(ANIM_TYPE_MOVE, MOVE_ROUND, opponentRight);
        ANIMATION(ANIM_TYPE_MOVE, MOVE_IRON_HEAD, playerLeft);
```

2024-08-18 22:34 UTC, AsparagusEduardo commented
Some readability suggestions, but also recommends checking all 4 move animations just in case

2024-08-19 07:01 UTC, hedara90 commented
Applied suggestions

2024-08-19 17:03 UTC, AsparagusEduardo approved these changes

2024-08-19 17:03 UTC, merged