Fixed indentation for various files.
rh-hideout/pokeemerald-expansion pull request #521
Opened 2020-10-19 21:04 UTC by AsparagusEduardo

## Description
Fixes #517, except for `data/battle_scripts_1.s` which is handled by #13 .

## **Discord contact info**
AsparagusEduardo#6051

2020-10-19 21:05 UTC, ExpoSeed approved these changes

2020-10-19 21:57 UTC, Pyredrid submitted a review, later dismissed

2020-10-21 02:11 UTC, ultima-soul requested changes

2020-10-21 02:11 UTC, ultima-soul commented on src/battle_script_commands.c
> +    Cmd_attackcanceler, // 0x0
Can you align the number comments all to the right so they're in the same column? Upstream seems to do that so we should match that.

2020-10-23 15:42 UTC, ghoulslash approved these changes

2020-10-23 15:43 UTC, ExpoSeed approved these changes

2020-10-23 15:46 UTC, ultima-soul approved these changes

2020-10-23 15:46 UTC, merged