Shed Tail AI + Small Substitute AI fix
rh-hideout/pokeemerald-expansion pull request #5260
Opened 2024-08-25 19:30 UTC by SarnPoke

## Description

Adds Shed Tail AI checks to `AI_CheckViability` and `AI_CheckBadMove`. Also fixes perceived syntax error in Substitute AI.

## Issue(s) that this PR fixes

#5238

## **Discord contact info**

sarnnn

2024-08-25 20:00 UTC, AlexOn1ine reviewed
Since both Sub and Shed Tail checks are very similar I would make a function in `battle_ai_util.c` and handle the differences inside it to remove duplicate code.

2024-08-25 20:39 UTC, SarnPoke commented on src/battle_ai_main.c
> +          && (aiData->hpPercents[battlerAtk] > 50) // Just extra reinforcement that this should never be used when at 50 or less HP
Agreed, redundant checks have been removed.

2024-08-25 20:39 UTC, SarnPoke commented on src/battle_ai_main.c
> +        if (!(gBattleMons[battlerDef].status2 & (STATUS2_WRAPPED | STATUS2_ESCAPE_PREVENTION)) && aiData->hpPercents[battlerAtk] > 70) // Why are we doing this?
Removed.

2024-08-25 20:40 UTC, SarnPoke commented
> Since both Sub and Shed Tail checks are very similar I would make a function in `battle_ai_util.c` and handle the differences inside it to remove duplicate code.

This makes sense, yeah. I've done this now.

2024-08-25 21:53 UTC, SarnPoke commented
Not sure why this test is failing now, when it didn't before:
```c++
AI_SINGLE_BATTLE_TEST("AI prefers to keep its substitute over removing hazards if target is slower")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT);
        PLAYER(SPECIES_WOBBUFFET) { Speed(50); Status1(STATUS1_PARALYSIS); Moves(MOVE_SLEEP_POWDER, MOVE_STEALTH_ROCK, MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(100); Moves(MOVE_BITE, MOVE_TACKLE, MOVE_SUBSTITUTE, MOVE_TIDY_UP); }
    } WHEN {
        TURN { MOVE(player, MOVE_STEALTH_ROCK); EXPECT_MOVE(opponent, MOVE_TIDY_UP); }
        TURN { MOVE(player, MOVE_STEALTH_ROCK); EXPECT_MOVE(opponent, MOVE_SUBSTITUTE); }
        TURN { EXPECT_MOVE(opponent, MOVE_BITE); }
    }
}
```

2024-08-26 01:23 UTC, Pawkkie requested changes
The test was failing because it relies on this check:
```
if (aiData->hpPercents[battlerAtk] > 70)
    ADJUST_SCORE_PTR(WEAK_EFFECT);
```
which makes Substitute ever so slightly preferable to other status moves when the mon is at higher HP thresholds. I completely agree with axing the status2 half, but this half is what makes the Tidy Up behaviour work properly :)

I tried to make a proper "review suggestion" with this change in it which I've never done before let's see if it worked lol

2024-08-26 01:23 UTC, Pawkkie commented on src/battle_ai_util.c
> +}
```suggestion
    if (aiData->hpPercents[battlerAtk] > 70)
        ADJUST_SCORE_PTR(WEAK_EFFECT);
}
```

2024-08-26 10:06 UTC, AlexOn1ine commented on src/battle_ai_main.c
> +        IncreaseSubstituteMoveScore(battlerAtk, battlerDef, move, &score);
```suggestion
    case EFFECT_SUBSTITUTE:
    case EFFECT_SHED_TAIL:
        IncreaseSubstituteMoveScore(battlerAtk, battlerDef, move, &score);
```

2024-08-26 10:06 UTC, AlexOn1ine commented on src/battle_ai_main.c
>      case EFFECT_SUBSTITUTE:
```suggestion
```

2024-08-26 13:38 UTC, Pawkkie approved these changes

2024-08-27 10:15 UTC, AlexOn1ine commented on src/battle_ai_util.c
> +    || HasMoveEffect(battlerDef, EFFECT_LEECH_SEED))
```suggestion
     || HasMoveEffect(battlerDef, EFFECT_TOXIC)
     || HasMoveEffect(battlerDef, EFFECT_POISON)
     || HasMoveEffect(battlerDef, EFFECT_PARALYZE)
     || HasMoveEffect(battlerDef, EFFECT_WILL_O_WISP)
     || HasMoveEffect(battlerDef, EFFECT_CONFUSE)
     || HasMoveEffect(battlerDef, EFFECT_LEECH_SEED))
```

2024-08-27 19:34 UTC, closed without merging