Added Dynamic Power and Accuracy in Move Descriptions
rh-hideout/pokeemerald-expansion pull request #5327
Opened 2024-09-05 22:13 UTC by Flash1Lucky

Adds config to show the real base power and accuracy of moves after ability, stat and item modifier in Move Descriptions. This is an add-on to Move Descriptions in battle #4152.

![Screenshot 2024-09-05 180225](https://github.com/user-attachments/assets/3f66bca1-a351-4a0e-9cd3-5bab046b7f60)

## **People who collaborated with me in this PR**
Code entirely based on Move Descriptions feature from @PCG06 which was based on the implementation from Elite Redux. I just worked on merging it.

## **Discord contact info**
flash1lucky

2024-09-05 22:17 UTC, AlexOn1ine commented
Calcs are stored in simulatedDamage so instead of recalc'ing everything which will waste a lot of cycles you should fetch the damage from there.

2024-09-05 22:19 UTC, AlexOn1ine requested changes
Calcs are stored in simulatedDamage so instead of recalc'ing everything which will waste a lot of cycles you should fetch the damage from there.

Also the config should be off by default

2024-09-05 22:40 UTC, AlexOn1ine commented
In battle.h there is a struct called `AiLogicData`. There is already a field preset called moveAccuracy. Can you add this additional field to the struct:
```
u8 moveBasePower[MAX_BATTLERS_COUNT][MAX_BATTLERS_COUNT][MAX_MON_MOVES];
```
Then in function `DoMoveDamageCalcVars` can you assign `gBattleMovePower` to that field?
then you can remove all the calcs you are doing and use both fields instead .

The problem with the current implementation is that it will recalc everything each time you open the move description but we already calc it at the beginning of the turn so there is no reason to do everything again

2024-09-08 21:26 UTC, kittenchilly commented
Should be off by default anyways I think, no official game gives ever you this info

2024-09-08 21:27 UTC, Flash1Lucky commented
> Should be off by default anyways I think, no official game gives ever you this info

Yeah, that's the plan

2024-09-11 09:39 UTC, AlexOn1ine commented on src/battle_util.c
> +
```suggestion
            if (move == MOVE_NONE 
            ||  move == 0xFFFF
            ||  move == MOVE_KNOCK_OFF
            ||  move == MOVE_BRINE
            ||  move == MOVE_EARTHQUAKE
            ||  move == MOVE_MAGNITUDE)
                continue;

```

2024-09-11 09:39 UTC, AlexOn1ine commented on src/battle_util.c
> +    u32 weather = gBattleWeather;
you can just remove this var and pass `gBattlerWeather` to the funct

2024-09-11 09:39 UTC, AlexOn1ine commented on src/battle_main.c
> +            #endif
what I would do is move all those call to `Ai_InitPartyStruct` since this one will be always code it saves some lines

2024-10-11 21:50 UTC, AlexOn1ine commented
Flash, I've been thinking about and I think it is better when the calculations are   computed on the fly when the move description is accessed. Reason for is that the calcs use a lot of cycles and it is better

2024-10-18 23:31 UTC, AlexOn1ine commented on src/battle_controller_player.c
> +            return;
this part should probably be included the previous if statement so it branches out to the else statement

2024-10-18 23:59 UTC, pkmnsnfrn commented
I'm happy to test this on stream this weekend. @AlexOn1ine are there specific things and cases you'd like me to test and make sure are covered?

2024-10-25 11:05 UTC, closed without merging