Pokemon follower changes for issue #5135
rh-hideout/pokeemerald-expansion pull request #5336
Opened 2024-09-07 17:56 UTC by Liamjd14

Will fix the following issues from #5135. (makrked the currently done ones)

Raichu-Alola follower shiny a bit too sunburnt and ears/tail too light -done
Sandshrew-Alola follower ear anim south - done
Vulpix-Alola follower east/west blinking pixels - done
Ninetales-Alola follower south blinking pixels - done
Persian-Alola follower east/west could have a less pointy face - done
Graveler-Alola follower blinking pixels - done
Golem-Alola follower blinking pixels - done
Exeggutor-Alola follower stray pixels on north sprite - done
Marowak-Alola follower fire color, shiny palette slightly off - done
Ponyta-Galar follower shiny hair too yellow
Rapidash-Galar follower shiny hair too yellow
Slowbro-Galar follower should look different east and west (needs new anim code)
Growlithe-Hisui follower blinking pixels south sprite
Arcanine-Hisui follower blinking pixels
Voltorb-Hisui follower east/west shadow for rolling, shiny shading hard to see
Electride-Hisui follower east/west shadow for rolling
Typhlosion-Hisui follower shiny stomach color wrong
Sliggo-Hisui follower normal palette spots wrong color
Goodra-Hisui follower throat goo missing
Dialga-origin follower shiny missing
Palkia-origin follower shiny missing
Shaymin-sky follower sprite missing
Basculin-white follower shiny missing
Sawsbuck-Winter follower blinking pixels, horns have transparent pixels
Tornadus-Therian follower sprite missing
Thundurus-Therian follower sprite missing
Landorus-Therian follower sprite missing
Enamorus-Therian follower shiny missing
Kyurem-White follower sprite missing
Kyurem-Black follower sprite missing
Keldeo-Reolute follower sprite missing
Flabebe-all follower shiny flower stem
Floette-Eternal follower shiny wrong palette
Pumpkaboo/Gourgeist sizes missing sprites
Zydog follower missing sprite
Oricorio-pompom/pa'u/sensu follower missing sprite
Necrozma-Dawn Wings follower blinking pixel south sprite above right eye
Toxtricity-LK follower missing shiny
Calyrex-Rider follower missing shiny (gold cape/crown
Raticate-Totem follower missing sprite
Mimikyu-Totem follower missing sprite
Marowak-Totem follower missing sprite
Partner Pikachu follower missing sprite
Partner Eevee follower missing sprite

## Issue(s) that this PR fixes
Fixes the issues listed above from #5135 

## **Discord contact info**
Liamjd14

2024-09-09 15:32 UTC, hedara90 requested changes
Some fixes to do.

2024-09-09 15:32 UTC, hedara90 commented on include/config/overworld.h
> +#define OW_FOLLOWERS_ENABLED           TRUE       // Enables follower Pokémon, HGSS style. Requires OW_POKEMON_OBJECT_EVENTS. Note that additional scripting may be required for them to be fully suppo
```suggestion
#define OW_FOLLOWERS_ENABLED           FALSE     // Enables follower Pokémon, HGSS style. Requires OW_POKEMON_OBJECT_EVENTS. Note that additional scripting may be required for them to be fully supported!
```

2024-09-09 15:32 UTC, hedara90 commented on graphics/pokemon/magearna/original_color/overworld.png
Massive blinking on north and south.
Shiny very wrong colors.

2024-09-09 15:32 UTC, hedara90 commented on graphics/pokemon/calyrex/shadow_rider/overworld_shiny.pal
Blinking left side of crown on south-

2024-09-09 15:32 UTC, hedara90 commented on graphics/pokemon/calyrex/ice_rider/overworld_shiny.pal
Missing top of thingies on sides of head, should match Shadow rider-

2024-09-09 15:34 UTC, hedara90 commented
As a temporary thing I'd merge in the Pumkaboo and Totem followers. But ideally those should have different sprites for different sizes.

2024-09-09 18:16 UTC, Liamjd14 commented on graphics/pokemon/sliggoo/hisuian/overworld.png
modifled to be exact match to shiny battle sprite

2024-09-09 18:31 UTC, Liamjd14 commented
I plan on adding one other change to this if a bit. Should fix the Size problems with the Pumpkaboo line and totums

2024-09-09 19:42 UTC, Liamjd14 commented
I dont know if its worth noting but all the totems use the regular pokemons ow sprites with no scaling as far as i can tell.

2024-09-09 19:50 UTC, AsparagusEduardo commented
> I dont know if its worth noting but all the totems (even the ones i didnt edit) use the regular pokemons ow sprites with no scaling as far as i can tell.

I think it is worth noting, thank you :)

2024-09-12 16:02 UTC, hedara90 requested changes
Just 2 things

2024-09-12 16:38 UTC, Liamjd14 commented
![pokeemerald-0](https://github.com/user-attachments/assets/4c214435-b60e-4fb2-a7ad-65caa5f4ca6c)
![pokeemerald-1](https://github.com/user-attachments/assets/313b410b-8c1f-4c1b-846b-ce117ee55b1d)
 Both are fixed

2024-09-12 16:51 UTC, hedara90 approved these changes

2024-09-12 16:55 UTC, merged