Added missing forms from Ultima-s oul's FromID system.
rh-hideout/pokeemerald-expansion pull request #536
Opened 2020-10-23 15:00 UTC by AsparagusEduardo

## Description
I took the liberty of adding all the forms included currently in @ultima-soul 's ID system that are missing in PE, to at least starting to fill whatever's missing.
(In draft for now, while I test all of them.

## **Discord contact info**
AsparagusEduardo#6051

2020-11-03 03:15 UTC, AsparagusEduardo commented
Ready for review

2020-11-13 10:07 UTC, ultima-soul requested changes

2020-11-13 10:07 UTC, ultima-soul commented on src/data/text/species_names.h
> +    // Cosplay Pikachu
Add newline here.

2020-11-13 10:07 UTC, ultima-soul commented on src/pokemon.c
> +	[SPECIES_VENUSAUR_MEGA - 1] = NATIONAL_DEX_VENUSAUR,
Shouldn't use tabs for this array.

2020-11-13 19:41 UTC, AsparagusEduardo commented
Ready for re-review.

2020-11-14 00:28 UTC, ultima-soul requested changes

2020-11-14 00:28 UTC, ultima-soul commented on src/data/text/species_names.h
> +    [SPECIES_GRENINJA_ASH] = _("Giratina"),
```suggestion
    [SPECIES_GRENINJA_BATTLE_BOND] = _("Greninja"),
    [SPECIES_GRENINJA_ASH] = _("Greninja"),
```

2020-11-14 12:10 UTC, AsparagusEduardo commented
Ready for re-re-review

2020-11-15 06:48 UTC, ultima-soul approved these changes

2020-11-15 15:27 UTC, ghoulslash approved these changes

2020-11-15 15:28 UTC, merged