Fixes Partner targeting and Acupressure/Ally Switch interaction
rh-hideout/pokeemerald-expansion pull request #5446
Opened 2024-09-30 09:10 UTC by AlexOn1ine

Fixes #4565
Fixes #5154

It is a bit of a scare change but all tests pass and I don't know what else could break

2024-09-30 09:52 UTC, AlexOn1ine commented on test/battle/move_effect/acupressure.c
> -DOUBLE_BATTLE_TEST("Acupressure works on the ally if the user targeted itself but switched positions via Ally Switch")
The test was wrong. The known failing test is the correct one and afaik it never changed in any generation

2024-09-30 22:38 UTC, AlexOn1ine commented
putting on draft because I thought of more tests to write

2024-10-14 10:16 UTC, AlexOn1ine commented
Added more tests. Ready for review again.

2024-10-15 01:23 UTC, Pawkkie requested changes
I agree this is a bit spooky, I'm willing to put my trust in the tests and I think the changes look sound as is otherwise. Happy to wait for an additional reviewer if you like :)

2024-10-15 01:23 UTC, Pawkkie commented on test/battle/move.c
> +        NOT ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, playerLeft);
I think this should be `playerRight`

2024-10-15 20:05 UTC, Pawkkie commented
> Fwiw I don't think this will break anything but if you would like a second opinion I could ask someone else to take a look.

No I'm also pretty confident it's good to go barring what I think is the test typo, if you're also comfortable with it I don't think we need to hassle others :)

2024-10-15 20:06 UTC, AlexOn1ine commented
> > Fwiw I don't think this will break anything but if you would like a second opinion I could ask someone else to take a look.
> 
> No I'm also pretty confident it's good to go barring what I think is the test typo, if you're also comfortable with it I don't think we need to hassle others :)

as psf would say, merge that bitch

2024-10-15 20:35 UTC, Pawkkie commented
> as psf would say, merge that bitch

First though was the test I commented on a typo though or my error lol

2024-10-15 20:47 UTC, AlexOn1ine commented on test/battle/move.c
> +        NOT ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, playerLeft);
```suggestion
        NOT ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, playerRight);
```

2024-10-15 21:04 UTC, Pawkkie approved these changes

2024-10-15 21:04 UTC, merged