Added footprints for the Gen. 5 species
rh-hideout/pokeemerald-expansion pull request #551
Opened 2020-11-01 12:51 UTC by LOuroboros

## Description
As stated in #546 the majority of the new species introduced in the pokemon_expansion branch are currently missing their footprints.
I decided to handle the Gen. 5 footprints after having implemented the Gen. 4 ones because... well, nobody else seem to care enough and Blackforest threatened me with a knife if I didn't insert them lmao.

I took care of inserting the sprites, which were taken from Veekun.
The code for `src/data/pokemon_graphics/footprint_table.h`, `include/graphics.h` and `src/data/graphics/pokemon.h` was provided by Discord user Blackforest.

## **Discord contact info**
Lunos#4026

Showcase: https://streamable.com/92hpgt

If there's anything wrong with it, let me know.

2020-11-01 14:36 UTC, AsparagusEduardo commented
Here's my feedback:

Servine: 1px left
Pansage: 1px right
Pansear: 1px right
Panpour: 1px right
Roggenrola: 1px left
Boldore: 1px left
Gigalith: 1px up
Swoobat: 1px left
Throh: 1px down
Ducklett: 1px down
Beartic: 1px down
Mienshao: 1px left
Bouffalant: 1px up

2020-11-01 15:05 UTC, LOuroboros commented
> 
> 
> Here's my feedback:
> 
> Servine: 1px left
> Pansage: 1px right
> Pansear: 1px right
> Panpour: 1px right
> Roggenrola: 1px left
> Boldore: 1px left
> Gigalith: 1px up
> Swoobat: 1px left
> Throh: 1px down
> Ducklett: 1px down
> Beartic: 1px down
> Mienshao: 1px left
> Bouffalant: 1px up

Done :eyes:

2020-11-01 18:17 UTC, ultima-soul requested changes

2020-11-01 18:17 UTC, ultima-soul commented on src/data/pokemon_graphics/footprint_table.h
> +	[SPECIES_VICTINI] = gMonFootprint_Victini,
Tabs should be changed to 4 spaces.

2020-11-01 18:39 UTC, LOuroboros commented
Ready for re-review :eyes:

2020-11-02 03:12 UTC, ExpoSeed approved these changes

2020-11-02 18:27 UTC, ultima-soul approved these changes

2020-11-02 18:28 UTC, merged