Convert gBattleStringsTable to COMPOUND_STRINGs
rh-hideout/pokeemerald-expansion pull request #5598
Opened 2024-10-27 02:11 UTC by AsparagusEduardo

## Description
Supersedes #5499 and #5596

## Feature(s) this PR does NOT handle:
Doesn't reorder the table by ID numbers.

## **Discord contact info**
AsparagusEduardo

2024-11-02 13:28 UTC, Bassoonian requested changes

2024-11-02 13:28 UTC, Bassoonian commented on src/battle_message.c
> +static const u8 sText_GotAwaySafely[] = _("{PLAY_SE SE_FLEE}Got away safely!\p");
Is this regression intentional?

2024-11-02 13:28 UTC, Bassoonian commented on src/battle_message.c
> +static const u8 sText_PlayerDefeatedLinkTrainerTrainer1[] = _("Player defeated\n{B_TRAINER1_CLASS} {B_TRAINER1_NAME}!\p");
Is this regression intentional?

2024-11-02 13:28 UTC, Bassoonian commented on src/battle_message.c
> +static const u8 sText_PlayerWhiteout2[] = _("{B_PLAYER_NAME} panicked and lost ¥{B_BUFF1}…\p… … … …\p{B_PLAYER_NAME} whited out!{PAUSE_UNTIL_PRESS}");
Is this regression intentional?

2024-11-03 14:11 UTC, AsparagusEduardo commented on src/battle_message.c
> +static const u8 sText_PlayerWhiteout2[] = _("{B_PLAYER_NAME} panicked and lost ¥{B_BUFF1}…\p… … … …\p{B_PLAYER_NAME} whited out!{PAUSE_UNTIL_PRESS}");
no, will fix

2024-11-06 21:39 UTC, AsparagusEduardo commented
Superseded by #5649

2024-11-06 21:39 UTC, closed without merging