New sprite compressor
rh-hideout/pokeemerald-expansion pull request #5627
Opened 2024-10-31 20:50 UTC by hedara90

## Description

Improved compression algorithm for 4bpp images on the GBA.
It's utilizing a modified LZ compression scheme along with an entropy encoding called tabled Asymmetric Numeral System (tANS).
Better and more through explanation to come.

## **People who collaborated with me in this PR**

A lot of people.
@mrgriffin and @tertu-m who has answered questions about the GBA hardware whenever I had them.

## Feature(s) this PR does NOT handle:

Config option to switch automatically, currently images must be manually set to `.4bpp.smol`

## Things to note in the release changelog:

- This will be filled out.

## **Discord contact info**

hedara

2024-11-02 14:51 UTC, hedara90 commented on src/decompress.c
> +}
This is where the tANS magic happens.
And where the biggest question marks are.

2024-11-07 08:27 UTC, mrgriffin commented
I haven't looked into the performance yet at all, but I was wondering if you've done any comparisons between large LZ loads and large smol loads? Off the top of my head, I'd expect warps and connections to be quite heavy? A warp loads up to 32kB of tiles (primary + secondary), and a connection loads up to 16kB of tiles by default (secondary with `NUM_TILES_IN_PRIMARY = 512`). For connections in particular I'd be concerned about the load taking more than a frame and causing a hitch. There may be some UIs which also load large amounts of compressed data, the Frontier Pass or PokéNav region map maybe?

I'm not sure if there's any source-available and/or open source games out there with graphics that are more complex and detailed than vanilla, but it would be good to benchmark against those if possible. Tilesets and battle backgrounds are the first things that come to mind for potentially-significant differences in fidelity between GF and the community.

2024-11-07 09:58 UTC, hedara90 commented
It takes quite a while for large images.
No tANS
```
[WARN] GBA Debug:	Mode: 0
[WARN] GBA Debug:	Bitsteam size: 0
[WARN] GBA Debug:	tANS table build time: 67
[WARN] GBA Debug:	LO decoding time: 40
[WARN] GBA Debug:	Sym decoding time: 38
[WARN] GBA Debug:	Unencoded copy time: 127357
[WARN] GBA Debug:	Instruction decoding time: 535601
[WARN] GBA Debug:	Total time: 663103
```
With tANS
```
[WARN] GBA Debug:	Mode: 5
[WARN] GBA Debug:	Bitsteam size: 1883
[WARN] GBA Debug:	tANS table build time: 17702
[WARN] GBA Debug:	LO decoding time: 383654
[WARN] GBA Debug:	Sym decoding time: 2061221
[WARN] GBA Debug:	Unencoded copy time: 75
[WARN] GBA Debug:	Instruction decoding time: 369126
[WARN] GBA Debug:	Total time: 2831778
```
Most of the time is spent doing symbol decoding, which makes sense, because it's a lot of symbols.

2024-11-07 10:23 UTC, mrgriffin commented
> It takes quite a while for large images.

Thanks for the numbers! Which image is that you're using?

For reference [a frame has 280896 cycles](<https://problemkaputt.de/gbatek.htm#lcddimensionsandtimings>), so:
* lz decode is taking 1.62 frames, ~33ms.
* non-tANS decode is taking 2.36 frames, ~50ms.
* tANS decode is taking 10.08 frames, ~183ms.

It's possible that things could take an extra frame due to the overhead of everything else that goes on. Note that, e.g. the v-blank handler is a tax on every frame, and on the OW for connections a fair chunk of cycles may be spent on preparing the OAM buffer.

I'm sure it'll be possible to speed up the decode implementation somewhat. I'm not confident that a 5x speed-up is available, but it's not unheard-of :)

I suppose even if it's not possible to match LZ speeds we can always have smol as opt-in for the files which have a noticeable performance impact. That way downstream users have a way to trade performance for space if they reach a point where they've used up all 32MB.

2024-11-07 10:25 UTC, hedara90 commented
I'm using `data/tilesets/primary/general/tiles.4bpp`.
I kinda just picked the largest image that I knew where it was.

2024-11-07 10:37 UTC, hedara90 commented
It's spending ~130 cycles per nibble doing tANS decoding, I can probably bring that down a bit by just optimizing the workflow a bit. But we're approaching the point where the raw ASM needs to be looked at.

2025-01-23 14:14 UTC, DizzyEggg commented
I know this file has over 10k additions, but given that it has 139 commits, it may be a better idea to merge&squash it. Thoughts?

2025-01-23 14:17 UTC, hedara90 commented
Basically all of the commits are in 3 files, `test/compression/smol.c`, `include/decompress.h` and `src/decompress.c`.
Those are files that nobody should touch.
I think the only thing I did outside of those files is replacing the calls to decompression functions with the new wrapper for compressions with header.
So squash it, for the sake of the commit history.

2025-01-23 14:31 UTC, DizzyEggg requested changes

2025-01-23 14:31 UTC, DizzyEggg commented on include/decompress.h
> +bool32 isModeLoEncoded(enum CompressionMode mode);
Do these functions need to be here? If they're only used in decompress.c I would make them static and remove them from the header.

2025-01-23 14:31 UTC, DizzyEggg commented on include/global.h
> +#include "decompress.h"
Why is it added to `global.h`?

2025-01-23 14:31 UTC, DizzyEggg commented on src/sprite.c
> +                MgbaPrintf(MGBA_LOG_WARN, "Address: %u", &sprite->images->data);
I don't think this should be here?

2025-01-23 14:34 UTC, DizzyEggg requested changes

2025-01-23 14:34 UTC, DizzyEggg commented on src/decompress.c
> +    const u32 *pLoFreqs;
Some compilers may warn about a potentially unused variable, so I would just assign `= NULL;` to prevent compiler errors.

2025-01-23 14:45 UTC, hedara90 commented on include/sprite.h
> +             //u16 prevFrame;
Remnants of when I was working on animation frame compression

2025-01-23 14:48 UTC, hedara90 commented on src/sprite.c
> +                MgbaPrintf(MGBA_LOG_WARN, "Address: %u", &sprite->images->data);
Removed, leaving the comment above in for when I maybe get the anim frame decompressor working.

2025-01-23 14:56 UTC, hedara90 commented on include/global.h
> +#include "decompress.h"
Removed from `include/global.h` and added manually to files that need it instead.

2025-01-23 15:03 UTC, hedara90 commented on include/decompress.h
> +bool32 isModeLoEncoded(enum CompressionMode mode);
Moved and declared static

2025-01-23 18:16 UTC, DizzyEggg requested changes

2025-01-23 18:16 UTC, DizzyEggg commented on src/decompress.c
> +bool32 isModeLoEncoded(enum CompressionMode mode)
You forgot to make them static here

2025-01-29 09:41 UTC, hedara90 commented
Conflicts resolved

2025-02-10 04:23 UTC, rayrobdod commented
The majority of the methods in `tools/compresSmol/tANS.cpp` are unused: `createDecodingTable`, `encodeData`, `decodeData`, `findSymbols`, `countSymbols`, `printEncodeTable`, `printDecodeTable`, `readFileAsNibbles`, `printCounts`, `printSymbols`, `sortCount`, `areVectorsEqual`, `getStringFromUCvec`, `getUCvecFromString`, `getUCfromChar`, `getCharFromUC`

2025-02-10 08:39 UTC, hedara90 commented
In `tANS.cpp` it's because I wrote it as a standalone thing first.
I can clean it up for this if you think it's better that way.

2025-02-10 22:34 UTC, hedara90 commented
Yea, fair.
I'll come back to cleaning up the compressor properly.
It's a mess from the 8 to 16-bit refactor among other things.

2025-02-15 11:41 UTC, hedara90 commented
Cleaned up some functions and added the tilemap compressor.

2025-02-28 13:29 UTC, hedara90 commented
Updated and migration script added.

2025-02-28 18:04 UTC, hedara90 commented
VRAM tests added for `.smol` (working).

2025-03-01 21:03 UTC, hedara90 commented
Error handling added to the decompression wrapper with full-screen window for the error.

2025-03-20 22:34 UTC, DizzyEggg requested changes

2025-03-20 22:34 UTC, DizzyEggg commented on .gitignore
> +<<<<<<< HEAD
I don't think this should be here

2025-05-15 10:07 UTC, hedara90 commented
Fixed conflicts (that I caused myself)

2025-05-30 21:09 UTC, DizzyEggg approved these changes

2025-05-30 21:10 UTC, merged