FakeRtc datetime and ResetRtcScreen day increments
rh-hideout/pokeemerald-expansion pull request #5695
Opened 2024-11-20 12:44 UTC by cawtds

## Description
Adds date extraction to FakeRtc_GetRawInfo. FakeRtc currently discards any date information. 
Also added different day increments to ResetRtcScreen.

## **Discord contact info**
.cawt

2024-12-22 22:41 UTC, AlexOn1ine commented
@pkmnsnfrn do you think you could review this?

2024-12-23 05:29 UTC, pkmnsnfrn commented
I intend to review this, but I sent this to cawt and my concern stands:

> I skipped over date because nothing in vanilla Emerald uses date and I wanted to make sure my testing was accurate
> I think its fine to include and I would like to include it, but I'm unsure as to how to test it since nothing uses date

2024-12-23 10:29 UTC, AlexOn1ine commented
> I intend to review this, but I sent this to cawt and my concern stands:
> 
> > I skipped over date because nothing in vanilla Emerald uses date and I wanted to make sure my testing was accurate
> > I think its fine to include and I would like to include it, but I'm unsure as to how to test it since nothing uses date

2 Options:
1. Trust cawt if the code makes sense
2. Make a script for a trainer that can only be challenged on a specific date and use the mGBA Game Pak Sensor to manipulate the date

2024-12-24 19:48 UTC, pkmnsnfrn requested changes
Nothing in testing revealed any issues
I would like to do a future PR that makes more of this data readily accessible via scripts like date and day of week but that's not needed right now!

2024-12-24 19:48 UTC, pkmnsnfrn commented on src/fake_rtc.c
```suggestion
static void FakeRtc_AdvanceSeconds(struct SiiRtcInfo *rtc, u32 *days, u32*hours, u32 *minutes, u32 *seconds)
{
    *seconds += rtc->second;
    *minutes += rtc->minute;
    *hours += rtc->hour;

    while (*seconds >= SECONDS_PER_MINUTE)
    {
        *minutes++;
        *seconds -= SECONDS_PER_MINUTE;
    }

    while (*minutes >= MINUTES_PER_HOUR)
    {
        *hours++;
        *minutes -= MINUTES_PER_HOUR;
    }

    while (*hours >= HOURS_PER_DAY)
    {
        *days++;
        *hours -= HOURS_PER_DAY;
    }

    rtc->second = *seconds;
    rtc->minute = *minutes;
    rtc->hour = *hours;
}

static void FakeRtc_SetDayOfWeek(struct SiiRtcInfo *rtc, u32 daysToAdd)
{
    rtc->dayOfWeek = (rtc->dayOfWeek + daysToAdd) % WEEKDAY_COUNT;
}

static void FakeRtc_AdvanceDays(struct SiiRtcInfo *rtc, u32 *days)
{
    u32 remainingDaysInMonth = (sNumDaysInMonths[rtc->month - 1] + (rtc->month == MONTH_FEB && IsLeapYear(rtc->year)) - rtc->day);

    if (*days > remainingDaysInMonth)
    {
        rtc->day = 1;
        rtc->month++;
        if (rtc->month > MONTH_DEC)
        {
            rtc->month = MONTH_JAN;
            rtc->year++;
        }
        *days -= (remainingDaysInMonth + 1);
        FakeRtc_SetDayOfWeek(rtc, remainingDaysInMonth + 1);
    }
    else
    {
        rtc->day += *days;
        FakeRtc_SetDayOfWeek(rtc, *days);
        *days = 0;
    }
}
```

2024-12-24 19:48 UTC, pkmnsnfrn commented on src/fake_rtc.c
>  }
Github is being stupid but I'm trying to leave a suggestion to replace this function with

```c
void FakeRtc_AdvanceTimeBy(u32 days, u32 hours, u32 minutes, u32 seconds)
{
    struct SiiRtcInfo *rtc = FakeRtc_GetCurrentTime();
    FakeRtc_AdvanceSeconds(rtc, &days, &hours, &minutes, &seconds);

    while (days > 0)
        FakeRtc_AdvanceDays(rtc, &days);
}
```

2025-04-12 01:42 UTC, pkmnsnfrn approved these changes

2025-04-12 02:29 UTC, pkmnsnfrn commented on src/rtc.c
>  enum TimeOfDay TryIncrementTimeOfDay(enum TimeOfDay timeOfDay)
```suggestion
enum TimeOfDay UNUSED TryIncrementTimeOfDay(enum TimeOfDay timeOfDay)
```

2025-04-12 02:30 UTC, pkmnsnfrn commented on src/rtc.c
>  enum TimeOfDay TryIncrementTimeOfDay(enum TimeOfDay timeOfDay)
idk why the PR won't merge without this now... can you add `UNUSED` to `TryDecrementTimeOfDay` too and then I'll merge?

2025-04-12 02:37 UTC, khbsd commented on src/rtc.c
>  enum TimeOfDay TryIncrementTimeOfDay(enum TimeOfDay timeOfDay)
btw `TryDecrementTimeOfDay` and `TryIncrementTimeOfDay` are used for the Pokedex time of day functionality, setting them to unused may cause problems

2025-04-12 20:01 UTC, pkmnsnfrn commented on src/rtc.c
>  enum TimeOfDay TryIncrementTimeOfDay(enum TimeOfDay timeOfDay)
I think i figured it out and I think i'm just dumb

2025-04-12 20:02 UTC, pkmnsnfrn commented on src/rtc.c
> +    return dateTime.dayOfWeek;
```suggestion
    return dateTime.dayOfWeek;
}
```

2025-04-12 20:17 UTC, pkmnsnfrn approved these changes

2025-04-12 20:17 UTC, merged