Ported Lunos' Gracidea.
rh-hideout/pokeemerald-expansion pull request #570
Opened 2020-11-07 00:55 UTC by AsparagusEduardo

## Description
Title.

## **Discord contact info**
AsparagusEduardo#6051

2020-11-07 20:37 UTC, ExpoSeed commented
does this mean we are adding support for forme changes rather than leaving it to ultima's branch? i'm not sure which forme stuff is in our scope and which isn't

2020-11-07 21:16 UTC, AsparagusEduardo commented
> does this mean we are adding support for forme changes rather than leaving it to ultima's branch? i'm not sure which forme stuff is in our scope and which isn't

Ultima's branch has Form IDs which is a whole other can of worms to handle. I don't see the harm on implementing form changes that don't require scripting (like Rotom's box of appliances), specially in this case as I feel Item Expansion should be the one implementing the feature as it's based on using the item itself. Shaymin Sky reverting back to Land should be handled by Pokémon Expansion in my opinion.

2020-11-12 16:41 UTC, ultima-soul commented
So were sorta deciding a while ago, the following distinctions:
Item-based form changes in Item Expansion
Battle-based form changes in Battle Engine Upgrade
Everything else possibly Pokémon Expansion (I guess this would mainly be script-based ones)

2020-11-12 21:35 UTC, ultima-soul requested changes
Functions well.

2020-11-18 09:56 UTC, LOuroboros commented on src/party_menu.c
> +        u16 newSpecies;
How about "forme" instead? :eyes:

2020-11-28 17:19 UTC, AsparagusEduardo commented
Ready for re-review.

2020-11-28 17:23 UTC, LOuroboros commented on src/party_menu.c
> +const u8 ChangedForm[] = _("{STR_VAR_1} changed Forme!{PAUSE_UNTIL_PRESS}");
This text string was updated somewhere inbetween Gen. 4 and Gen. 7. In [the latter](https://youtu.be/jQBBXX6c6VA?t=173), the string when changing either Shaymin's or Giratina's form actually says "Pokémon transformed!".

2020-11-28 17:27 UTC, LOuroboros commented on src/party_menu.c
> +            TryChangeShayminForm(taskId,task);
Shouldn't there be an empty space inbetween `taskId` and `task`? :eyes:

2020-11-28 17:31 UTC, AsparagusEduardo commented
Re-re-ready for Re-re-review

2020-11-29 02:36 UTC, ExpoSeed approved these changes
this is fine as is

2020-12-12 06:38 UTC, ghoulslash approved these changes

2020-12-31 23:20 UTC, ExpoSeed commented
On hold until we decide form table shenanigans

2021-09-26 14:55 UTC, AsparagusEduardo commented
Superseded by #1375

2021-09-26 14:55 UTC, closed without merging