Add Liquid Ooze Test
rh-hideout/pokeemerald-expansion pull request #5753
Opened 2024-12-01 19:18 UTC by ghoulslash

Tests `If the recipient of Leech Seed's effect were to faint due to Liquid Ooze on the same turn as the victim of Leech Seed, then the victim faints before the recipient. This means that the victim's team loses the battle if both teams had their final Pokémon sent out.`

2024-12-01 20:42 UTC, AlexOn1ine commented
test fails

2024-12-02 17:21 UTC, AsparagusEduardo commented
`SPECIES_WEEZING_GALARIAN` is now `SPECIES_WEEZING_GALAR`

2024-12-10 14:35 UTC, AsparagusEduardo requested changes

2024-12-10 14:35 UTC, AsparagusEduardo commented on test/battle/ability/liquid_ooze.c
> +            MESSAGE("Foe Tentacool fainted!");
```suggestion
            MESSAGE("The opposing Tentacool's health is sapped by Leech Seed!");
            MESSAGE("The opposing Tentacool fainted!");
```

2024-12-10 14:35 UTC, AsparagusEduardo commented on test/battle/ability/liquid_ooze.c
> +            MESSAGE("Foe Tentacool fainted!");
```suggestion
            MESSAGE("Bulbasaur sucked up the liquid ooze!");
            MESSAGE("The opposing Tentacool fainted!");
```

2024-12-18 13:58 UTC, AlexOn1ine commented
The Liquid Test test message order is my fault. I moved absorb to moveend (which I think is better) but it does not work well with the order. I will try to find a fix for this or revert the moveend change.

2024-12-31 00:43 UTC, AsparagusEduardo commented
Let's slap a `KNOWN_FAILING` and call it a day

2025-01-12 09:03 UTC, AlexOn1ine commented on test/battle/ability/liquid_ooze.c
> +    PARAMETRIZE { ability = ABILITY_CLEAR_BODY; }
```suggestion
{
    KNOWN_FAILING; // message fails
    u16 ability;
    PARAMETRIZE { ability = ABILITY_CLEAR_BODY; }
```

2025-01-12 09:32 UTC, AlexOn1ine approved these changes

2025-01-12 11:15 UTC, AsparagusEduardo commented
Superseded by #6012

2025-01-12 11:15 UTC, closed without merging