[CFRU Port] Simultaneous HP Reduction
rh-hideout/pokeemerald-expansion pull request #5760
Opened 2024-12-02 18:42 UTC by AlexOn1ine

## Description
Simultaneous HP Reduction PR ported from CFRU. I've done a couple minor things differently like depracting some of the EWRAM variables. The cfru still used those and assigned the values back from the calculated values. I felt it is not needed since you can always fetch the data.

Special thanks to @Skeli789 for their CFRU implementation and doing the actual work

## Things to note in the release changelog:
```
gBattleMoveDamage, 
gMoveResultFlags
gIsCriticalHit 
```
Those above been deprecated. Instead the following should be used with an appropriate battler argument 
```
calculatedDamage[MAX_BATTLERS_COUNT];
calculatedCritChance[MAX_BATTLERS_COUNT];
moveResultFlags[MAX_BATTLERS_COUNT];
``` 
To have access in battle scripts callnatives can be used.
```
setmoveresultflags
clearmoveresultflags
jumpifmoveresultflags
jumpifcriticalhit
```

2024-12-02 20:50 UTC, AlexOn1ine commented
putting on draft. can't figure out why the test fails

2024-12-02 23:14 UTC, AlexOn1ine commented
fixed the test

2024-12-03 02:12 UTC, AsparagusEduardo requested changes
General recommendation:
I want to start promoting with the rest of the codebase that we start encapsulating whenever we can. With inline functions, we should be able to make our code more flexible.
Specifically, I'm thinking that we should add the following:
- `Get/SetBattleMoveDamage(battler)`
- `Get/SetBattleCritChance(battler)`
- `Get/SetBattleMoveResultFlags(battler)`

2024-12-03 02:12 UTC, AsparagusEduardo commented on test/battle/spread_moves.c
> +DOUBLE_BATTLE_TEST("Spread Moves: No damage will be dealt to a mon in an invulnerable position - Surf")
This should probably be Fly

2024-12-03 02:12 UTC, AsparagusEduardo commented on test/battle/spread_moves.c
> +DOUBLE_BATTLE_TEST("Spread Moves: No damage will be dealt to a mon in an invulnerable position - Surf")
Is this supposed to be for Dive?

2024-12-03 02:12 UTC, AsparagusEduardo commented on test/battle/spread_moves.c
> +    }
What is this actually testing?

2024-12-03 02:12 UTC, AsparagusEduardo commented on test/battle/spread_moves.c
> +// Can be removed once the above test passes
Will it be removed now xD

2024-12-03 07:55 UTC, AlexOn1ine commented
> I want to start promoting with the rest of the codebase that we start encapsulating whenever we can. With inline functions, we should be able to make our code more flexible.

What's the motivation behind this generally and why would encapsulation make sense in this specific case?

2024-12-03 10:35 UTC, AsparagusEduardo commented
> What's the motivation behind this generally and why would encapsulation make sense in this specific case?

This is something I want to talk more in depth on the server, so in this case might not be blocking for the purposes of the PR.
But basically, encapsulation *always* makes sense for data access and it's good practice in coding. Even if it's a single line, having new fields already encapsulated will save both us and users on the long run when we want to modify those methods to add new logic to them and even allow us to modify const data on runtime if needed.

2024-12-03 11:10 UTC, AlexOn1ine commented
> > What's the motivation behind this generally and why would encapsulation make sense in this specific case?
> 
> This is something I want to talk more in depth on the server, so in this case might not be blocking for the purposes of the PR. But basically, encapsulation _always_ makes sense for data access and it's good practice in coding. Even if it's a single line, having new fields already encapsulated will save both us and users on the long run when we want to modify those methods to add new logic to them and even allow us to modify const data on runtime if needed.

Would love to see a discussion about it because I somewhat disagree with encapsulating for the sake of it. ~~Premature optimization is the route of all evil~~

2024-12-03 14:23 UTC, AlexOn1ine commented
please supersede this pr. though I'm not going to support it with bugfixes

2024-12-04 17:25 UTC, AlexOn1ine commented
I don't know if anyone will pick this up again and I don't want the work to get lost so I will address the review comments sometime next week and support this particular pr with bugfixes

2024-12-04 17:56 UTC, AsparagusEduardo commented
> I don't know if anyone will pick this up again and I don't want the work to get lost so I will address the review comments sometime next week and support this particular pr with bugfixes

I was about to do so ^^;

2024-12-04 17:57 UTC, AsparagusEduardo commented
#5770

2024-12-04 18:06 UTC, closed without merging