Fix Pokemon with No Guard failing OHKO Moves into Semi-Invulnerable Pokemon
rh-hideout/pokeemerald-expansion pull request #5779
Opened 2024-12-06 03:28 UTC by iriv24

Issue is described in the linked issue: mon with ability no guard tries to use an OHKO move on a mon that is semi-invulernable (flying, underground, diving, etc) but the move fails, which is incorrect. Normal moves hit under these circumstances, and so should OHKO moves according to bulbapedia.

## Description
Made `BattleScript_EffectOHKO` call `accuracycheck` with `ACC_CURR_MOVE` instead of `NO_ACC_CALC_CHECK_LOCK_ON`.
I couldn't figure out why it was using `NO_ACC_CALC_CHECK_LOCK_ON` in the first place, so if there was a specific reason for that that I am missing and this is the incorrect fix, please let me know. 

Wrote accompanying test and tested the scenario in game.

## Issue(s) that this PR fixes
#5745

## **People who collaborated with me in this PR**
Issue reported by @Cafeei

## **Discord contact info**
iriv24

2024-12-06 09:08 UTC, Bassoonian commented on test/battle/move_effect/ohko.c
>  TO_DO_BATTLE_TEST("Fissure faints the target, skipping regular damage calculations")
```suggestion
}

TO_DO_BATTLE_TEST("Fissure faints the target, skipping regular damage calculations")
```

2024-12-06 09:08 UTC, Bassoonian approved these changes

2024-12-07 19:33 UTC, AsparagusEduardo requested changes
Small things, lgtm otherwise

2024-12-07 19:33 UTC, AsparagusEduardo commented on test/battle/move_effect/ohko.c
> +SINGLE_BATTLE_TEST("OHKO moves can hit semi-invulnerable mons when the user has No-Guard")
I would recommend moving this test into a `ability/no_guard.c` file, as this is a property of No Guard instead of OHKO move themselves.

2024-12-07 19:33 UTC, AsparagusEduardo commented on test/battle/move_effect/ohko.c
> +        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_NO_GUARD); }
Non-blocking, but thematically I would change this to Machamp :)

2024-12-07 21:11 UTC, merged