Add mega evolution overworld sprites
rh-hideout/pokeemerald-expansion pull request #5874
Opened 2024-12-24 23:21 UTC by khbsd

## Description

Adds mega evolution overworld sprites. This is a heavy WIP and will probably take a while to finish, so feel free to PR this branch if you'd like to chip in! :) 

## Images
![image](https://github.com/user-attachments/assets/e7dfebe7-2958-43e1-b8dc-b53cfc32c18e)
![image](https://github.com/user-attachments/assets/8f6ecee5-f397-4a8c-bb19-6980b3527b47)

## Mega Evolution Sprite Credits:
- [princess-phoenix](https://www.deviantart.com/princess-phoenix)
- [larryturbo](https://www.deviantart.com/larryturbo)
- [kidkatt](https://www.deviantart.com/kidkatt)

^This section has been added to the README.md as well.

## TODO:
- [ ] Finish sprite integration and formatting
- [ ] Add toggle

## **Discord contact info**

2025-01-28 01:28 UTC, AsparagusEduardo requested changes
Code-only review for now.

If it's ready to review, please update the description, as it's still mentioning it's a WIP branch.

ALso, I see that you're handling Ultra Necrozma data too. Will you handle other battle form changes? If not, please add a `## Feature(s) this PR does NOT handle:` section to the PR's description to clarify this.

2025-01-28 01:28 UTC, AsparagusEduardo commented on README.md
> +## Mega Evolution Overworld Sprite Credits:
Can you move these to the PR description and to a new `CREDITS.md` file? That would at least get the ball rolling for #2403

2025-01-28 01:28 UTC, AsparagusEduardo commented on src/data/pokemon/species_info/gen_1_families.h
> +    #if OW_POKEMON_OBJECT_EVENTS && OW_BATTLE_ONLY_FORMS
`OVERWORLD`'s definition already handles `OW_POKEMON_OBJECT_EVENTS`, so you only need `OW_BATTLE_ONLY_FORMS` here.

2025-01-28 01:28 UTC, AsparagusEduardo commented on src/data/pokemon/species_info/gen_1_families.h
> +            OVERWORLD(
Please align the `OVERWORLD` macros to `FOOTPRINT`, with the `#if` 4 spaces back.

2025-01-28 01:28 UTC, AsparagusEduardo commented on src/data/pokemon/species_info/gen_1_families.h
> +            OVERWORLD_FEMALE(
Female follower data don't need to be set if it's the same as Male data. It defaults to it if not set.

2025-01-28 01:28 UTC, AsparagusEduardo commented on src/data/pokemon/species_info/gen_4_families.h
> +        #endif //OW_POKEMON_OBJECT_EVENTS && OW_BATTLE_ONLY_FORMS
Probably doesn't need the comment here, but it's non-blocking, so whatever ^^;

2025-01-28 02:32 UTC, khbsd commented on src/data/pokemon/species_info/gen_1_families.h
> +    #if OW_POKEMON_OBJECT_EVENTS && OW_BATTLE_ONLY_FORMS
hmm, if that's the case, should i just put `OW_BATTLE_ONLY_FORMS` in the definition too?

2025-01-28 02:42 UTC, khbsd commented on src/data/pokemon/species_info/gen_1_families.h
> +    #if OW_POKEMON_OBJECT_EVENTS && OW_BATTLE_ONLY_FORMS
wait, no, answered my own question lol.

2025-01-31 01:28 UTC, AsparagusEduardo approved these changes
Finished checking the sprites on the visualizer, look good to me :)

2025-01-31 01:29 UTC, merged