Consolidated Frontier teams into battle_frontier_trainers.h
rh-hideout/pokeemerald-expansion pull request #5892
Opened 2024-12-28 04:11 UTC by fdeblasio

## Description
Removed all gBattleFrontierTrainerMons variables and moved their contents into gBattleFrontierTrainers to reduce the number of files needed to be edited if adding any new trainers
Also consolidates the three FRONTIER_MONS_PSYCHIC_2X macros into one since the expansion isn't constrained into needing an identical checksum like pret is

## **Discord contact info**
Frankfurter0

2025-01-01 15:07 UTC, Bassoonian requested changes

2025-01-01 15:07 UTC, Bassoonian commented on migration_scripts/1.10/convert_battle_frontier_trainers.py
1.10 already came out, so this will need to be /1.11/. It also needs to be added to the readme in the migration script folder

2025-01-02 00:00 UTC, fdeblasio commented on migration_scripts/1.10/convert_battle_frontier_trainers.py
Done!

2025-02-09 21:16 UTC, Bassoonian approved these changes

2025-02-09 21:17 UTC, merged