Codify new expansion release schedule
rh-hideout/pokeemerald-expansion pull request #5916
Opened 2024-12-31 05:03 UTC by pkmnsnfrn

## Description
Add a document detailing the proposed expansion release schedule and process around Big Features

## **People who collaborated with me in this PR**
@Pawkkie 

## **Discord contact info**
pkmnsnfrn

2024-12-31 05:26 UTC, Pawkkie commented
Putting feedback here rather than discord, I think the doc itself is great as I've said there:
- Would suggest putting it in `docs/team_procedures`, and also moving `scope.md` to that folder. I think it makes sense to have all our developer-facing docs in one place. Perhaps that's not suitable though, feel free to ignore
- Should add to the website via `SUMMARY.md` as per #5706

--- 
Do we think it's fine if I approve this given that I helped write some of it, or am I fine to do so given that it's been met with approval from the problem squad (assuming the latter but want to clarify with a second opinion first)

2024-12-31 16:26 UTC, pkmnsnfrn commented
> * Would suggest putting it in `docs/team_procedures`, and also moving `scope.md` to that folder. I think it makes sense to have all our developer-facing docs in one place. Perhaps that's not suitable though, feel free to ignore
Done
> * Should add to the website via `SUMMARY.md` as per [Added scope document and made changes to pull request template #5706](https://github.com/rh-hideout/pokeemerald-expansion/pull/5706)
Done
> Do we think it's better if I don't approve this given that I helped write some of it, or am I fine to do so given that it's been met with approval from the problem squad (assuming the latter but want to clarify with a second opinion first)
I think you should not approve but don't feel strongly

2024-12-31 17:47 UTC, AsparagusEduardo requested changes

2024-12-31 17:47 UTC, AsparagusEduardo commented on .github/pull_request_template.md
> +<!--- If you believe this PR qualifies as a "Big Feature" as defined in docs/schedule.md, please let a Maintainer know! -->
Scope's directory should also be updated
```suggestion
<!--- If you believe this PR qualifies as a "Big Feature" as defined in docs/team_procedures/schedule.md, please let a Maintainer know! -->
```

2025-01-01 13:16 UTC, AsparagusEduardo approved these changes

2025-01-02 21:01 UTC, AsparagusEduardo commented on .github/pull_request_template.md
> +<!--- If you believe this PR qualifies as a "Big Feature" as defined in docs/schedule.md, please let a Maintainer know! -->
You still need to update the scope document URL

2025-01-12 15:41 UTC, AsparagusEduardo commented
Please solve conflicts. I added the change I suggested earlier

2025-01-13 18:40 UTC, tertu-m approved these changes
I like this.

2025-01-13 19:52 UTC, merged