Sync battle engine v2
rh-hideout/pokeemerald-expansion pull request #8
Opened 2020-10-12 21:20 UTC by ExpoSeed

i can't believe i fucked this up 3 times now

2020-10-12 21:23 UTC, Pyredrid approved these changes, later dismissed
The only thing changed was the destination branch due to user error, my previous comments on PR #6 are still relevant.  This merge has been tested with a full QA session from the beginning of the game to the Hall of Fame. No obvious issues found.

2020-10-12 21:23 UTC, AsparagusEduardo submitted a review, later dismissed
Same review as #6 :

> I've done tests to check if current issues are still present after the merge and they still are, so we can at least be sure that the merge is good in that sense.
As this is the first merge in a long time, if there are issues that might originate from this, we can deal with them as they come up.

2020-10-13 04:22 UTC, ultima-soul requested changes, later dismissed

2020-10-13 04:22 UTC, ultima-soul commented on src/battle_util.c
> +void HandleAction_UseMove(void)
Sync these functions based on the gist provided on Discord. The functions were modified before being moved to battle_util.

2020-10-13 14:40 UTC, ExpoSeed commented
Done

2020-10-13 16:10 UTC, ultima-soul approved these changes

2020-10-13 16:44 UTC, ghoulslash approved these changes

2020-10-13 17:13 UTC, merged